### ISSUE TITLE
Is It Possible Rotate Canvas Without Device Rotation

### ISSUE THREAD

**Issue by skyberk** [CreateJS/EaselJS#1044]
I want to rotate canvas portrait to landscape when device orientation still portrait mode. I tried with css but it does not work. Also i managed to rotate with the code below. But it is not working well stage still drawing with portrait width height. In short i want to landscape preview when device on portrait mode. Thank you from now.

```
s_oStage = new createjs.Stage(canvas);
s_oStage.regX = 0;
s_oStage.regY = 800   
s_oStage.rotation =90;
```

**Comment by danzen** [comment]
You can put everything in a Container on the stage and then rotate and scale the container.
