### ISSUE TITLE
New touch issues on touch-screen boards with new Chrome

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#1067]
It looks like Chrome has changed something in the way it handles touch - at least on touch boards - reports have come in from people not being able to use touch on Smartboard, Ctouch, Promethean and Clevertouch boards with Chrome version: 99.0.4844.51 (Official Build) (64-bit) . Chrome was working pre March 1st.

We expect it is something in the CreateJS although at ZIM we run our own version that is roughly the same.  Wondering if there are any reports here, any fixes or any thoughts.  Just starting to look into it again.  Cheers.

**Comment by dijitaletkinlikler** [comment]
I can test this page on the smartboard tomorrow. There were no problems with carrying in the activities I used at school today. The chrome version used on the smart board at school is 99. I'll test it tomorrow and get back to you.

**Comment by dijitaletkinlikler** [comment]
Today I had the opportunity to experiment extensively on the smart board. I haven't encountered a problem with touch.

**Comment by danzen** [comment]
Okay - looks like it might have been a false alarm - where perhaps it was a specific issue with the code being used.  The tests have gone out on our basic touch and results back were it is all working fine.  Closing the issue.
