### ISSUE TITLE
Different Luminence values for Saturation vs Hue

### ISSUE THREAD

**Issue by leonwind** [CreateJS/EaselJS#1074]
Hi,

I was just wondering if there is a specific reason why you are using different luminence values for [Saturation](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/filters/ColorMatrix.js#L284) and for [Hue](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/filters/ColorMatrix.js#L310).

As far as I know the values for Hue should be correct if you use [sRGB](https://en.wikipedia.org/wiki/SRGB) which uses the [BT.709](https://en.wikipedia.org/wiki/Rec._709) standard underneath. The relative luminence values for it are described [here](https://en.wikipedia.org/wiki/Relative_luminance) and match with your Hue adjustment but not with the Saturation one.

Thanks a lot!
Leon

**Comment by gskinner** [comment]
it's been a long time, but iirc it is a direct copy of how the Flash (now Animate) authoring environment applies color effects.

**Comment by leonwind** [comment]
The only source I could find for this is this [old documentation from 1993](http://www.graficaobscura.com/matrix/index.html).
He quoted that these values are better for the linear RGB space but I think the current best practise has changed in the last 30 years, time flies :D, and I think your Hue values are actually providing better results.

But no need to change, I was just curious about it!

**Comment by danzen** [comment]
I think Grant has a little "in" at Adobe on occasion!  I am closing this, but anyone is welcome to continue the conversation!
