### ISSUE TITLE
Createjs website dose not work !

### ISSUE THREAD

**Issue by hardworker0ir** [CreateJS/EaselJS#1081]
Hi. Just try to open createjs.com. and you can see that this website does not work anymore. it just shows me a white page.
I tried to find the connection ways with them but I didn't find any email or number. do you know why this website does not work? Do you have the same problem or not? I opened the console and I saw that there were a couple of errors on this website so it does not work. it's very weird. a big and professional website suddenly does not work.

![createjs](https://github.com/CreateJS/EaselJS/assets/82308288/f9cdc7f4-fa7c-4061-b3a6-cdc9d8624a75)

**Comment by danzen** [comment]
Not sure if there was an issue at the time.  The site works for me at the moment.  So assume all is good now.  Cheers.

![image](https://github.com/CreateJS/EaselJS/assets/380281/1280a1ca-0766-4c16-9e2d-d3290e895b3c)
