### ISSUE TITLE
Ticker.addListener(stage.update) does not work

### ISSUE THREAD

**Issue by takfuruya** [CreateJS/EaselJS#153]
Error

``` javascript
Uncaught TypeError: Object [object Window] has no method 'getConcatenatedMatrix'
```

Code

``` javascript
var canvas, stage, circle;

function init() {
    canvas = document.getElementById('canvas');
    stage = new Stage(canvas);
    circle = new Shape();
    circle.graphics.beginFill("orange").drawCircle(0, 0, 10);
    circle.y = 75;
    stage.addChild(circle);
    Ticker.addListener(loop);
    Ticker.addListener(stage.update);
}

function loop() {
    circle.x ++;
    // stage.update();
}
```

Rather than calling stage.update() at the end of the loop function, I added in the Ticker listener but this does not work.
(easeljs-0.4.2.min.js)

**Comment by scotself** [comment]
Just a related comment that this answer helped me understand better...I was trying to detach an event listener and the attached listener was anonymous. Unless I don't know how (certainly likely), you really need a named listener to be able to easily remove it.

**Comment by danzen** [comment]
var listener = circle.on("click", function(){});
// later...
circle.off("click", listener);
// the above works properly.

// I have had problems with this:
circle.on("click", doStuff);
function doStuff(){}
// later this does not seem to work 
circle.off("click", doStuff);

**Comment by lannymcnie** [comment]
The `on` function creates a closure every time, so you can not remove a listener by passing the same function to `off()`. Your first approach is right.

If you aren't using a scope param, just use `addEventListener` and `removeEventListener` which are the same as DOM events, and you can pass the same function to each to add/remove.
