### ISSUE TITLE
IE 10 Click event Doesn't work correctly

### ISSUE THREAD

**Issue by omezzine** [CreateJS/EaselJS#233]
Am building a Card game all work perfect on other browsers even IE9  but  on IE10  i have a problem with those events

Card.onDoubleClick = function(ev){
// do something
}

Card.onPress = function(e){
// do somthing
}

when i double click on card for the first time it work  but when i click on other cards it doesn't work and log show me that  i clicked on the first card 

when i move away the cursor from the canvas and i come back it work again but for one time

**Comment by strohrdanz** [comment]
I'm having the same issue - double click will register but a single click will not, in IE10 and 11. I have touch enabled, and enabling then disabling gives me an error. Any other fixes?

**Comment by lannymcnie** [comment]
@strohrdanz What is the error you get?

**Comment by strohrdanz** [comment]
"Unable to get property 'f' of undefined or null reference" in the createjs minified file

**Comment by lannymcnie** [comment]
Any chance you can toss in a combined minified file instead? Obviously this error is pretty unhelpful as-is :)

**Comment by strohrdanz** [comment]
I believe that's what I'm using... createjs-2014.12.12.min.js.  I tried switching it out for the latest version but then things stopped working...

**Comment by strohrdanz** [comment]
I've also got click events registering on different pages, so i'm not sure what's going on. It's not working only on one page, and the double click and mouseover events are registering, just not a single click, which is what I need.

**Comment by gskinner** [comment]
I think Lanny means the unminified combined file. The latest is here:
https://code.createjs.com/createjs-2015.05.21.combined.js

**Comment by strohrdanz** [comment]
@gskinner @lannymcnie  ah, makes sense. I still get the same error with the unminified version, referencing this function: 

Touch._IE_disable = function(stage) {
		var f = stage.__touch.f;

		if (window.navigator["pointerEnabled"] === undefined) {
			window.removeEventListener("MSPointerMove", f, false);
			window.removeEventListener("MSPointerUp", f, false);
			window.removeEventListener("MSPointerCancel", f, false);
			if (stage.canvas) {
				stage.canvas.removeEventListener("MSPointerDown", f, false);
			}
		} else {
			window.removeEventListener("pointermove", f, false);
			window.removeEventListener("pointerup", f, false);
			window.removeEventListener("pointercancel", f, false);
			if (stage.canvas) {
				stage.canvas.removeEventListener("pointerdown", f, false);
			}
		}
	};

**Comment by lannymcnie** [comment]
The error is likely caused by calling if `Touch.disable()` when it is disabled already (since the stage.__touch variable is nulled when you disable). It is probably worth adding a check for this in the Touch class to avoid this error.

I will look into the click/double-click error.

**Comment by strohrdanz** [comment]
I ended up adding this line in the p.enableDOMevents function as a workaround:

ls["click"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };

**Comment by lannymcnie** [comment]
I did some quick testing in IE11/Edge, and `click`/`doubleClick` works as expected when the Touch class is enabled. 

Your solution dispatches a doubleclick when a click happens, so it doesn't really make sense.

The reason we don't use a browser `click` event on the Canvas in the Stage class is that it will register for the entire canvas, so it can not differentiate if the EaselJS target that was "pressed" is also the target that was "released".

I will do some testing in IE10, but so far have been unable to reproduce this issue.

**Comment by StefanRein** [comment]
Hey guys, by calling 

createjs.Touch.disable(stage);

I get in IE11 still the above error (version 0.8.1):
>"Unable to get property 'f' of undefined or null reference" at a._IE_disable

But I definitely didn't called this before on the stage, so I just wrote for now:
`stage.__touch && createjs.Touch.disable(stage);`

**Comment by alelp** [comment]
It's still happening in 1.0.0.
