### ISSUE TITLE
SpriteSheetUtils.extractFrame has not loaded.

### ISSUE THREAD

**Issue by aholla** [CreateJS/EaselJS#276]
Hi, I'm using "SpriteSheetUtils.extractFrame" to extract a frame from the atlas. The problem is that the image has not had time to load and therefore does not have a width and height property when trying to access it.

``` javascript
SpriteSheetUtils.extractFrame = function(spriteSheet, frame) {
    if (isNaN(frame)) {
        frame = spriteSheet.getAnimation(frame).frames[0];
    }
    var data = spriteSheet.getFrame(frame);
    if (!data) { return null; }
    var r = data.rect;
    var canvas = SpriteSheetUtils._workingCanvas;
    canvas.width = r.width;
    canvas.height = r.height;
    SpriteSheetUtils._workingContext.drawImage(data.image, r.x, r.y, r.width, r.height, 0, 0, r.width, r.height);
    var img = new Image();
    img.src = canvas.toDataURL("image/png");
    return img;
}
```

Could the image have and "onload" event to make sure it is loade before it is returned?

**Comment by megamasterO** [comment]
> Yes, unfortunately we can't delay the return until the image is loaded (if you had animation running it would cause a very noticeable pause). You'll have to monitor the .complete and .onload.
> 
> As an important note: If you're displaying the frame in EaselJS, it's always faster to use a Sprite to display the frame than to extract the frame. One place where you might use extractFrame is for using it with a bitmap fill.

So would it be okay to use this method to create alphamapfilters for specific frames in a spritesheet?
