### ISSUE TITLE
Uncaught An error has occurred. This is most likely due to security restrictions cross-domain images. 

### ISSUE THREAD

**Issue by wpoosanguansit** [CreateJS/EaselJS#297]
Hi,

I have searched for the solution to the restriction but what I have found so far doesn't seem to overcome the issue.  I have images displayed in the canvas and the source is from the cloud storage.  Is there a way to suppress the error or turn it off on the canvas itself?  Thanks for your help.

**Comment by Atila027** [comment]
Hi.
I have some error llike this.
But I can not fix 
please help me
