### ISSUE TITLE
Real time Vector Shapes don't work on Chrome 27/Android

### ISSUE THREAD

**Issue by Makac** [CreateJS/EaselJS#327]
Real time vector shapes don't appear in Chrome 27 on Android devices. The only way we've managed to get them to show up is by using bitmap caching.

The problem is clearly there when testing the demos, for example:
- The Caching demo: Nothing shows up unless "caching enabled" is checked.
- Alpha Mask Filter Demo: The blurry image isn't visible.
- Space Rocks Demo: Doesn't show loading text, nor the animations - just a black background
- Local to Global Demo: Text shows and flies around, geometric shapes not visible
  -Vector Mask demo: Background shows, no masking visible

We've reproduced this on two different devices:
- Samsung Galaxy Note: Chrome 27.0.1453.90, Android 4.0.4
- Samsung Galaxy SIII Mini: Chrome 27.0.1453.90, Android 4.0.4

**Comment by adampasz** [comment]
Not sure if anyone still cares, but  I can repro. this on a Galaxy S3 running 4.1.2.
