### ISSUE TITLE
300ms click delay on touch devices

### ISSUE THREAD

**Issue by mayank-finoit** [CreateJS/EaselJS#347]
On touch devices (e.g iphone, ipad, android) there is a delay of 300ms on click event. So if i want to add fast click event on some shape there will be a delay which is causing a lot of problem.

**Comment by zipspeed** [comment]
Same problem @gskinner

**Comment by zipspeed** [comment]
Find the solution, should enable touch via createjs.Touch.enable(stage); then use mousedown event
