### ISSUE TITLE
lineTo does nothing without moveTo

### ISSUE THREAD

**Issue by aholla** [CreateJS/EaselJS#370]
If you just call "lineTo" you will get no line, but if you first call "moveTo" the line will appear:

e.g:

this does not work:

```
var line = new createjs.Graphics();
line.beginStroke( '#FF00FF' );
line.lineTo( 300, 0 );
```

This however does work:

```
var line = new createjs.Graphics();
line.beginStroke( '#FF00FF' );
line.moveTo( 0, 0 );
line.lineTo( 300, 0 );
```

I would expect it to have a default position of 0, 0 and then draw from there.

**Comment by Rikhter** [comment]
Hi there could you consider updating your API docs at least to reflect this just spent an unreasonable amount of time scratching my head over this issue of my lines not drawing.

Another thing I'd like to highlight is the moveTo must be after the beginStroke in order for this to work again seemingly counter intuitive.

**Comment by lannymcnie** [comment]
Updated `lineTo` docs. This issue will also manifest in other places (such as curveTo), but I think the one doc comment should suffice. Thanks guys!

**Comment by Rikhter** [comment]
@lannymcnie thanks!
