### ISSUE TITLE
Bower install failing

### ISSUE THREAD

**Issue by mukulseth** [CreateJS/EaselJS#467]
I'm trying to setup easeljs as a bower dependency, and everytime I try to do "bower install" I get the following error --

bower not-cached    git://github.com/CreateJS/EaselJS.git#~0.7.1
bower resolve       git://github.com/CreateJS/EaselJS.git#~0.7.1
bower not-cached    git://github.com/CreateJS/EaselJS.git#*
bower resolve       git://github.com/CreateJS/EaselJS.git#*
bower checkout      easeljs#master
bower resolved      git://github.com/CreateJS/EaselJS.git#f9d12964d4
bower ENORESTARGET  No tag found that was able to satisfy ~0.7.1

Additional error details:
No versions found in git://github.com/CreateJS/EaselJS.git

**Comment by hayesmaker** [comment]
It still doesn't contain SpriteContainer and SpriteStage, despite it saying it is v0.8.0.

**Comment by lannymcnie** [comment]
Unfortunately, bower uses excludes to omit files, so in order to include it, we would have to exclude every class individually, instead of the "src" folder that we do now. 

We have added a "webgl-NEXT.js" to the lib folder, which should be included in the bower download.
