### ISSUE TITLE
SpriteContainer: must use the same sprite sheet, can this param change to  optional?

### ISSUE THREAD

**Issue by liuyi** [CreateJS/EaselJS#536]
Because we have lots of textures, more than 1000 pictures. Player can create items with these pictures, and add it to stage. If we use SpriteContainer to be the parent container, we can not merge so many images in one big sprite image. It's mean that we can not use WEBGL in createjs. I think this api is not 
 suitable in many work scenes.

Can this API would be change to don't need to use the same SpriteSheet?

**Comment by lannymcnie** [comment]
Closing this. Please check out StageGL, which will be merged into master very soon: https://github.com/CreateJS/EaselJS/tree/StageGL-beta
