### ISSUE TITLE
Matrix2D not translating the same as previous versions

### ISSUE THREAD

**Issue by mcfarljw** [CreateJS/EaselJS#539]
I'm specifically referring to this commit and line:

https://github.com/CreateJS/EaselJS/blob/3ed3b894d5e53c07869c4a7f0ca405f3ee583f15/src/easeljs/geom/Matrix2D.js#L392

When I revert the `translate` method to what it was in previous versions things display correctly:

```
this.tx += x;
this.ty += y;
```

Here is the bit of code we're using, that given the same data input produces different matrix values between versions:

```
var ms = shape.getMatrix();
var sx = data.w / spriteBounds.width;
var sy = data.h / spriteBounds.height;
ms.scale(sx, sy);
ms.translate(-data.w / 2, -data.h / 2);
ms.rotate(data.rot * Math.PI / 180);
```

Any thoughts on why this might be happening?

**Comment by FumioNonaka** [comment]
I wrote the article, "[Critical changes of the Matrix2D's transform methods in the EaselJS 0.8.0](http://f-site.org/articles/2015/01/09000000.html)", to show some snippets to get the same results as old versions with version 0.8.0.
