### ISSUE TITLE
Stagemousedown : detect click on the empty part of the stage

### ISSUE THREAD

**Issue by yayayayazam** [CreateJS/EaselJS#544]
Hi, I wonder if it is possible to create a "pressempty" event for the stage object when I click on the empty part of the stage. I think the "getObjectUnderPoint" has already been called every time I click the stage, and it is wasted to call it again to detect the empty click.

**Comment by yayayayazam** [comment]
Thank you for your advice and easeljs is awesome  : D


What I want is to close some panels when I click on a nearly transparent background. Since I want to run this programe on iPad 2 and I find that a large background image gives a performance hit. So I cancel the background and detect the the press on empty part like:


stage.on("stagemousedown", function(event){
	var test = this.getObjectUnderPoint(event.stageX, event.stageY);
	if(test === null){
		panel.toggleOff();
	}
});


I also write a "stagepressmove" since the "pressmove" needs opaque objects and I don't have a background on stage.

**Comment by gskinner** [comment]
I just pushed an update that includes `MouseEvent.relatedTarget`.

So you can now tell if anything was the target of a mouse press / release. Note that only valid mouse targets (ie. with a listener or cursor) are counted.

````
stage.on("stagemousedown", function(evt) {
   if (!evt.relatedTarget) { panel.toggleOff(); }
});
````
