### ISSUE TITLE
getBounds returns null on Text when text is integer of 0

### ISSUE THREAD

**Issue by scaryuncledevin** [CreateJS/EaselJS#550]
The following code will create a text display, but is unable to return the bounds of it:

    var val = 0;
    var testText = new createjs.Text(val);
    console.log(testText.getBounds());

A simple workaround is to ensure the text value is a string by adding a blank string to the end, like so:
    var testText = new createjs.Text(val+"");

**Comment by gskinner** [comment]
I just pushed a fix for this, based on @noobiept's pull request.
