### ISSUE TITLE
flash cc 2014 export with 0.7.1,does not support 0.8

### ISSUE THREAD

**Issue by happyqu** [CreateJS/EaselJS#552]
flash cc 2014 export with 0.7.1,does not support 0.8

**Comment by lannymcnie** [comment]
Can you be more specific? We specifically tested with 0.8, so it should work.

**Comment by ylazy** [comment]
Me too. In addition, Flash CC Canvas Document contain many bugs, but I can't find where to report.
- Event Listeners can't be removed.
- SpriteSheet bugs
- ...
I've been waiting for Flash CC updating for a long time...

**Comment by ylazy** [comment]
Anyone ever try remove "tick" event in Flash CC Canvas Document?

this.on("tick", count, this);
var value = 0;
function count()
{
	++ value;
	this.tf.text = value; // tf is a textfield created on stage
	this.off("tick", count);
}

**Comment by noobiept** [comment]
You need to save what is returned from .on().

```
var ref = something.on( 'tick', count );

// ...

something.off( 'tick', ref );
```

**Comment by lannymcnie** [comment]
@ylazy Can you be more specific about "spritesheet bugs"? CreateJS does not support the export of spritesheets using a Canvas document. There is EaselJS format options for spritesheet export, but that is  different. Where are you having problems?

Please feel free to log a specific bug with reproduction steps, and sample code.

@noobiept is right about event removal. If you require a scope (3rd param) when using `on()`, then a method closure is generated, which the `on()` method returns. You need to use this reference to remove the listener.

Cheers.

**Comment by lannymcnie** [comment]
Updated previous comment: A method closure is *always* returned, to stay consistent no matter the usage. If you don't specify a scope, then the EventDispatcher instance will be used.

**Comment by gskinner** [comment]
To clarify a couple of things:

One of the important features of `on()` is to provide callback scope, either to a specified scope (third param) or to the event dispatcher. This (and the other features of `on`) requires the creation of a wrapper function, which is returned to facilitate easy removal of the listener using `off()`:

```
var f = this.on("click", doStuff);
this.off("click", f);
```
Alternately, you can look at `event.remove()`, which makes it easy to remove a listener within the context of a callback, even without the original listener.
```
this.on("click", doStuff);
function doStuff(evt) {
   // ... do stuff
   evt.remove();
}
```

With regards to sprite sheets: The sprite sheets exported from Flash Pro CC extend the `SpriteSheet` class using the old `initialize()` model. Flash Pro will either need to update to use the new model, or we will have to grandfather this method (which we did for `MovieClip` and Flash Pro).

Adding this to your code before the exported sprite sheet is initialized *should* fix this problem for now (I haven't tested this):
```
createjs.SpriteSheet.prototype.initialize = createjs.SpriteSheet;
```

Closing this for now. Please reopen if this doesn't address your problems.

**Comment by gskinner** [comment]
Logged the sprite sheet separately as #553

**Comment by ylazy** [comment]
Thank you for quick replies. The answers really help me a lot. The SpriteSheet issue I meant, is how to create SpriteSheet at runtime from MovieClip in Flash CC. This code doesn't work:

createjs.Sprite.prototype.initialize = createjs.Sprite;

var builder = new createjs.SpriteSheetBuilder();
    builder.scale = 1;
    builder.maxWidth = 1024;
    builder.addMovieClip(this.mc); // mc is a MovieClip on Stage
    builder.build();
var spriteSheet = builder.spriteSheet;
var sprite = new createjs.Sprite(spriteSheet);
    sprite.x = sprite.y = 100;
    stage.addChild(sprite);
    sprite.gotoAndPlay(0);
