### ISSUE TITLE
Get bounds of Graphics

### ISSUE THREAD

**Issue by zzm2q** [CreateJS/EaselJS#557]
Hi, are there any way to get bounds of Graphics?
i am using Graphics as base library in my framework, i want dynamically to create a canvas, and the canvas size is determined by the bounds of the instance of Graphics.

**Comment by lannymcnie** [comment]
The short answer is no.

Have a read through the original post about this topic http://blog.createjs.com/width-height-in-easeljs/ and then the update here: http://blog.createjs.com/update-width-height-in-easeljs/

Bounds support was added to most object types (including Containers, which use their children bounds to calculate). Unfortunately, Graphics is much trickier. We are still looking at options, but as of today, there is no automatic support.

**Comment by gskinner** [comment]
You could create a naive solution fairly easily, that would read through the graphics instructions list via `Graphics.getInstructions()`, and calculate maximal values of all significant points. It would give you rough bounds for most shapes, which you could then pad up slightly to accommodate things like stroke width.

Making this completely accurate is a huge challenge (as outlined in the blog posts above), but you might be able to build something that's good enough for your use case. If you do, feel free to share.

**Comment by jcward** [comment]
Hi @gskinner and anyone who visits this page in the future,

I created just such a simplistic solution, as I had need of it. Of course, I didn't implement everything, but enough to be interesting:

https://github.com/jcward/EaselJS-Graphics-bounds

Cheers,
-Jeff

![selection_999 219](https://cloud.githubusercontent.com/assets/2192439/21940783/1aeb8d36-d983-11e6-8e50-33e8349cc85e.png)

**Comment by gskinner** [comment]
Super cool! I'll check it out.
