### ISSUE TITLE
Masks are not working on Chrome Version 40.0.2214.93

### ISSUE THREAD

**Issue by manorius** [CreateJS/EaselJS#560]
I haven't tested the mask property on older versions of Chrome but it doesn't work on the latest release 40.0.2214.93. It works on Safari 8.0.2 though.

**Comment by lannymcnie** [comment]
Can you provide a sample? I am using the same version (Mac OS X) and this demo works fine: http://createjs.com/demos/easeljs/Masks.html

**Comment by manorius** [comment]
Sorry my bad, it works.
It requires a server to work properly on Chrome.

**Comment by lannymcnie** [comment]
Masks themselves do not, but if other operations taint the canvas, then it might fail. Thanks for following up.
