### ISSUE TITLE
should p.clear clean _oldStrokeDash also?

### ISSUE THREAD

**Issue by pchicociv** [CreateJS/EaselJS#562]
After cleaning a graphics that has used dashed strokes, I found that p._updateInstructions is pushing a null instruction because _oldStrokeDash still have some value.
Then, at p.draw, instr[i] has a null value and so exec fails.

**Comment by gskinner** [comment]
Yes. Both `_oldStrokeDash` and `_oldStrokeStyle` should be set to null in `clear()`. I have updated locally and will push after some testing.

**Comment by gskinner** [comment]
Pushed the fix for this. Please test.
8625a21ae171803e766a1d9c036358553438ebb9

**Comment by pchicociv** [comment]
Tested and working fine.
Thnks!
