### ISSUE TITLE
Run-time error when using BitmapFill with an image that isn't loaded

### ISSUE THREAD

**Issue by lannymcnie** [CreateJS/EaselJS#564]
When using a bitmap fill, if the bitmap is not yet loaded, EaselJS throws an error. All versions show the fill as black, but only EaselJS 0.8.0 throws an error. 

Additional info: If the image isn’t loaded before the draw, the draw remains black, even if you update the stage after the image has loaded. This is possibly due to browsers caching the pattern.

http://screens.gskinner.com/Screen%20Shot%202015-02-05%20at%209.44.59%20AM.png
http://jsfiddle.net/lannymcnie/ogy1qmxn/

**Comment by lannymcnie** [comment]
Similarly, a null image will throw a different error.

**Comment by gskinner** [comment]
Just pushed a fix for this. Please verify.

**Comment by lannymcnie** [comment]
Verified :)
