### ISSUE TITLE
EaselJS 0.8 lineTo no longer works 

### ISSUE THREAD

**Issue by robincafolla** [CreateJS/EaselJS#565]
createjs.Graphics.lineTo no longer functions but silently fails.

test case:
http://jsfiddle.net/5Bs5k/55/

**Comment by brean** [comment]
you have to call beginStroke and setStrokeStyle before moveTo and/or lineTo

**Comment by robincafolla** [comment]
Ah, cheers. So the api has changed? Perhaps an update in the docs?

You can see the same example working here with an older version of CreateJs http://jsfiddle.net/5Bs5k/56/

**Comment by MannyC** [comment]
See #520

**Comment by gskinner** [comment]
Closing this in favour of #520.
