### ISSUE TITLE
document usage of rgba color in shadow filter

### ISSUE THREAD

**Issue by griii2** [CreateJS/EaselJS#568]
I've just realised you can use rgba as a string in the shadow filter color - and probably everywhere in EaselJS. It could be beneficial for others to explicitly mention in the documentation on every place where you are expected to set color.

**Comment by gskinner** [comment]
In general we try to mention that you can use any valid CSS color value. If you see places that's not the case, feel free to correct and issue a pull request (or list them here and we can fix on our end).

**Comment by gskinner** [comment]
I've updated it locally for the Shadow class.

**Comment by gskinner** [comment]
Closing. But feel free to list any other instances you encounter here.
