### ISSUE TITLE
Specify frames for each animation instead of entire sprite sheet

### ISSUE THREAD

**Issue by Pajamaman** [CreateJS/EaselJS#570]
It would be nice if instead of specifying the indices of the frames I want to use in an animation I could specify the frames directly. i.e., instead of this:

    var spriteSheet = new createjs.SpriteSheet({
        images: [loader.getResult(animation.image)],
        frames: [
            [546,145,36,45,15,40],
            [112,344,37,44,16,39],
            [428,373,36,44,16,39],
            [464,373,37,44,16,39]
        ],
        animations: {
            idle: {
                frames: [0, 1, 2, 3, 2, 1],
                speed: 0.1
            }
        }
    });

I'd like to be able to do this:

    var spriteSheet = new createjs.SpriteSheet({
        images: [loader.getResult(animation.image)],
        animations: {
            idle: {
                frames: [
                    [546,145,36,45,15,40],
                    [112,344,37,44,16,39],
                    [428,373,36,44,16,39],
                    [464,373,37,44,16,39],
                    [428,373,36,44,16,39],
                    [112,344,37,44,16,39]
                ],
                speed: 0.1
            }
        }
    });

The reason is that I'm working with a sprite sheet with several hundred frames crammed into as tiny a space as possible, and randomly ordered to boot. For example, this image was lifted from [Flare](https://github.com/clintbellanger/flare-engine):

![image](https://cloud.githubusercontent.com/assets/1323271/6343260/9bf6b500-bba2-11e4-8986-6ab6765582a4.png)

Because of the random ordering, it can be difficult to determine indices for the individual frames.

**Comment by gskinner** [comment]
Point taken, but the idea is that the data is generated by a tool, not by hand. We're not going to break compatibility with the existing format, and I'd prefer to avoid complicating it any more than it already is. Also, we want to be able to support features like frame reuse.

I'm closing this for now, but feel free to reopen it if you feel like there are compelling reasons for this that I haven't considered.

**Comment by Pajamaman** [comment]
I think it could be useful in other cases as well. For now I've managed to work around it:

https://github.com/Pajamaman/flare-ini-converter
