### ISSUE TITLE
Rectangle trouble

### ISSUE THREAD

**Issue by elderNosferatu** [CreateJS/EaselJS#572]
Rectangle.js
--------------------

```javascript
p.pad = function(top, left, bottom, right) {
	this.x -= top; // should be this.x -= left
	this.y -= left; // should be this.y -= top
	...
};
```

**Comment by lannymcnie** [comment]
Feel free to submit a pull request.

**Comment by gskinner** [comment]
I just pushed a fix for this: https://github.com/CreateJS/EaselJS/commit/94bc7f13af8c8f6b37b776a7532553d23918365f
