### ISSUE TITLE
Changes in Matrix2D 0.8.0

### ISSUE THREAD

**Issue by yar3333** [CreateJS/EaselJS#574]
Please, explain: why Matrix's rotate/scale/translate methods logic was changed in 0.8.0? May be these methods must work the same as in Flash's Matrix? Now its work differently:
```
// flash
var m = new flash.geom.Matrix();
m.translate(5,5);
m.scale(2,2);
trace(m); // a=2, b=0, c=0, d=2, tx=10, ty=10
```

```
// js
var m = new createjs.Matrix2D();
m.translate(5,5);
m.scale(2,2);
console.log(m); // a=2, b=0, c=0, d=2, tx=5, ty=5
```

For me, it looks strange...

**Comment by gskinner** [comment]
Please see: https://github.com/CreateJS/EaselJS/issues/539
