### ISSUE TITLE
Consider adding `currentFrame` getter/setter on MovieClip/Sprite

### ISSUE THREAD

**Issue by lannymcnie** [CreateJS/EaselJS#575]
This would be an easy way to get/set the current frame. Likely, this would only gotoAndStop when using the setter.

**Comment by gskinner** [comment]
Our general rule is to avoid getter/setters for more complex tasks. Calling gotoAndStop() runs a bunch of code to normalize the frame, may modify the original input, and may generate events.

The more important issue here, is that our docs have lost their readonly indicators.

**Comment by lannymcnie** [comment]
Fixed the @readonly indicators. Note that there is a critical change in the YUIDocs source, which is not git-managed. An updated builder.js is supplied in the `build/updates` folder, with instructions on where to put it to properly build docs.

Here is a link to the YUIDoc request to support @readonly on properties. https://github.com/yui/yuidoc/issues/123
