### ISSUE TITLE
adding an event with "on", and then removing it with "removeEventListener" does not work.

### ISSUE THREAD

**Issue by DanielJPetersen** [CreateJS/EaselJS#576]
It appears you can't add an event with "on", and then remove that event with "removeEventListener".  

Adding an event with "addEventListener" seems to work fine with "removeEventListener", though.

Interestingly, you can mix "addEventListener" and "off" just fine.  I tested this on both a stage and a container.  Here's the code on just the stage

http://jsfiddle.net/xajcaasf/

**Comment by gskinner** [comment]
Please see the docs: http://www.createjs.com/Docs/EaselJS/classes/EventDispatcher.html#method_on

> This method works by creating an anonymous wrapper function and subscribing it with addEventListener. The created anonymous function is returned for use with .removeEventListener (or .off).

The docs also include an example of how to use this.
