### ISSUE TITLE
Ticker Documentation

### ISSUE THREAD

**Issue by webskin** [CreateJS/EaselJS#577]
Hello,

At https://github.com/CreateJS/EaselJS/blob/master/src/createjs/utils/Ticker.js#L181

Minor doc change to do

When the ticker is paused, all listeners will still receive a tick event, but the <code>paused</code> property of the event will be ~~false~~ true.

**Comment by lannymcnie** [comment]
This is working as intended. Cheers.

**Comment by webskin** [comment]
if the ticker is paused then 
```Ticker.paused = true```

If an event is dispatched when the ticker is paused, it must have the property ```paused``` with the same value : ```true``` and not ```false``` as the documentation says.

Have I misunderstood something ?

**Comment by lannymcnie** [comment]
Ah, I see. We can check it out. Sorry!

**Comment by lannymcnie** [comment]
Thanks! I pushed an updated Ticker class to GitHub (EaselJS and TweenJS) with this fix, and a few other minor doc updates.
