### ISSUE TITLE
If the CreateJS library supports the JSON output formats of Texture Packer 

### ISSUE THREAD

**Issue by Rachelin** [CreateJS/EaselJS#580]
Hi, I am the new one in using CreateJS . Now I was blocked in how to loading an image which is made by Texture Packer, and i got the JSON file. 
Here is the json file :

{"frames": [

{
	"filename": "aim_dot",
	"frame": {"x":118,"y":4,"w":76,"h":76},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":76,"h":76},
	"sourceSize": {"w":76,"h":76}
},
{
	"filename": "boundary",
	"frame": {"x":4,"y":385,"w":250,"h":100},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":250,"h":100},
	"sourceSize": {"w":250,"h":100}
}]

}

**Comment by gskinner** [comment]
Please post questions on StackOverflow. GitHub Issues is for reproducible bugs and feature requests. Thank you!

**Comment by Rachelin** [comment]
Thank you so much.

**Comment by MannyC** [comment]
You need to tell TexturePacker to export for EaselJS/CreateJS (Under "Data Format").  The JSON you've posted is not in the correct format for EaselJS.
