### ISSUE TITLE
BitmapText clone error

### ISSUE THREAD

**Issue by honzatjb** [CreateJS/EaselJS#584]
Hello,
I recently ran into problem with cloning BitmapText object. Error specifically appears in _cloneProps when it tries to call super method DisplayObject__cloneProps where it says DisplayObject__cloneProps is undefined.

I think the problem is that BitmapText extends Container and not DisplayObject so DisplayObject super methods are not visible in BitmapText object.

I fixed the error by changing DisplayObject__cloneProps to Container__cloneProps so _cloneProps for BitmapText now looks like this:

```javascript
/**
 * @method _cloneProps
 * @param {BitmapText} o
 * @return {BitmapText} o
 * @protected
 **/
p._cloneProps = function(o) {
	this.Container__cloneProps(o);
	o.lineHeight = this.lineHeight;
	o.letterSpacing = this.letterSpacing;
	o.spaceWidth = this.spaceWidth;
	return o;
};
```

Thanks for reply,
Honza

**Comment by lannymcnie** [comment]
Feel free to post pull requests if you can for future fixes - they make integration of fixes like these much easier. Thanks for finding the issue!
