### ISSUE TITLE
SpriteSheet next animation not functioning

### ISSUE THREAD

**Issue by timbowerbank** [CreateJS/EaselJS#588]
Hi,

Having trouble with implementing a next animation, I have tested this mulitple times and this was functioning OK with older versions of easeljs so logging this as an issue.
 
Animation created in Flash CS6 and SpriteSheet created through Zoe.
The json clearly specifies what the next animation should be but the animation just loops.
Here's a link to the animation:
http://www.roythezebra.com/abc_demo/html5/example16/
It can be tested using the Button which should step it through each animation type.

Many thanks

Tim

**Comment by MannyC** [comment]
None of the animations you're trying to play actually exist (even "lookup", it's "lookUp" in the json)

**Comment by timbowerbank** [comment]
Hi Manny, apologies, I have corrected that now. The reason I pulled out the animation was that I can't get it to work in a seperate game. I can see the animation is working fine when it isn't embedded. 
Thanks for looking again, and sorry for wasting your time. Thanks for all your hard work with createjs.
Tim
