### ISSUE TITLE
Rotation and Registration Point

### ISSUE THREAD

**Issue by Ajit-Dongre** [CreateJS/EaselJS#59]
Hi,

I want to rotate a particular shape like rectangle, ellipse etc.  around its center.  To achieve this,  I had set regX and regY to center of that shape. But it is shifting the shape.  In detail,  I did following things.

Suppose I am drawing ellipse as below :

newShape.graphics.drawEllipse(start.x, start.y,  width, height);

newShape.regX = start.x + width / 2;
newShape.regY = start.y + height / 2;

then I am rotating this shape with button.  Button Click event has following code

newShape = rotateCnt;
rotateCnt += 10;

This is actually shifting the shape and rotating it about (0, 0).
If I would not set regX & regY then shape will not be shifted but rotated about (0, 0)

**Comment by tromgy** [comment]
I ran into the same issue. Here's a simple example of regX/Y in action. You can see how it affects rotation.

http://jsfiddle.net/ZnWuP/

When offsetting regX, regY by 50, the center of rotation does move by 50 units horizontally and vertically relative to the shape origin, but the shape itself gets translated by the same amount in the opposite direction!

I had spent some time trying to figure out what was wrong with rotations in easel and I think the code in easelJS regarding rotations about an arbitrary point (regX, regY are not 0s) is incorrect.

I have a fix but at this point don't know how to do a pull request -- do I need to create my own branch?

**Comment by wdamien** [comment]
@tromgy Your best off checking the github documentation for pull requests:  https://help.github.com/articles/using-pull-requests/

**Comment by lannymcnie** [comment]
I responded to your question on Google Groups.

I am fairly certain the behaviour you are describing is expected. The registration point is where the object draws from. Here is a quick fiddle showing that in action. The circle is drawn from the top left. After 2 seconds, it will change its registration point to be centered on the circle. This counter-translates it.
http://jsfiddle.net/lannymcnie/vaa19njf/

Registration points are not just "transformation" points, and they affect where the content appears on the stage.

Regarding your other question about matrix math, here is what I posted to Google Groups: "There are two ways to approach matrixes: A row-first approach, and a column-first approach. EaselJS takes the column-first approach which is inline with the W3C spec, as well as matching what Canvas APIs use."

Hope that helps.

**Comment by tromgy** [comment]
Why do we need regX,Y to affect translation? We already have X,Y properties for that.

From the documentation on EaselJS it is implied that registration point is the relative offset for the rotation point.

The way it works now for every rotation one has to compensate with additional translation.

In the original JSFiddle example (in the abovementioned google gropu) , to make it rotate around its center while maintaining position one needs to do:

    square.regX = square.regY = 50;
    square.x += square.regX;
    square.y += square.regY;

This doesn't make sense to me.

**Comment by yar3333** [comment]
@tromgy: Properties regX/Y are specify predefined center of the object, local coordinate system origin. So, I think, changing regX/Y after time is not assumed by design.

**Comment by gskinner** [comment]
@tromgy This just represents two different approaches to a similar problem. You are referring to a rotation or pivot point, which is not directly supported in EaselJS. Instead we support a registration (or origin) point. This redefines the 0,0 position of an instance, as opposed to setting a point strictly for rotation. A side effect of this, of course, is that the content of the instance is translated by the specified amount.

Both approaches have advantages, but registration points tend to be more understandable to the average user as the relationship between position and rotation/skew is much more straightforward.

For more advanced users, it is fairly simple to get the effects of a rotation point by using the Matrix2D object directly, and applying it to an instance using the `transformMatrix` property.

Regardless of personal opinion on this matter (I can see the usefulness of both approaches), this functionality is definitely not changing, as it would break a ton of existing content, and confuse existing users.

Perhaps we could evaluate adding a `rotateAt(rotation, x, y)` or similar method to `Matrix2D` to expose this capability a bit more obviously? I'd be interested to hear your thoughts.
