### ISSUE TITLE
mouse event problems from 0.7.1 to 0.8.0

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#590]
In 0.7.1 I had the stage move on this.mouseX and this.mouseY so the player could look around the area with the mouse. Now both those values are always 0.

I added "enableDOMevents(true)" and now it looks.... but only when I click the mouse. What?

I tried putting the mouse look function into a "stagemouselook" event and changed this.mouseX and this.mouseY to evt.stageX and evt.stageY, but the event NEVER FIRES. I use this.on("stagemousemove", mouseLook); and nothing happens.

Please help?

**Comment by krazbobeans** [comment]
I've discovered a little more.

I have two Stage objects (map and hud) at the same time. hud is set to "autoclear=false" so I can see map. There was no conflict before with mouseX,mouseY in 0.7.1, but now it seems like they dont want to work together.

As soon as I disable the hud stage, mouseX,mouseY works. What can I do here?

**Comment by krazbobeans** [comment]
I solved it.

hud had its Stage.nextStage set to map. By reversing this and making map set its Stage.nextStage to hud instead it worked.

I have no idea why the order mattered but there you go.

**Comment by lannymcnie** [comment]
Thanks for posting your solution!
