### ISSUE TITLE
7.1 to 8.0 - Inherited stage object no longer connects to canvas

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#591]
I use prototyping (var p = Map.prototype = new Stage()) type stuff to inherit from Stage. Up until 0.8.0 I was able to pass the canvas through the initiation call:
function Map(cvs) 
{
	this.initialize(cvs);
}
and then stage_initialize(cvs)...

Now for some reason it does not pass "cvs" along and connect to the canvas. To fix this I had to go into my own prototype initialzer for my inherited object and use the line:
		this.canvas = document.getElementById(cvs);

I don't mind doing that, but it's a shame I had to waste hours figuring that out when it should have worked like before. Can you guys fix this?

**Comment by gskinner** [comment]
Please make sure to review the VERSIONS file when updating to a new version. The inheritance model changed in 0.8.0. http://blog.createjs.com/new-createjs-class-model/
