### ISSUE TITLE
Adding "tick" event is adding a function it cannot remove

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#592]
I'm using the line
		this.on('tick', this.whileClicking, null, false);
To have a function continuously fire while holding the mouse button. Then I use the line
		this.off('tick', this.whileClicking, null, false);
To remove it when pressup is called to stop the continuous function call.

The problem is this.whileClicking still runs after "off" function is called. I went step by step into easeljs and see that it doesnt see a match when it compares in the "removeEventListener" function. It gets to that function in listeners["tick"] but when it compares it doesn't see it as the same, therefore it never gets removed.

Any suggestions how to solve this? Will update if I think of it first.

Thanks!

**Comment by gskinner** [comment]
http://www.createjs.com/Docs/EaselJS/classes/EventDispatcher.html#method_on

The `on` creates a wrapper function which must be passed to `off`.
````
var listener = foo.on("bar", onBar);
//...
foo.off("bar", listener);
````
Alternately, check out `Event.remove()`

**Comment by krazbobeans** [comment]
Great! Thank you for your help.

**Comment by gskinner** [comment]
PS. I'm adding a bold note in the docs for both `on` and `off` to call attention to this, since it gets asked a lot.

**Comment by Abhishekbharti** [comment]
Hey i am having issue while dispatching event ,  Chrome give this error: Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is null.

This is the code i'm dispatching event after the game end on line : 164

(function(window) {

window.game = window.game || {};

function Game() {
	this.Container_constructor();
	this.setup();
}

var p = createjs.extend(Game, createjs.Container);

p.sprites;
p.caught = false;
p.spritePool;
p.terrain;
p.terrainContainers;
p.gameBG;
p.fish;
p.speed;
p.cuttingNet = false;
p.score;
p.scoreBitmap;
p.scoreContainer;
p.keyDown;

p.setup = function() {
	this.gameBG = this.addChild(new lib.GameBG());
	this.gameBG.x = 160;
	this.gameBG.y = 240;
	
	this.terrain = [
		{speed: 0.2, minX: 480, maxX: 960, minY: 40, maxY: 250, bounce: false, x: -240, labels: ["FishSwarm", "JellySwarm"]},
		{speed: 0.5, minX: 320-2, maxX: 320-2, minY: 345,maxY: 345, bounce: true, x: -320, labels: ["WaterPlant1", "WaterPlant2", "WaterPlant3","WaterPlant4"]},
		{speed: 2, minX: 320-2, maxX: 320-2, minY: 420,maxY: 420, bounce: false, x: -320, labels: ["SandLand1", "SandLand2", "SandLand3"]}, 
		{speed: 2, minX: 40, maxX: 4800, minY: 420,maxY: 480, bounce: false,x: -160, labels: ["SandDots1", "SandDots2", "SandDots3"]}, 
		{speed: 2, minX: 160, maxX: 640, minY: 395,maxY: 460, bounce: true,x: -320, labels: ["CactusG", "CactusB", "CactusY", "OrangePlant1", "OrangePlant2", "GreenPlant", "Lotus"]}, 
		{speed: 1.5, minX:96, maxX:480, minY:280, maxY:280, bounce:false, type:1, x:500, labels: ["NetClose"]}
	];
	
	this.init();
};

p.init = function() {
	this.sprites = [];
	this.spritePool = [];
	this.terrainContainers = [];
	this.score = 0;
	this.keyDown = false;
	
	for(var i = 0; i < this.terrain.length; i++) {
		var o = this.addChild(new createjs.Container());
		this.terrainContainers[i] = o;
		this.terrain[i].x = this.terrain[i].x || 0
	}
	
	this.scoreContainer = this.addChild(new createjs.Container());
	this.scoreContainer.set({x: 160, y: 120});
	this.scoreBitmap = new createjs.BitmapText(String(this.score), spritesheet);
	this.scoreContainer.addChild(this.scoreBitmap);
	
	this.fish = this.getSprite("Swimming", 4, false, null, 0);
	this.fish.scaleX = 0.3;
	this.fish.scaleY = 0.3;
	this.fish.set({x: -this.fish.getBounds().width, y: 280});
	createjs.Tween.get(this.fish).wait(250).to({x: 90}, 3000, createjs.Ease.get(1));
	this.addChild(this.fish);

	this.speed = 2;

	// pre-generate the terrain here.
	this.updateTerrain();

	stage.addEventListener('stagemousedown', this.stageListener = this.handleMouseDown.bind(this));
};

p.handleMouseDown = function(evt) {
	if(!this.keyDown) {
		this.keyDown = true;
	}
};

p.updateTerrain = function(t) {
	var i;
	// move existing terrain elements: 
	var speed = this.speed * (t||1);
	for(i=this.sprites.length-1; i>=0; i--) {
	var sprite = this.sprites[i];
	if(sprite.type == 0) { continue; }
		sprite.x -= speed * sprite.speed;
	var bounds = sprite.getTransformedBounds();
	if(sprite.x < bounds.x - bounds.width) { this.reclaimSprite(sprite, i); }
	}
	
	// generate new terrain: 
	var speed = this.speed * (t||1);
	for(i = 0; i < this.terrain.length; i++) {
		var o = this.terrain[i];
		o.x -= speed * o.speed;
		if(!o.labels || o.x > 0) { continue; }
		var label = o.labels[Math.random() * o.labels.length|0];
		var sprite = this.getSprite(label, o.speed, o.bounce, i, o.type);
		sprite.y = o.minY + Math.random() * (o.maxY-o.minY) | 0;
		sprite.x = canvas.width-sprite.getBounds().x + o.x;
		var range = (o.maxX - o.minX) * (o.type ? this.speed/12 : 1);
		o.x += (o.minX + Math.random() * range);
	}
};

p.getSprite = function(label, speed, bounce, containerIndex, type) {
	// Get sprite 
	var sprite = new createjs.Sprite(spritesheet);
	sprite.set({speed: speed, type: type});
	sprite.gotoAndPlay(label);
	var bounce = sprite.bounce;
	if (bounce) { createjs.Tween.get(sprite, {loop:true}).to({scaleY:0.9}, 400).to({scaleY:1}, 400); }
	if(containerIndex != null) {this.terrainContainers[containerIndex].addChild(sprite);}
	this.sprites.push(sprite);
	return sprite;
}

p.reclaimSprite = function(sprite, index) {
	// deactivate the sprite, and returns it to the object pool for future use
	createjs.Tween.removeTweens(sprite);
	sprite.stop();
	sprite.scaleY = 1;
	if(sprite.parent) { sprite.parent.removeChild(sprite); }
	if(index == null) { index = this.sprites.indexOf(sprite); }
	if(index != -1) { this.sprites.splice(index, 1); }
	this.spritePool.push(sprite); 
}

p.check = function() {
	for(var i = 0; i < this.sprites.length; i++) {
		var sprite = this.sprites[i];
		if(sprite.type) {
			if(sprite.x < 145 && !(sprite.x < 94) && this.keyDown && this.fish.currentAnimation == 'Swimming') {

				this.fish.gotoAndPlay("CutNet");
				sprite.gotoAndPlay("NetOpen");
				this.score++;
				this.keyDown = false;
			}else if(sprite.x > 145 && this.keyDown && this.fish.currentAnimation == 'Swimming') {
				this.fish.gotoAndPlay("MouthOpen");
			}else if(sprite.x < 94 && sprite.currentAnimation != 'NetOpen') {
				this.die();
			}
		}
	}
	if(this.keyDown) {
		this.keyDown = false;
	}
}; 

p.die = function() {
	stage.removeEventListener('stagemousedown', this.stageListener);
	this.fish.gotoAndPlay('Caught');
	//createjs.Sound.play(game.assets.FishCaught, createjs.Sound.INTERRUPT_NONE, 0, 0, 0, 1, 0);
	this.speed = 0;
	this.caught = true;	
	window.setTimeout(this.endGame, 500);
};

p.endGame = function() {
	this.dispatchEvent(game.GameStateEvents.GAME_OVER);
};

p.updateScore = function() {
	// store the highScore and yourScore to the localStorage
	localStorage['maxScore'] = this.score || 0;
	var maxScore = Math.max(localStorage['maxScore'], this.score);
	localStorage['maxScore'] = maxScore;
	this.scoreContainer.removeAllChildren();
	this.scoreBitmap = new createjs.BitmapText(String(this.score), spritesheet);
	this.scoreContainer.addChild(this.scoreBitmap);
};

p.run = function(evt) {
	var fps = spritesheet.framerate;
	var t = evt.delta / (1000/fps);
	this.updateTerrain(t);
	this.check();
	this.updateScore();
	if(!this.caught) {
		this.speed = Math.min(20, this.speed+0.005*t);
	}
};

window.game.Game = createjs.promote(Game, "Container");

}(window));
