### ISSUE TITLE
v0.8.0 does not have SpriteStage included despite what docs say.

### ISSUE THREAD

**Issue by hayesmaker** [CreateJS/EaselJS#593]
Hi there,

i've used bower to get the v0.8.0 of easelJS.. and tried to use SpriteStage, but it doesn't seem to be included in our package... is this a problem? why are there different versions of the same version?

**Comment by lannymcnie** [comment]
SpriteStage and SpriteContainer are part of the Version 0.8.0 release on GitHub, but are not included in the minified version, since it is not an often-used feature. You have to include them manually from GitHub.

Cheers.

**Comment by hayesmaker** [comment]
I'm not using the minified version, I'm using the unminified version 0.8.0 from a bower install

**Comment by lannymcnie** [comment]
The unminified (combined) version still represents the "core" library (it is the same as the minified lib, except the source is readable, and it contains comments). The SpriteStage/Container is not part of the core library, and not included.

It might make sense to modify the bower install to include the 2 WebGL classes. We will evaluate.

**Comment by hayesmaker** [comment]
Sure, thanks.. in the meantime we can get them like this:
"EaselJS": "CreateJS/EaselJS#master",
"SpriteStage": "https://raw.githubusercontent.com/CreateJS/EaselJS/master/src/easeljs/display/SpriteStage.js",
"SpriteContainer": "https://raw.githubusercontent.com/CreateJS/EaselJS/master/src/easeljs/display/SpriteContainer.js"

The docs should probably explain the core library concept, and explain they aren't core files

**Comment by lannymcnie** [comment]
I guess it could be more obvious. At the bottom of the main description it says "Note: SpriteStage is not included in the minified version of EaselJS."

We are considering adding an "easeljs-webgl" min file to the /lib folder, which contains the tagged version of the 2 classes.

Cheers.

**Comment by lannymcnie** [comment]
There is a webgl minified version now, which should come down with a bower install. We are considering including this file on the next CDN release.
