### ISSUE TITLE
unminified v0.8.0 does not contain SpriteStage

### ISSUE THREAD

**Issue by hayesmaker** [CreateJS/EaselJS#594]
Well, as my previous question was closed as a non-issue because the minified version does not include SpriteStage, I'd like to raise this as an issue with the source code, because I'm using the unminified version and it does not include SpriteStage and the related classes.

**Comment by gskinner** [comment]
The combined version does not include the SpriteStage either. It includes the same classes as the minified library. The WebGL features are not considered "core" for the 0.8.0 release, but may be rolled into the minified version in the next major release.

**Comment by hayesmaker** [comment]
That should probably be made clearer in the docs.

If anyone else wants these with their bower installs, you can add these to your bower.json.

    "EaselJS": "CreateJS/EaselJS#master",
    "SpriteStage": "https://raw.githubusercontent.com/CreateJS/EaselJS/master/src/easeljs/display/SpriteStage.js",
    "SpriteContainer": "https://raw.githubusercontent.com/CreateJS/EaselJS/master/src/easeljs/display/SpriteContainer.js"
