### ISSUE TITLE
Docs: container::removeAllChildren

### ISSUE THREAD

**Issue by robincafolla** [CreateJS/EaselJS#596]
http://www.createjs.com/Docs/EaselJS/classes/Container.html#method_removeAllChildren

```
container.removeAlLChildren();
```

should be 

```
container.removeAllChildren();
```
obviously minor but a copy-paste will break and lead to some unnecessary debugging (as it did for me).

**Comment by gskinner** [comment]
Good catch. I just pushed a fix for this.
