### ISSUE TITLE
CreateJS exported.js vs library.item order

### ISSUE THREAD

**Issue by SmartArtsStudio** [CreateJS/EaselJS#597]
Hi,
Forgive me in advance if this is not the best location, I couldn't figure out where this question really fits:

The createjs exporter obviously appends indexes to any 'linkage' names that are the same.
The exporter iterates the library in a different order to the IDE library display. Initially it looked to simply be the reverse order of the library display, but nest some library folders... and the indexing order becomes unclear.

I need to use linkage names that ARE the SAME, as I am using them for their original AS3 purpose: extending super classes. Statically injecting the linkage named subclass (multiple sub-classed inheritance between cjs.Container classes and the final linkage class) into the createjs output.js. You guys are going to LOVE what I have gotten substantially up and running (property inspector box2d for flash canvas projects) Would you like a new wave of designer/game devs to createjs? Hopefully its popular, and that's my thanks for all your team's work open-sourcing createjs.

JS instance prototype manipulation after instantiation is neither performant nor browser supported, leaving static creatjs output.js manipulation. Which thanks to jsfl + onPublish event... static code manipulation works beautifully. But of course it results in same-name-indexed symbols that makes it harder to tell one from another. Prepending the lib.symbols with commented library.item details WAS working nicely. But as a library folder structure grows more advanced, trying to predict the symbol indexing order with a linkage name instance counter while iterating the DOM.library.items array, falls apart and seems to require some inside knowledge to how the nested folder name-indexing proceeds through the folder strucuture. 

1) Does the createjs exporter.jsfl use an Array as it appends index numbers? Can you shed some light on the order in which it works through the library folder structure?  (Is it controlled, hoping it doesn't turn out to be pushed object properties.)

2) If it is object properties, FEATURE REQUEST: any chance it can be reimplemented with a more predictable structure, ideally in the same order as the library.items array in a future release?

3) Ideally can you point me in the direction of a readable createjs exporter.jsfl for any other weirdness I may come across? (The jsfl API weirdness 'surprises' alone have consumed more way time than I will ever admit, any help on the createjs side would be hugely appreciated!) 

[edit] 4) I've realised if I could read the exporter.jsfl I might be able to figure out a way to hook into it to add to the the output.js an additional 'physics' symbol instance property (the same as alpha, tint, visible, blending etc currently work except I add an object.) Currently if when using the same symbol, just with different physics properties it requires duplicating all the symbol code for each variation on desired physics configuration. To avoid unnecessarily bloated output.js I am still yet to figure how to deal with deleting out all the identical symbols and adding the 'physics' instance property after each of their instantiations. (Which already works) So you can hopefully understand why I really hoping that exporter.jsfl isn't suppose to be a secret. [edit]

I am pretty sure I once found the createjs exporter.jsfl somewhere in the Flash folders but it was all-wing-dings... was it obfuscated proprietorially or is it something to do with the fact I am running windows and that file was written on a mac. Because the Convert AS3 to HTML.jsfl and many others are totally fine. 

Any other thoughts on alternatives to control which index numbers match which symbols accurately more than welcome... 

Currently: I search the output.js for 'lib.symbol_6' add comments and re-super class this symbol based on what my own: items[i].linkageClassName+'_6' count anticipated it being... but this only works to a single folder depth. (re-super classing is always accurate because it matches the the indexed symbol name, its just accessing the correct library.item details in the correct order that is the problem)

I tried linkage name = 'symbol/superClass' Hopeing NOT to have to change the symbol name at all, while still providing the required superClass reference, but the exporter seems to elegantly strip special characters from the linkage. Adding linkage name = symbolSuperClass is a LAST resort the actual SuperClass will be out of sight, highly error prone, hard bughunt => not user friendly/readable => not in-line with createjs standards, which is one of my goals)

I even tried turning on (in the features.xml): (** replace xml tags)

** Feature name="ScriptLinkage" supported="true" ** 
                ** Property name ="Definition" supported="true" /**
**/ Feature **

Which unblocks 'canvas project' access to symbol properties "export for actionscript" 

Thinking I could simply jsfl the Class and BaseClass values. But because the symbol properties inspector still integrity checks that the BaseClass extends Sprite/MovieClip. It wont accept another value...
Unless you can tell me what features.xml property unblocks access  to PublishSettings > Spanner > SourcePath tabs. I have been unsuccessful finding it. I expect proxy AS3 MovieClip extending classes, with identical names as my JS classes, placed in the source path would pass inspector integrity check. Class & BaseClass should become jsfl retrievable, couldn't be a tidier nor more intuitively compatible solution for as3ers

It is not an 'extension-breaker' obviously,  but I would like to produce a high quality extension. As it alters the createjs output.js a goal is to respect the same standard of user friendliness, readability and documentation createjs already sets. Both in the Flash IDE (designer and coder friendly) extension, and an enhanced Box2D wrapping javascript library.

Sorry a little long, but you can see I have put a lot of effort into this myself, hopefully you can recognize any thoughts, resources, contacts or pointers in the right direction you can offer on this will be well worthwhile. And greatly appreciated.

Happy Easter 
Daniel

**Comment by SmartArtsStudio** [comment]
It seems the referenced feature.xml was stripped:
Feature name="ScriptLinkage" supported="true"
            Property name ="Definition" supported="true"/
/Feature
Which unblocks 'canvas project' access to symbol properties "export for actionscript"

**Comment by gskinner** [comment]
Interesting question. To boil this all down: you are building an extension that generates Box2D metadata for Symbols in the library, but you need some way to associate that data with the symbols in the exported JS file so you can apply post processing using that metadata. Is that correct?

The one part I'm not totally following is why you need to have symbols with identical names. If you could clarify that, I'd be happy to give some thought to this.

I'm going to close this, since it's not a library issue, but we can keep using the closed issue as a place to communicate.

**Comment by SmartArtsStudio** [comment]
1)  RE: “symbols with identical name” clarification…

I am using ‘symbol’ ==  (Library.items[i].name) == ‘Name’ in the IDE library …(ctrl)F8 to create.
and ‘linkage’ == (Library.items[i].linkageClassName) == dble-click ‘Linkage’ in the IDE library to add linkage class.

It is not actually the symbols that I need or want to have identical names... this just happens as result of how the exporter.jsfl currently handles the use of the symbol’s 'linkage' values when faced with identical 'linkage' class names. Perhaps this is an unintended side-effect? because I was actually surprised the exporter even took notice of ‘linkage’ property. Even checked my code to make sure I wasn’t inadvertently doing it. I am not yet familiar with the toolkit's intended use for setting the ‘linkage’ value, and can only think of sub-classing like I am attempting, I have possibly just found a complex way to do something which is already simple? …but what currently happens is… 

Say I have three library symbols name Moe, Larry and Curly and I want them all to act as B2Body at runtime, I assign each of their ‘linkage’ names all the same name 'Body'. But because all three ‘linkage’ names are identical, the exporter handles the ambiguity by actually renaming the ‘symbol’ names in the output.js. It takes what (without linkage names assigned) would have been output symbol names: lib.Moe, lib.Larry and lib.Curly ...and replaces them with... lib.Body, lib.Body_1, lib.Body_2.  The IDE library symbol names are then no longer referenced in the output.js at all. I though no big deal I’ll just prepend the original commented symbol names lib.Moe, lib.Larry and lib.Curly above their new lib.Body, lib.Body_1, lib.Body_2  IF I could track them in a predictable way. 

1)  RE: “meta-data” clarification…

In essence meta-data yes, but added post processing is not necessary. Unless I am trying to eliminate the duplicated symbol code my current implementation produces just to define different physics material (friction, restitution, density, static, kinematic, dynamic…) for the exact same symbol. I am pretty sure we are on the same page, but just for accuracy I will explain my implementation…

What I do is add the ‘meta-data’ in the form of a javascript object  to the symbols script Layer 0, Frame 0 of a symbols timeline. Which the exporter of coarse “exports” via a this.frame_0 symbol property, already associated with the symbol prior to post processing. I only currently use Post processing to re-super class symbol declarations based on a symbols ‘linkage’ name. The ‘meta-data’ is already a part of the symbols timeline. My classes (I believe) need to be injected between Movie clip class and the symbol contents because I am adding (amongst a lot of stuff) ‘added’/’removed’ from stage management to box2dified symbols for runtime. 

Once 'added' ...(each class does a bunch of checks and delays till everything depended on is actually rendered)... then when time is appropriate each re-super classed entity calls its this.frame_0() which returns their physics instance object, the last dependency they need to then create the box2d side of themselves. Post processing is only re-super classing, and adding library symbol details due to lost symbol names… but looking towards mobile I will have to address the unnecessary symbol duplication code my method produces, because…

To create the same symbol with different physics properties, my extension currently simply duplicates and renames the symbol in the IDE library and adds the new ‘variation’ physics object to the duplicated symbols timeline… which of course in the ouput.js duplicates exactly the same graphics code. Just to gain a different ‘this.frame_0()’ that returns the slightly different physics object. Which to reduce bloated output.js file sizes for mobile I need to somehow delete duplicate symbol declarations, track their instantiations and add a new physics instance property to them instead. So ‘some way to associate that data with the symbols in the exported JS file’ to me, would look something like how the following adds a this.newInstance.frame_0… 

// [Library] project/world [smArt.World]
(lib.World = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var PHX={};
		PHX.world = {
			isDebugDrawing: true,
			zoom: .75
		};
		return PHX;
	}

	// input controlled hero
	this.hero = new lib.Body_4();
	this.hero.setTransform(83,-191);
	this.hero.cache(-22,-22,44,44);
	this.hero.this.frame_0 = function () {		// previously declared inside lib.Body_4
		var PHX={};
		PHX.body = {
			density: 0.3,
			ezShape: 'circle',
			friction: 0.5,
			isTarget: true,
			restitution: 0.8
			};
			return PHX;
		}

// alternative to a duplicated new lib.Body_5() of lib.Body_4() 
// just for identical graphics with unique this.enemy.frame_0 for unique physics behaviour. 
// This does already work I just need to solve the problem of manipulating the output
// to get it here...

	// timeline tweened enemy 
	this.enemy = new lib.Body_4();  		// same symbol definition
	this.enemy.setTransform(83,-191);
	this.enemy.cache(-22,-22,44,44);
	this.enemy.frame_0 = function () {		// with unique instance property
		var PHX={};
		PHX.body = {
			density: 0.3,
			ezShape: 'circle',
			friction: 0.5,
			type: 'tween',
			restitution: 0.8
			};
			return PHX;
		}

}).prototype = p = new smArt.World();
p.nominalBounds = new cjs.Rectangle(-345,-271,729.2,484.5);

or alternatively a more direct 
this.newInstance.PHX = {
			density: 0.3,
			ezShape: 'circle',
			friction: 0.5,
			type: 'tween',
			restitution: 0.8
			};

For me (without knowing how complex it is) trying to hook into the exporter and add either:
this.newInstance.hero.frame_0 or a this.newInstance.PHX property definition directly to a new instance SEEMS cleaner than
trying to find all duplicated symbol declarations to delete and finding all there instantiations to rename and add this property to. 

Again which while not necessary to work just fine, file size consideration of coarse is necessary for mobile.

But culling code post production definitely will not be possible if I can’t get the library.items array structure in sync with the createjs output.js structure,
so I am getting ahead of myself :)

**Comment by SmartArtsStudio** [comment]
Hi Grant

Have you had a chance to look at the relationship between the 'createjs exporter duplicated name index symbol order' and the 'fl.getDocumentDOM().library.items array symbol order' ...I don't need a solution just yet, but if you know if the exporter moves items out of this array into a javascript object at any point and iterates that objects key/values out into the exported.js I believe we will know the answer: that finding a way to sync the two will never be reliable (if, as I believe javascript for..in loops don't guarantee consistent iteration order) 

Inaccurately synced lists rule out attempts to accurately add/move physics property declaration to a instance property assignment after instance instantiation (to cull duplicate exported.js code for mobile). Via regex post production anyway.

I tried to look further into FlashPro Library 'linkage' property, not fully understanding its intended use case. Why ALL the exporter seems to do with linkage is take it's symbol name in the IDE library and replace this name in the exported.js with what ever it's 'linkage' name is. 

Based on the only info I can find on HTML5 Canvas Project 'linkage': Sebastian's recent article, and a comment from Hemanth Kumar :

http://blog.gskinner.com/archives/2015/04/introduction-to-the-flash-cc-html5-canvas-document.html
"Unlike Flash, you don’t need to enter a “linkage”. All symbols in the library are exported."

Hemanth Kumar -  https://forums.adobe.com/thread/1203890?start=0&tstart=0
"Toolkit indeed exports library symbols with the AS-Linkage names specified.If no as-linkage names are present mc's are exported with their names." 

Was 'linkage' never intended to serve a role in the exporter? Its treatment of the 'linkage' values with identical names is just an unfortunate interference? If so I believe createjs exporter is missing a great opportunity. And 'linkage' is missing its true calling.

If the exporter took a library symbols 'linkage' value i.e. 'namespaced.superClass' (note the '.' operator) and instead of replacing the symbol name, it replaced the symbol's parent class like so:

(lib.docName= function() {       // INSTEAD of replacing lib.docName with lib.namespacedsuperClass' 
	this.initialize();                  // NOTE: the exporter currently strips out the '.' operator

	// Layer 1
	this.instance = new lib.World();
	this.instance.setTransform(340,270);

	this.addChild(this.instance);                // Alter the exporter to keep the '.' operator and
}).prototype = p = new cjs.MovieClip();       // REPLACE cjs.MovieClip with 'namespaced.superClass' 
p.nominalBounds = new cjs.Rectangle(355,239.1,729.2,484.4);

'linkage' would now serve a very valuable purposes. 
1) Different cjs.DisplayObjects could inherit the same custom behaviour from a custom name-spaced super class (replicating 'Base Class' from AS3 projects) Without devs/designers having to wade through the exported.js to find all the symbols and do each by hand each publish.
2) exported.js lib.Symbol names would remain as intended in the library.
3) Identical linkage names would not get indexes appended, and could then be used as an actual useful linkage Class identifier. Super class though! (which has a cjs.Container ancestor, devs responsibility to ensure, as the IDE has no way of checking js library paths like it can AS3 library paths... Yet. ;)  
Sub classes don't need to be injected into exported.js classes (they already have a perfectly good unique class name from the library) so if this was the intention, 'linkage' is wasted on sub classing.

Not to mention personally it would solve both my problems :)
The exported.js symbols would remain exactly as named in the library (and not have to be added back in to the output with comments. I should be able to code a jsfl script that in post production reliably takes the correct  this.frame_0 or this.PHX properties from duplicated DisplayObject's and adds them reliably as instance properties after its correct new symbol instantiations... then cull non-essential DisplayObject duplicate code.

Of coarse even if you agree with the value of linkage super classing, I assume the earliest this solution would be of any use to anyone will be the next release of FlashPro which I won't be holding my breath for :)

I have all the essential class functionality solved and working: drag'n'drop Box2D Worlds, Body, Joint symbol instances (simulating as3 components) with their own component property inspector panels to customise their individual instance physics properties. b2body's and b2joint's timeline tweens correctly participating in b2World physics simulation. This week I am starting to port the missing Joints and buoyancy / custom gravity (angry birds in space style) Controllers to, and bring box2dweb up to date  in order to implement those joints/controllers . Then produce a game which demonstrates everything to iron out any obvious kinks. So I expect still a good few months off before open-sourcing, but if I know where the limitations are I know what roads to not waste time looking down.

liquidFun (box2d liquid extension) implementation will follow or be included if its easier than expected (if non emscripten js port already exists), I am planning box2d closure and box2d c++ emscripten's  javascript compatibility with my framework ... but emscripten's asm.js is not readable, so for new devs/designer's to box2d education and debugging I decided on fixing box2dweb to align my whole project's libraries with createjs readability and documentation standards.

Thanks
Daniel

**Comment by SmartArtsStudio** [comment]
[Library.items order vs exported.js order SOLVED]
[HTML5 Document future suggestion if Adobe have not forgotten about Flash]

Hi Grant,

CreateJS Toolkits 'unclear' fl.getDocumentDOM().library.items processing order was caused by unique behavior of library.items who's item.itemType == 'component'. After all, who'd be using components in HTML5 Document! :)

CreateJS appends increasing indices to identically named library.item linkages as it parses the library.items array  simply backwards.
The library.items array parses the nested folder tree, from the lowest depth, breadth first each depth, up to the root library folder. (no surprises there, but...)

library.items who's item.itemType == 'component'...
CreateJS skips UNLESS that item has an instance on the stage (use count >= 1) CreateJS exports it. However any instances of a component symbol ( use count=0 ) CreateJS DOESN'T export it automatically like it does item.itemType == 'movie clip's. 

It was this anomaly that was causing the unpredictable miss match between MY library.items indexing pass and CreateJS indexing pass.

NOTE: library.unusedItems property does NOT match the library.item "Use Count" values as anything with a Linkage value is also considered 'used' (potentially by runtime AS3) and is not included in the library.unusedItems array.

FOR CONSIDERATION:
Obviously CreateJS never considered someone would want to export component symbols. But if you ever have any input into any future versions of the HTML5 Document mode, I believe HTML5 Document mode makes WAY TOO MANY assumptions about how the (extensible!) IDE 'should' be used.

I believe HTML5 Document should ONLY turn off features that are literally incompatible with the HTML DOM and leave anything which just simply, has nothing to do with HTML DOM turned on. It unnecessarily limits FlashPro's Extensibility to preconceived expectations, which would seem to defeat the whole purpose of the extensibility API.

Thanks to CreateJS, I see nothing stopping me (except time, this is a hobby project) from expanding the HTML5 Document mode to do just about everything the AS3 Document does but for javascript, most obviously super/sub classing external classes and linking to external library 'packages' (objects).

(Actually the: File > ActionScript Settings... window is the only feature in the features.xml that I could not identify how (or even if it can) be turned back on... and have not yet identified equivalent jsfl API, is currently what stops this... if you happen to how to point me in the right direction, that would be appreciated.)

Designers would not really be confused by the AS3 options still available, because the have very little interest in dealing with classes, linkages, libraries and components to be hunting for those menus. Developers wont be confused by them because they will recognize what they are used for. I follow the thinking, but it seems a much larger unfortunate sacrifice for only minor aesthetic gains.
