### ISSUE TITLE
Can the sprite animation begin before all images have been downloaded?

### ISSUE THREAD

**Issue by orcaman** [CreateJS/EaselJS#599]
I have a collection of a lot of images that together comprise my complete sprite. I am creating them as img DOM elements and then I give an array containing all images to the SpriteSheet "images" attribute. 

But I see that the animation does not start before all images have been downloaded (in my case, there are 30 images, so this is very apparent). 

This causes two issues:
1. A major performance issue (the animation takes a long time to start because we have to wait for all images to be downloaded). I would think that by breaking down a large image to multiple smaller ones, one would get better performance (because the download of the complete sprite would be progressive), but the fact is this takes a bit longer than just downloading one big sprite image. 
2. When the final image was downloaded, the sprite animation starts from the point in time where it would get to as if it started immediately. That is, if after 10 seconds all images are downloaded, the animation starts at second 10. 

Any way around this? 

Thanks

**Comment by macguffin** [comment]
You might want to consider creating a loader which waits till the images have all loaded before starting.
Preloadjs would be good for this.

**Comment by lannymcnie** [comment]
There is currently no support for playing a partially loaded SpriteSheet (I assume you want to only play frames from one image while the other loads). It is an interesting idea, but not easy to implement. Preloading your content as suggested by @macguffin is a good solution.

**Comment by gskinner** [comment]
We wait for all images in a sprite sheet to load before displaying anything to avoid problems with flickering sprites. Most sprite sheets are machine generated, and animations can be spread across multiple images, so frame 1 & 2 might be loaded, but 3-5 are not.

Likewise, we start playing the Sprite immediately, in case it is time synched.

@macguffin has the correct solution - use PreloadJS (or something similar) to load your images in advance. This makes things predictable. If you want to do something more progressive, then write I'd write a bit of code to manage multiple SpriteSheets.
