### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#605]
I wanted to use this program: https://www.codeandweb.com/spriteilluminator with my Easeljs game but FAQ says the framework has to support shaders.

Does Easeljs use shaders and if not, how tricky would it be to write something that could use and apply shader data?

Thanks!

**Comment by lannymcnie** [comment]
Currently there is no shader support. The WebGL functionality that exists bring some of the existing functionality into WebGL, but doesn't enable additional WebGL features. Future versions may have this support though.
