### ISSUE TITLE
Applying filters to spritesheets

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#607]
Hi, I'm wondering if there's an inexpensive way to apply a filter to a sprite or spritesheet with multiple frames each possibly with different sizes and registry points.

For my example I am trying to make particles and projectiles that only apply a color filter ONCE when they are initialized. That way I can have green or red blobs etc. The problem is, when I finally got the color filter to work correctly, the sprite sheet would not animate unless I called "updateCache()" every tick. Once that was called it animated the sprite but it only took 3 or 4 projectiles to lag the game like crazy. If I comment out updateCache it runs hundreds of projectiles smoothly but they won't animate.

I found this: http://jsfiddle.net/lannymcnie/NRH5X/1/

Someone posted this on your CreateJS forums but still the end result requires me to call UpdateCache every tick. Is there a better way to do this?

Thanks

**Comment by MannyC** [comment]
In the forum example that you've posted, you want to follow method 2, not method 3.  This will not require you to call `updateCache` on each tick.   Method 3 is only required it you want to change the filter at every tick.
