### ISSUE TITLE
baseLine and textAlign seem backwards

### ISSUE THREAD

**Issue by zwhitchcox** [CreateJS/EaselJS#609]
Not sure if this is a bug, but this seems pretty counterintuitive to me

![out](https://cloud.githubusercontent.com/assets/4328800/7443263/cd8c7174-f10b-11e4-97ed-cb4c2b85a95c.gif)

**Comment by lannymcnie** [comment]
This is based on canvas APIs. You need to think of it more like where the text draws relative to the position.
