### ISSUE TITLE
Ticker event seem to be cached and ahead of event, no sync

### ISSUE THREAD

**Issue by futurist** [CreateJS/EaselJS#613]
I want to make snapshot of canvas, and find there's somewhat "cached" of animation, say not sync with the click event. Please see below demo:
>http://1111hui.com/lido-may/

Click the screen when the guy move around the LOGO, try many times and you will see the snapshot and the animation are not SYNC.

I don't know it's the problem of EaselJS or TweenJS, and post here, but I've tried other tween library the result is same. So I guess it's the problem of EaselJS.

I've tried many way but not luck. Is it a bug or is there any way to work around this?

**Comment by wdamien** [comment]
I checked out your code, there are 2 issues I can see:

1) Your source dimensions are incorrect, so when you call drawImage() cropping is occurring.
2) You should call stage.update() just before you take the snapshot, currently your drawing 1 tick behind.

**Comment by futurist** [comment]
Thank you very much. Problem solved. stage.update should be at last line in ticker.
