### ISSUE TITLE
Mouse events do not work in desktop IE11

### ISSUE THREAD

**Issue by zlumer** [CreateJS/EaselJS#616]
OS: Windows 8.1
Browser: Internet Explorer 11

Mouse events don't work. IE11 only sends `pointerdown`/`pointerup` (no `mousedown`/`mouseup`).
I tried enabling Touch, but there's one more problem:
https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/ui/Touch.js#L75
```js
(window.navigator['pointerEnabled'] && window.navigator['maxTouchPoints'] > 0)); // IE11+
```
Here, `pointerEnabled` is true, but `maxTouchPoints` is 0 on desktop (haven't tried it on the phone yet).

Summary:
Mouse events don't work because IE11 doesn't send them.
Touch events don't work because the Touch.js check fails.

**Comment by zlumer** [comment]
On my Windows Phone 8.1 it correctly returns `pointerEnabled = true` and `maxTouchPoints = 10`

**Comment by lannymcnie** [comment]
Will look into this. The Touch logic is correct (only needed for touch support, which should have `maxTouchPoints`), but we will need to ensure mouse events are properly supported otherwise.

**Comment by lannymcnie** [comment]
Did some testing on our end.
1. I haven't come across a device that has `pointerEnabled=true`, but `maxTouchPoints` of 0.
2. On all desktop devices, the regular mouse events work fine, so the only time we need pointer support is when we are doing touch or multi-touch gestures.

What sort of device do you have? Does it have some touch support?

**Comment by zlumer** [comment]
IE: 11.0.9600.17728
Windows: 8.1 Pro
Laptop: Acer Aspire V3-571G
No mouse connected, only touchpad (with scrolling gesture).

I can do more tests, just let me know what kind of additional info you will find useful.

![](http://i.imgur.com/rNmvGra.png)

**Comment by zlumer** [comment]
I've attached a pull request with possible workaround. Just in case :smile:

**Comment by lannymcnie** [comment]
So I was able to reproduce the conditions above (`pointerEnabled`, `maxTouchPoints`), but it still works fine with regular mouse events. The PointerEvent events are only necessary when working with touch interfaces, and they map to regular mouse events in EaselJS anyways. What exactly is not working for you?

Can you run this demo in your IE11? http://dev.gskinner.com/createjs/MouseEventsTest.html
1. Click on the circle
2. Look at the console output

**Comment by zlumer** [comment]
The demo works correctly.
I guess there's a problem with my configuration, I'll look what else could cause that.

**Comment by zlumer** [comment]
Looks like it was my mistake after all: I've had a `preventDefault()` on `touchstart` and `touchmove` somewhere in my app. Removing it fixed mouse events.

Thanks for the help and sorry for misguiding you.
