### ISSUE TITLE
DisplayProps.setValues() method

### ISSUE THREAD

**Issue by FumioNonaka** [CreateJS/EaselJS#622]
Value of the compositeOperation property is not properly set with the [DisplayProps.setValues() method](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/geom/DisplayProps.js#l88).  [The argument of shadow is assigned to it](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/geom/DisplayProps.js#l104).

Also, the default value of the [DisplayProps.alpha property is 1](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/geom/DisplayProps.js#l102) although [the doc](http://www.createjs.com/Docs/EaselJS/classes/DisplayProps.html#method_DisplayProps) tells that it is 0.

**Comment by lannymcnie** [comment]
Thanks! We will definitely fix these shortly.

**Comment by lannymcnie** [comment]
I have pushed these changes to GitHub. They are not part of the 0.8.1 release.
