### ISSUE TITLE
add support for elliptical arcs.

### ISSUE THREAD

**Issue by tromgy** [CreateJS/EaselJS#623]
in my work I needed to draw arbitrary elliptical arcs e.g.

graphics.ellipticalArc(cx, cy, rx, ry, startAngle, endAngle, counterClockwise)

where cx, cy are the coordinates of the center of the ellipse defining the arc,
rx and ry are the radii.

I have an implementation for this, just don't know how to do a pull request -- do I need my own branch?

**Comment by lannymcnie** [comment]
You will need to fork the repo, make the change, and then submit the request. Here is a guide: https://help.github.com/articles/using-pull-requests/
