### ISSUE TITLE
Document bug of Rectangle.pad() method

### ISSUE THREAD

**Issue by FumioNonaka** [CreateJS/EaselJS#625]
The *Rectangle.pad()* method is mistakenly indicated as [extend()](http://www.createjs.com/docs/easeljs/classes/Rectangle.html#method_extend) in the doc.  And default values of arguments are not set in [source code](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/geom/Rectangle.js#l141) while the doc tells that they are 0.

**Comment by lannymcnie** [comment]
Thanks! I have made the changes in GitHub. Note that the `pad` method should not have optional parameters.
