### ISSUE TITLE
Failed to access http://createjs.com/ in China

### ISSUE THREAD

**Issue by jonlimx** [CreateJS/EaselJS#627]
When accessing http://createjs.com/ after a long time loading. Could you please take a look? Will be pleasure if you need my help to troubleshoot.

**Comment by wdamien** [comment]
@jonlimx we currently use a few scripts from CDN's that may be blocked in China, if you can let us know which ones you can see or not, we might be-able find suitable alternatives.

Currently we use:
https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js
http://use.typekit.net/cek3iwo.js
https://code.createjs.com/createjs-2015.05.21.min.js

**Comment by jonlimx** [comment]
@wdamien Thanks for you response. I can't assess the first one(the googleapis), but able to access the rests. I missed something in the first post - actually,  when accessing http://createjs.com/, I got a blank page after a long time loading.
I would like to send you a screenshot, but seems like we can't attach an image here.

**Comment by liuyi** [comment]
We can not visit google's any content, so we have to use proxy to visit the website which use  google api and fonts. I am from china too -_-  @jonlimx  You can use GoAgent when you want access to these sites.

**Comment by jonlimx** [comment]
@liuyi Thanks for your reminder. GoAgent doesn't always work, cuz it could be blocked by gov some day.

**Comment by wdamien** [comment]
Good to have verification that its the Google apis causing the issue. Can you try these other cdn links?  Its an easy change to use another one that will work everywhere.

https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js
http://cdn.jsdelivr.net/jquery/2.1.4/jquery.min.js

**Comment by liuyi** [comment]
@jonlimx  http://libs.useso.com/ This link would be help you.

**Comment by jonlimx** [comment]
@wdamien Thanks for your follow up.These two CDN work in China.

**Comment by wdamien** [comment]
@jonlimx createjs.com is updated to use cloudflare instead of the google apis, hopefully the site will work in China now.

**Comment by jonlimx** [comment]
@wdamien I enjoyed a one week trip in the past week, sorry for the late response. It works well now! Thanks very much!
