### ISSUE TITLE
Browserify / Webpack support?

### ISSUE THREAD

**Issue by nlhkh** [CreateJS/EaselJS#638]
Would there be a browserify or webpack version coming soon?

**Comment by wdamien** [comment]
This is something we are considering. Its not a small change, since the way the code base is architected we would need to implement it across all 4 libraries at once. You can see more discussion on the topic here: https://github.com/CreateJS/PreloadJS/issues/85

**Comment by nikini** [comment]
No news on this?

**Comment by glebmachine** [comment]
The worst animation library ever.

**Comment by gskinner** [comment]
Things have been a bit (read: lot) slower than we'd like due to client work keeping the core team busy. We are in the midst of an ES6 rewrite now though, that should provide this functionality.

**Comment by stephanedemotte** [comment]
Release date ?

**Comment by bdanis** [comment]
Any update on this? Considering it's packaged with Adobe Animate, it would be practical to set it up in web devs pipelines.
There are some npm packages that offer webpacking. Are any of them recommended?

**Comment by jamint** [comment]
Any update? Would be awesome to have.

**Comment by limichange** [comment]
Try it.
https://github.com/yuki-torii/yuki-createjs

**Comment by kad0108** [comment]
@limichange Thanks for your sharing, it's very helpful for me. I've been troubled by the weird errors for some time when I use createjs with webpack. Thanks a lot.

**Comment by MIKUScallion** [comment]
Hi every one.
We can use this.

npm install latest-createjs
This package will follow the latest official createjs version and also include the old version.
Have fun!

https://www.npmjs.com/package/latest-createjs

**Comment by noemi-salaun** [comment]
What can we do ? Where should we look to help you migrating to ES2015 module ?

**Comment by MIKUScallion** [comment]
@noemi-salaun , No, See That.

https://github.com/CreateJS/Combined

@wdamien ，I Thinks you can close this issue.

**Comment by tehvgg** [comment]
The `2.0` branch contains bundler support, and is currently live on npm under the `@createjs` scope.
