### ISSUE TITLE
Does EaseIJS support networking and video playing natively?

### ISSUE THREAD

**Issue by bagusflyer** [CreateJS/EaselJS#640]
I googled and find EaselJS, an elegant html5 game engine. I have a question:

Does EaseIJS support networking and video playing natively? Or if there are any plugins doing that? Thanks.

**Comment by wdamien** [comment]
Yes, Easel supports displaying videos. You can pass your existing video instance to a Bitmap object. Note, that not all browsers support drawing video to canvas, you will be fine targeting the latest desktop browsers.

```
var b =  new createjs.Bitmap(yourVideo);
```
