### ISSUE TITLE
problem about mouseover/rollover.

### ISSUE THREAD

**Issue by dysonbird** [CreateJS/EaselJS#641]
createjs version:createjs-2015.05.21.min.js

When I use this.on("mouseover", this.mouseover, this, !1)  or this.on("rollover", this.mouseover, this, !1) in my container,It work fine in  IE or chrome browser on pc, But when I play my game on mobile device IOS or Android, It can't work.

Any suggestions in this regard?

**Comment by lannymcnie** [comment]
iOS devices don't have mouseOver or rollOver.  What are you trying to accomplish?

**Comment by dysonbird** [comment]
I'm trying to make a elimination game, When mouseOver or rollOver will select the bubble to eliminate.
Thanks for give me some advice.

**Comment by lannymcnie** [comment]
You will need a different approach for mobile, since most devices don't support rollover or mouseover.
