### ISSUE TITLE
DisplayObject.hitTest ignores rotation

### ISSUE THREAD

**Issue by mbonacci** [CreateJS/EaselJS#646]
All the tutorials on hitTest are using circles, but when you try using different shape and apply a rotation to it, hitTest ignores the rotation and reports a hit in wrong place. I assume the same is true for scale, haven't tried it though.

Example: https://jsfiddle.net/Lyw4e85L/

**Comment by gskinner** [comment]
From the docs:
"Tests whether the display object intersects the specified point in local coordinates"
http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#method_hitTest

So transformations are not considered by hitTest. You need to convert your coordinates (ex. using `globalToLocal()` or similar first.

**Comment by gskinner** [comment]
Actually, I'm going to leave this open for now, because I think there is value in expanding the docs a bit on this point.

**Comment by lannymcnie** [comment]
I have updated the documentation to be a little more clear on local coordinates. The existing documentation actually used stage coordinates in the example, which would only be reliable if the contents were at [0,0]. The update includes an example using `globalToLocal`.

Here is an updated fiddle with globalToLocal: https://jsfiddle.net/lannymcnie/Lyw4e85L/1/
```js
var p = circle.globalToLocal(stage.mouseX, stage.mouseY);
if (circle.hitTest(p.x, p.y)) {
    // Collision
}
```

Thanks for the report!
