### ISSUE TITLE
where were the OFFICIAL TUTORIALS?

### ISSUE THREAD

**Issue by potaty** [CreateJS/EaselJS#658]
http://www.createjs.com/getting-started/tutorials/getting-started/tutorials/inheritance is 404...

**Comment by lannymcnie** [comment]
Thanks! It looks like the links on the Getting Started page are not resolving properly. We will fix it up shortly!

**Comment by lannymcnie** [comment]
I believe this has been resolved. Cheers.

**Comment by sergeyzhulin** [comment]
Truly saying, just tried link below, it still returns 404 page
http://www.createjs.com/getting-started/tutorials/getting-started/tutorials/inheritance

**Comment by potaty** [comment]
@sergeyzhulin  http://www.createjs.com/tutorials/Inheritance/ It's in this page. It can be link to http://www.createjs.com/getting-started

**Comment by lannymcnie** [comment]
Yes, the initial link you posted was the result of the issue on this page: http://www.createjs.com/getting-started - and is incorrect. Sorry for any confusion.
