### ISSUE TITLE
Why SpriteSheetBuilder.addAnimation parameter 'frequency' does not work?

### ISSUE THREAD

**Issue by httphttp** [CreateJS/EaselJS#661]
It looked no different when I changed the parameter 'frequency' from 1 to 60;
And how to set the frequency... besides set the ticker's fps

**Comment by lannymcnie** [comment]
Thanks for reporting this, it is a bug. Earlier versions of SpriteSheet used `frequency`, but this was changed to the easier-to-understand `framerate`, which works differently. It looks like SpriteSheetBuilder was not updated to properly support it. 

We will post a fix soon!

**Comment by lannymcnie** [comment]
I have pushed support for both a `frequency` argument on the SpriteSheetBuilder constructor, as well as a "speed" argument on the "addAnimation" method (which replaces the old "frequency" argument). 

Note that "speed" operates as a multiplier on the framerate (which will default to the Ticker framerate), and works the opposite as frequency did.

These changes currently exist in the "NEXT" version of EaselJS in GitHub, and will be included in the next public release (TBD).

Thanks again!

**Comment by httphttp** [comment]
Thanks very much.
