### ISSUE TITLE
Is Container.getObjectsUnderPoint() missing a point object parameter for memory management?

### ISSUE THREAD

**Issue by SmartArtsStudio** [CreateJS/EaselJS#663]
Should Container.getObjectsUnderPoint() be able to accept a point object to optionally stem the creation of undesired new createjs.Point objects? 

Internally getObjectsUnderPoint calls this.localToGlobal( x, y ) without passing an argument to localToGlobal's optional point parameter, resulting in the default creation of a new createjs.Point.

Suggestion:

```
p.getObjectsUnderPoint = function(x, y, mode, pt) {
    var arr = [];
    var pt = this.localToGlobal(  x, y, pt );
    this._getObjectsUnderPoint(pt.x, pt.y, arr, mode>0, mode==1);
    return arr;
};
```

**Comment by lannymcnie** [comment]
Thanks, we are evaluating this for the next build. It will probably get implemented similar to how you suggested. Cheers!

**Comment by gskinner** [comment]
Are you encountering a scenario where this is causing noticeable memory churn? This seems unlikely to cause any significant issues unless you are calling getObjectsUnderPoint hundreds of times per tick (in which case, the primary cost would likely be the under-the-hood rendering). Totally willing to entertain a fix to this, I just need to understand when its warranted.

Please reopen as appropriate.

**Comment by SmartArtsStudio** [comment]
No I have not thoroughly tested for noticeable memory churn yet, but anticipate the potential for it  while detecting displayObjects representing box2d particle systems within a defined region of the stage. This does have the potential to call getObjectsUnderPoint() 100s even 1000s in a given frame. This will be on top of all the existing physics simulation calculations going on each frame for the entire physics world. So I like to control as much pre-allocated memory where ever its possible to reduce the risk of garbage collection taking a chunk out of the frame also.

I found it while building a box2d sensor which can be added and removed from the stage via the timeline to activate and deactivate. Which requires the sensor to actually detect all displayObjects representing box2d bodies and particles underneath/inside its own shape, because box2d sensors do not natively do this behaviour.

**Comment by SmartArtsStudio** [comment]
@gskinner 
No I have not thoroughly tested for noticeable memory churn yet, but anticipate the potential for it while detecting displayObjects representing box2d particle systems within a defined region of the stage. This does have the potential to call getObjectsUnderPoint() 100s even 1000s in a given frame. This will be on top of all the existing physics simulation calculations going on each frame for the entire physics world. So I like to control as much pre-allocated memory where ever its possible to reduce the risk of garbage collection taking a chunk out of the frame also.

I found it while building a box2d sensor which can be added and removed from the stage via the timeline to activate and deactivate. Which requires the sensor to actually detect all displayObjects representing box2d bodies and particles underneath/inside its own shape, because box2d sensors do not natively do this behaviour.
