### ISSUE TITLE
Sound not triggered on iOS 9 when Touch is enabled

### ISSUE THREAD

**Issue by ramezrafla** [CreateJS/EaselJS#664]
The same content that triggered audio on iOS 8 stopped as soon as we upgraded to iOS 9. We could not trigger audio on touch when using createjs.Touch. 

This is related to #586. 

To get around it, it turns out you have to 

(1) set allowDefault to true when calling Touch like this `createjs.Touch.enable(stage,false,true)` and 
(2) `stage.preventSelection = false` 

for the event to be bubbled properly for Safari on iOS to acknowledge a user event to trigger audio.

Maybe this is merely a doc issue? Not sure yet.

**Comment by Article19** [comment]
We're seeing something similar in only 1 of our HTML5 titles. The others have the same setup and are playing sound as expected under iOS9. We have not yet pinned down what might be different about this one title. Sound continues to function under iOS8. The workaround proposed above does get audio working under iOS9, but has some undesirable side-effects.

**Comment by ramezrafla** [comment]
Agreed, the above approach makes it complicated to do fancier things like dragging. Some updates in terms of our progress with iOS9:

We force the user (on mobile) to click on a 'Start' button with NO createjs.Touch.enabled (so the events bubble to the DOM). We then play audio to get the OS to recognize we can now play audio. From that point on, we have full access to audio WITH createjs.Touch like before iOS9.

**Comment by ramezrafla** [comment]
And to answer why it might only work on one of your titles, do you enable createjs.Touch from the start AND is sound triggered by a createjs object? That is what blocked our HTML5 Web App from playing audio. If you trigger the audio from within the HTML5 DOM (e.g. a button), you should be fine. It seems events don't get bubbled the first time from Canvas to play audio.

**Comment by Article19** [comment]
Our solution (and all of our titles use it) has been to:
- enable createjs.Touch from the start
- play an audio file from within the DOM, as follows:
    var sound = document.getElementById('silence');
    sound.play();
- subsequent sounds are triggered by createjs.Sound.play

This is currently working in all but one of our games on iOS9. There's probably a subtle difference in this title (it was the first we developed) which is blocking the event from bubbling through.

Your solution above seems interesting (have the user trigger audio before createjs.Touch gets enabled). I'll report back shortly.

**Comment by Article19** [comment]
Slight update...we just noticed that in the games in which sound is working, the very first sound instances does not play audibly, but all subsequent instances do (with our iOS8 setup). The 1 offending title does not play any audio at all.

I can confirm that your workaround works...though I'd rather this get solved another way.

**Comment by ramezrafla** [comment]
For mobile, the first audio play has to be triggered by the user, and then gets assigned to the triggering namespace. I guess in the prior versions of iOS8 you were able to fool the browser. What we do is attach a silence mp3 to the first 'start' button, then all subsequent audio gets played without the need for user interaction. 

Note: We also only use createjs.Touch with dragging; we found we don't need it when just want a basic touch event (Disclaimer: we have not tested on Android yet. So that last behaviour may change.)

**Comment by lannymcnie** [comment]
There is a `playEmptySound` method on the WebAudioPlugin, which will do this for you. Just wire it up to a click handler.

    createjs.WebAudioPlugin.playEmptySound();

http://createjs.com/docs/soundjs/classes/WebAudioPlugin.html#method_playEmptySound

**Comment by ramezrafla** [comment]
Agreed! Thanks Lanny -- didn't dig that deep enough in the docs :)

**Comment by Article19** [comment]
Thanks guys! Something has definitely changed from iOS9 to iOS9, not yet sure where the solution should lie. For the moment I have implemented ramezrafla's workaround by forcing a click on the first screen before setting createjs.Touch. Hopefully something better will emerge over time as iOS9 rolls out to more players...

**Comment by Article19** [comment]
...seems this issue has been mentioned over on HTML5 Game Devs:
http://www.html5gamedevs.com/topic/17326-ios-9-webaudio-issues/

I experimented for a bit and discovered that the following will work under iOS9:
- enable createjs.Touch from the start (as we always have)
- before user interaction is required, add the following event: stage.addEventListener("stagemouseup", enableAudioFromStageMouseUp);
- the function called will play a silent sound then remove the stagemouseup event:

function enableAudioFromStageMouseUp(event) {
     createjs.Sound.play("silenceSnd", {interrupt: createjs.Sound.INTERRUPT_ANY});
     stage.removeEventListener("stagemouseup");
}

...from then on audio will work.

**Comment by lannymcnie** [comment]
@Article19 See my comments above about the `playEmptySound` method.

**Comment by Article19** [comment]
Hey Lanny - saw that. Does that only serve as a replacement for using SoundJS to play a silent sound, or does it also address this whole issue of getting audio to play under the various flavours of iOS?

**Comment by lannymcnie** [comment]
It is just a placeholder method to facilitate playing _something_ on click to help enable sound on mobile browsers. You still have to do the rest of the steps.

**Comment by Article19** [comment]
Excellent - thanks for pointing it out!

**Comment by JonnyNgan1** [comment]
I've found that changing my events from "mousedown" (older library) to "click" works for me. However, if you place your finger on the target and hold for a couple seconds then release to trigger the "click" event, it doesn't work. It seems that ios9 doesn't register a click if the click is done in that fashion (click hold for a second and release). 

Can you test whether this is the case with you?

Using EaselJS 0.7.1, soundjs 0.6.1, preloadjs 0.4.0m Tweenjs 0.5.0

Thanks

**Comment by lannymcnie** [comment]
I did some testing, and was unable to reproduce the issue with touch on iOS9. I built a sample based on the MobileSafe demo in GitHub, greatly simplified:

1. Listen for click on a HTMLTextElement
2. Onclick, initialize the default SoundJS plugins (which will automatically play an empty sound if WebAudio is supported)
3. Load some audio
3. Once the audio is loaded (asynchronous), it will play a sound every 2 seconds from a setInterval.

The demo works fine in both iOS8 and iOS9.

To further test the Touch issue, I implemented an EaselJS Stage with a shape.
1. During initialization, create a Stage and draw a shape on it.
2. Enable Touch on the stage
3. Listen for click on the shape instance 
4. Onclick, load and play audio (same as steps 2-4 in the earlier list)

Here is the sample HTML file I am using: http://playpen.createjs.com/mobilesafe/MobileSample.html

Please let me know if this sample doesn't work for you, or if there are steps I am missing. I am trying to put together a dot-release for Git/CDN shortly, and was hoping to include a critical fix, or at least updated docs on this issue.

Thanks!

**Comment by TheJasonReynolds** [comment]
I second JonnyNgan1's "click" vs "mousedown" for the for the first click
(mousedown works after that first sound play). Mousedown worked as the
first play before ios9. Not related to CreateJS but I also found this to be
true for other elements such as a file select dialog moving from ios8 to
ios9.

**Comment by Article19** [comment]
Lanny, it seems that what we're all honing in on is that more than a "mousedown" event is now required to enable audio under iOS9. Both a "click" and a "stagemouseup" seem to do it (there may be other events, I suspect the 'up' is the necessary bit). I think <=iOS8 had slightly different requirements, but it looks like we have a set of solutions here.

**Comment by JonnyNgan1** [comment]
Hi Lanny

I tested your test (http://playpen.createjs.com/mobilesafe/MobileSample.html) and it works. However as I mentioned in my last post, if you press and hold for about 2 seconds and then release, the audio doesn't play. Not sure why this is but it seems like its not triggering the correct event if the click is done in a press hold then release manner. Granted I wouldn't expect users to "click" in this manner but it is a strange issue.

using IPad Air

Jonny

**Comment by lannymcnie** [comment]
@JonnyNgan1 It looks like iOS does not want to enable WebAudio from scroll-type gestures. Touchstart is removed completely, and touchend only works if it comes from a "click". If you hold down too long, it becomes a scroll/gesture, and it no longer works.

This is all complicated by the fact that "mousedown" events will not work if an element has a "touchstart" event. Enabling the Touch support in EaselJS will make mousedown no longer work.

The best we can really do is to support touchend AND mousedown, and just live with long press not helping to enable audio.

We plan on releasing an update to SoundJS that automatically handles the first document-level mousedown/touchend event triggered by the user, which will handle this use-case automatically. If the user just has SoundJS, then mousedown will work across the board. If they start using EaselJS/Touch, then it will have to fallback on `touchend`.

Thanks for all your help identifying this issue. Let me know if you have additional suggestions or a better approach for SoundJS to do this automatically.

**Comment by lannymcnie** [comment]
I pushed an update to the NEXT version of SoundJS to listen for touchend/mousedown, and play an empty sound to unlock the audio context. This should prevent you from having to manually play an empty sound. Feel free to test it out to see if it helps. 

If you insist on using mousedown + Touch, you will have to follow @ramezrafla's initial suggestion of `stage.preventSelection=false`, and `allowDefault` on Touch.

**Comment by FiveHundredMiles** [comment]
Thank you, lannymcnie, for responding to this iOS9 related issue.  

Here's my workaround for this issue :
```javascript
<canvas  onclick="playSound();" id="canvas" width="350" height="250"></canvas>
<script>
    function playSound () {
        createjs.WebAudioPlugin.playEmptySound();
    }
</script>
</code>
```
I hope this helps.

**Comment by ramezrafla** [comment]
@Petra, your solution is quick and easy. 

However, wouldn't the 'click' event trigger empty audio every time the canvas is touched (not just the first time)?

**Comment by FiveHundredMiles** [comment]
Try this:
```javascript
    var isSoundReady = false;
    function playSound () {
        if (isSoundReady === false) {
            createjs.WebAudioPlugin.playEmptySound();       
            isSoundReady = true;    
        }       
    }
```

However, this  workaround only works on "click" event. It does not work for events such as "touchstart" or "touchend" events. :-(

I have checked this solution: 
http://playpen.createjs.com/mobilesafe/MobileSample.html
But the downside to this solution is that user is required to "click" or "touch" to start.

**Comment by lannymcnie** [comment]
@FiveHundredMiles Have a look at my previous comments in this thread. We have patched SoundJS (latest NEXT in GitHub) to automatically listen for the necessary events, and play the empty sound for you. There is no longer any need to handle this manually.

Cheers.

**Comment by fnovais** [comment]
How can I get this to work changing my audio everytime I need, since variable "src" is already set at the begining of the script?

**Comment by lannymcnie** [comment]
@fnovais I don't know what you need exactly. You only need the mouse event the very first time. You should NOT be changing the src of audio at run-time.
