### ISSUE TITLE
createjs.extend removes methods from prototype

### ISSUE THREAD

**Issue by ktimothy** [CreateJS/EaselJS#666]
```js
var MyClass = (function(){
  function MyClass() {}

  MyClass.prototype.myMethod = function(){}

  createjs.extend(MyClass, createjs.Container);

  console.log(MyClass.prototype.myMethod); // undefined

  return MyClass;
})();
```

Why does CreateJS do that to prototype?

**Comment by lannymcnie** [comment]
The extend method creates a **new** prototype based on the super class, so it will not maintain the existing methods in the class you pass in. The extend utility is for creating a new object based on the super class to add functionality to, and not to blend multiple class prototypes together. 

You should define the methods you want _after_ extending Container.

Here is the extend method for reference:

    function o() { this.constructor = subclass; }
	o.prototype = superclass.prototype;
	return (subclass.prototype = new o());

**Comment by gskinner** [comment]
Lanny's description is correct. You should extend before appending methods. To update your sample:

````js
var MyClass = (function(){
  function MyClass() {}
  createjs.extend(MyClass, createjs.Container);
  MyClass.prototype.myMethod = function(){}
  console.log(MyClass.prototype.myMethod); // function
  return MyClass;
})();
````
