### ISSUE TITLE
GetBounds() on bitmap is returning Width and Height as 0 on Internet Explorer

### ISSUE THREAD

**Issue by murteira** [CreateJS/EaselJS#667]
The function GetBounds() on bitmap is returning Width and Height as 0 on Internet Explorer.

I found two ways to fix:

1. Don't use tagLoader, i was using LoadQueue with parameter "false", you should use "true":
new createjs.LoadQueue(true);

2. If you want or need to use TagLoader you must get width/height using naturalWidth/naturalHeight.

**Comment by lannymcnie** [comment]
Sounds like we should check `naturalWidth` as well in Bitmap `getBounds()`.

**Comment by lannymcnie** [comment]
This was fixed in 0.8.1 (May)
