### ISSUE TITLE
SpriteStage ignoring transforms

### ISSUE THREAD

**Issue by Garinn** [CreateJS/EaselJS#670]
Hi!

As of 0.8.1, SpriteStage ignores any transforms (translate, scale etc) applied directly to the stage, even though the docs don't mention any such restrictions. This is especially inconvenient if you want to combine Sprites and Bitmaps, since arbitrary Bitmaps can only be added direcly to the SpriteStage, not to SpriteContainers (and regular Containers aren't allowed for SpriteStages).
I wanted to implement panning and zoom for my whole scene, hence why I tried transforming my Stage.

Had a look at the source and it was pretty easy to enable transforms for the SpriteStage:

Change

``` javascript
p._drawWebGLKids = function(kids, ctx, parentMVMatrix) {

            [...]

            // Get the kid's global matrix (relative to the stage):
            mtx = (parentMVMatrix ? mtx.copy(parentMVMatrix) : mtx.identity()).appendTransform(kid.x, kid.y, kid.scaleX, kid.scaleY, kid.rotation, kid.skewX, kid.skewY, kid.regX, kid.regY);

}
```

to

``` javascript
p._drawWebGLKids = function(kids, ctx, parentMVMatrix) {

            [...]

            if(!parentMVMatrix) {
                mtx = new createjs.Matrix2D().identity().appendTransform(this.x, this.y, this.scaleX, this.scaleY, this.rotation, this.skewX, this.skewY, this.regX, this.regY);
            } else {
                mtx = mtx.copy(parentMVMatrix);
            }

            // Get the kid's global matrix (relative to the stage):
            mtx = mtx.appendTransform(kid.x, kid.y, kid.scaleX, kid.scaleY, kid.rotation, kid.skewX, kid.skewY, kid.regX, kid.regY);
}
```

Is there any reason why this is omitted? Code comments suggest this was intentional, but I can't see why.

**Comment by gskinner** [comment]
Thanks for looking into this. If you're able to do a pull request for this, we'll have a look, do a bit of testing, and integrate it if we don't encounter any issues.

**Comment by TiagoMarinho** [comment]
Should arbitrary bitmaps be added to SpriteStage anyway? I though the reason for SpriteContainers not allowing more than a single spritesheet was that you should merge every graphic into a single, big spritesheet.

Using arbitrary bitmaps on the stage has no performance implications?

**Comment by MannyC** [comment]
AFAIR EaselJS just puts a single texture into the GPU's memory at a time, so changing it incurs a performance hit, meaning it's better to use the same texture if you can.  However, there's also a limit to how big the texture can be, and it's device dependent.  

https://www.khronos.org/registry/webgl/sdk/tests/conformance/limits/gl-max-texture-dimensions.html

4096 on my Nexus 4,  16384 on my PC. 1024 is the minimum (https://www.opengl.org/sdk/docs/man/html/glTexImage2D.xhtml)

**Comment by lannymcnie** [comment]
Updates to SpriteStage/SpriteContainer are deprecated due to the new StageGL approach. Check out the [StageGL-beta branch](https://github.com/CreateJS/EaselJS/tree/StageGL-beta) in GitHub.

Closing this issue in the mean time.

**Comment by Cleod9** [comment]
@lannymcnie Just stumbled upon this StageGL mention, phenomenal work for a beta branch! This is a huge improvement over the limitations of SpriteContainer/SpriteStage. I plugged it into a 1920x1080 CreateJS canvas game we're developing and it's basically addressed of all of our performance woes without issue. Is there a recommended place I can follow along with news/updates on StageGL?

**Comment by lannymcnie** [comment]
@Cleod9 That is great to hear!

We are planning some polish and release in the next 2 weeks. We will post updates to the CreateJS blog and twitter.

Cheers!
