### ISSUE TITLE
instanceof Array vs Array.isArray() in SpriteSheet

### ISSUE THREAD

**Issue by jsaelhof** [CreateJS/EaselJS#672]
I've run into an issue today with creating Sprites. I've traced the problem down to one line in the SpriteSheet class.

The issue is that the SpriteSheet class fails to correctly test if the input (data.frames) is an Array if the array was created in a different frame. In my case, the array is created in the parent frame but the sprite is created in a same-domain child iframe. 

Here is an example of the SpriteSheet data as instantiated in the parent frame.

```javascript
{
  images: [ my image ref loaded by preloadjs ],
  frames: [
     [1,0,41,56],
     [44,0,26,56],
     [72,0,35,56],
     [109,0,35,56]
  ]
}
```

The json above is declared in a file loaded by my parent frame (This is crucial to the problem). When I create the Sprite in the child iframe and add it to the display list, nothing appears. Additionally I found that calling getBounds() returns null.

The same exact code works fine when run in the parent frame. Sprite appears and getBounds() works as expected.

I tracked the issue down to one line in the "_parseData" function of SpriteSheet. This line checks to see if the input for data.frames is an Array and if not, handles it as the alternate Object form.

```javascript
if (data.frames == null) {
   // nothing
} else if (data.frames instanceof Array) {
   // handle as array
} else {
   // handle as object
} 
```

The issue is using the instanceof operator. When checking "data.frames instanceof Array" when data.frames is an array declared in a different frame, the result is FALSE. The explanation relates to different execution environments in each frame. Here's what MDN says about it:

> **instanceof and multiple context (e.g. frames or windows)**
>
> Different scope have different execution environments. This means that they have different built-ins (different global object, different constructors, etc.). This may result in unexpected results. For instance, [] instanceof window.frames[0].Array will return false, because Array.prototype !== window.frames[0].Array and arrays inherit from the former. This may not make sense at first but when you start dealing with multiple frames or windows in your script and pass objects from one context to another via functions, this will be a valid and strong issue. For instance, you can securely check if a given object is in fact an Array using Array.isArray(myObj)
>
>*https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof[1]*

Changing the line I referenced above to the following makes it work correctly in my iframe:

```javascript
if (data.frames == null) {
   // nothing
} else if (Array.isArray(data.frames)) {
   // handle as array
} else {
   // handle as object
} 
```

Is there any problem with detecting the array using Array.isArray()? I'll admit i'm not sure if there are larger implications. What I do know is that the latter version is more compatible with multiple frames.

I have put together a full example illustrating the issue here: https://dl.dropboxusercontent.com/u/1549663/ArrayExample.zip

**Comment by gskinner** [comment]
Thanks for the report and pull request! Coincidentally, I was reading about this very topic a few days ago.

Any chance I could convince you to do a quick audit of EaselJS (basically a multi-file search for instanceof), and update your pull request with fixes where appropriate. I can definitely do this myself, but it would be great to have it all in one PR.

**Comment by jsaelhof** [comment]
For sure. I'll go through the lib and search for the instances...shouldn't be too hard. From your understanding, is it fairly safe to assume that "instanceof" and "Array.isArray()" are interchangeable (aside from the multi-frame case I found)?

**Comment by gskinner** [comment]
In my quick research, it appears that is the case, with the exception that isArray isn't supported in IE8 (but neither is canvas, so I think that's a non-issue at this point). We could always add a polyfill if need be.

**Comment by jsaelhof** [comment]
Well, I i just did a search of all files under "src" and apparently there are no other cases where instanceof is being used to check for an array. There are 9 other code usages but the are all checking other object types (Container, DisplayObject etc). Screenshot of results:

![Screenshot of Search Results](https://cloud.githubusercontent.com/assets/7939225/10349804/8f56a4c4-6cfd-11e5-83a2-c71bf5766972.png)

**Comment by gskinner** [comment]
OK. Thanks. The internal classes could potentially cause issues if someone were to pass display objects across a frame boundary, but that seems like a fairly unlikely case. We can always deal with it when/if it becomes an actual problem.

Do you mind me asking what the use case is for passing the array in from a parent frame? Handling loading for an app, and passing the spritesheet in to a dedicated display frame?

**Comment by jsaelhof** [comment]
Yeah, I wondered about those checks as well. There isn't an Array.isArray() alternative in those cases though. I supposed we'd have test those cases and see if they suffer the prototype inheritance issue. The MDN article I referenced only talks specifically about the Array object.

As for my use case, I'm building a gaming platform to run multiple games. It's a Nintendo/Cartridge type relationship. The platform page contains all the runtime code and display elements (menus, error screen, server communication etc) used by all games. The games are implemented inside an iframe so that they have their own sandboxed space (DOM etc). This way the games don't have to re-implement all the platform-level functionality and are quicker to build. One big aspect of that functionality is that the platform is responsible for preloading all it's assets as well as the game's assets. This is where the issue cropped up. Everything worked great until i tried to use a spritesheet in the game. The frame data is in a json file in the game but since it's preloaded by the platform, it is instantiated by using the platform's Array prototype. It's definitely a niche use-case. I tried an approach where the platform and the game shared the DOM but it was a bit ugly since either side ends up with direct access to the other's elements (For example, the game could empty the DOM and remove all the platform's display elements). Sandboxing with an iframe provided the type of separation of concerns I was looking for. This was all a lot cleaner with SWF's in Flash ;)

**Comment by Harbs** [comment]
FWIW, I believe that array.constructor.name=="Array" is a valid check that will work on all browsers.

**Comment by Harbs** [comment]
The constructor.name trick is something I've used in various contexts for a long time. I wonder what the performance is relative to isArray().

Another approach I just saw is:
Object.prototype.toString.call(arr) === '[object Array]'
but apparently this is really slow.

**Comment by lannymcnie** [comment]
JSPerf shows that isArray is the fastest - seems like the best approach. http://jsperf.com/isarray-vs-instanceof/7

**Comment by Harbs** [comment]
This is really weird, but I just created a jsperf test which seems to indicate that constructor.name is way faster than Array.isArray()
http://jsperf.com/isarray-vs-constructor-name

I wonder if I did something wrong.

**Comment by Harbs** [comment]
Follow up:
I'm not sure what the deal with Firefox is, but Array.isArray() seems really slow there.
Chrome has Array.isArray() as faster, while Safari is the other way around.

**Comment by Harbs** [comment]
Actually, it looks like it's .constructor.name is very fast on Firefox. It's so fast, it does not seem to make sense...

**Comment by jsaelhof** [comment]
Does array.constructor.name=="Array"work across frames (that was the initial problem)? I haven't had a moment to check yet. If no one knows I can find out.

**Comment by lannymcnie** [comment]
So other than Firefox's behaviour, the `Array.isArray(val)` seems like a performant, cross-frame solution that is clean and works. 

I have updated both SpriteSheet in EaselJS, and LoadQueue in PreloadJS with this change.
Thanks everyone for your feedback!

**Comment by Harbs** [comment]
Sure. For Easel that's probably fine because it does not support pre-IE9 anyway. For older browser support constructor.name==="Array" (strict comparison seems slightly faster than non-strict) seems like the most performant alternate.

I have not actually tested it across frames, I can not imagine that it does not work because the name of the constructor is always "Array" no matter which window owns the object. It would be nice to have actual confirmation though.
