### ISSUE TITLE
SoundJs no longer playing in stereo

### ISSUE THREAD

**Issue by ShaneSkuse** [CreateJS/EaselJS#674]
Sound doesn't seem to play in Stereo from Soundjs version 0.6.0 in chrome version 45.0.2454.101 m on widows 8.
HtmlAudioplugin does play in both speakers  but levels seem much lower.

**Comment by derz** [comment]
Thats already solved in a newer version of SoundJS, check here: https://github.com/CreateJS/SoundJS/issues/182

**Comment by ShaneSkuse** [comment]
Brilliant thanks
