### ISSUE TITLE
Framerate for sprite sheet animations seem to be disregarded when using a ticker update function

### ISSUE THREAD

**Issue by JasXSL** [CreateJS/EaselJS#675]
Is there a setting somewhere I'm missing?

Example 1:
createjs.Ticker.addEventListener("tick", stage);
Framerate is properly set to 4.
JS Fiddle: http://jsfiddle.net/o1joyju5/2/

Example 2:
createjs.Ticker.addEventListener("tick", function(){stage.update();});
Framerate is completely disregarded
JS Fiddle: http://jsfiddle.net/o1joyju5/3/

**Comment by lannymcnie** [comment]
This is an easy mistake I make all the time. The stage needs to know the `delta` from the tick, which is the time between ticks. This is propagated in the tick event. Your example is not passing the event into the `stage.update()`.

```js
createjs.Ticker.addEventListener("tick", function(event){
    stage.update(event);
});
```

I am leaving this open as a reminder to update the documentation to makes this clear.

**Comment by gskinner** [comment]
Where else would we doc it? We doc it in `Sprite.framerate`, `Stage.update()`, and a bunch of the examples. I guess the `Stage.update()` docs could put more emphasis on the reasons for it.

**Comment by JasXSL** [comment]
The ticker tutorial http://createjs.com/tutorials/Animation%20and%20Ticker/ doesn't mention it

**Comment by gskinner** [comment]
We could definitely add it there.

**Comment by lannymcnie** [comment]
Documented in the SpriteSheet overview, as well as the tutorial. I have pushed them to GitHub, but won't build new documentation for the site until we push out a new release of the source (which should be soon). Thanks for the suggestion.
