### ISSUE TITLE
Why this is happending?

### ISSUE THREAD

**Issue by andrewsilaghi** [CreateJS/EaselJS#679]
b_color.graphics
   .beginFill('#ff0000') //this color is rendered lighter.
   .drawRect(0, 0, w, h);
   background = new createjs.Container();
   background.addChild(b_color);
Just drawing a rectangle with the same size as canvas size from 0,0. The thing is that when I preview my canvas the color is not #ff0000 is #fb0006.

**Comment by sebastianderossi** [comment]
Looks fine to me. Have a look.
http://jsfiddle.net/sebastian_derossi/en2jsbom/1/
