### ISSUE TITLE
Shape.setBounds is ignored

### ISSUE THREAD

**Issue by ruslan-simonenko** [CreateJS/EaselJS#680]
Looks like shape bounds are completely ignored: http://jsfiddle.net/twdn1hfb/4/
Is there any way to specify which graphics part is required?

**Comment by lannymcnie** [comment]
What are you expecting the `setBounds` to do? The bounds of a shape are used when getting the bounding rectangle of a displayObject using `getBounds()`, and has nothing to do with display or hitArea.

**Comment by ruslan-simonenko** [comment]
I was expecting that it affects display area, however now I see that it can be done through `cache` method, closing.

**Comment by lannymcnie** [comment]
Also, you can use the Mask method (which uses a Shape instance), and for Bitmaps you can use `sourceRect`, which takes a Rectangle.
