### ISSUE TITLE
[Request] Implementing the strength parameter for filters

### ISSUE THREAD

**Issue by flashist** [CreateJS/EaselJS#683]
Hi,
I just have found that CreateJS ingnores the strength parameter of filters created in Flash CC 2015 =(

Here what I mean:
![Ignoring the strength parameter in Flash CC 2015](http://c2n.me/3pUVVP4.gif)

Please, could you tell me if it's possible to use this parameter?

**Comment by lannymcnie** [comment]
This is a known issue with the Blur filter in EaselJS.

**Comment by lannymcnie** [comment]
Sorry, my earlier comment was wrong. This is actually a canvas limitation, and not solvable with the current implementation, which relies on the canvas shadow property.
