### ISSUE TITLE
[Request] A way to change CreateJS publish scripts on your own

### ISSUE THREAD

**Issue by flashist** [CreateJS/EaselJS#684]
Hi,

Please, could somebody tell me if there is any chance to change CreateJS scripts for publishing from Flash CC 2015?

I was able to find the file "Publish for CreateJS.jsfl", which is located in "Common\Configuration\Publish\Canvas\jsfl", but if you try open it, you'll find that it's obfuscated or something like that, because it consists of strange characters and at the beginning of it we may find part of a phrase: MACROMEDIAOBFU. I guess it means that we can't read jsfl file, because it was obfuscated by Flash/CreateJS team.

I am asking about it because it looks like there are some features that might be fixed by developers themselves, without asking CreateJS about some features. And it definetely might imrpove workflow of people who try to work with CreateJS.

**Comment by lannymcnie** [comment]
While you can swap out the CreateJS libraries themselves with newer ones (which _should_ work, though there is no guarantee), there is no way to modify the export process. You could try asking adobe about this directly, but this isn't controlled by CreateJS.

https://forums.adobe.com/community/flash/flash_general
