### ISSUE TITLE
CORS issues is IE9

### ISSUE THREAD

**Issue by johncskelton** [CreateJS/EaselJS#686]
I get the following error when trying to load any images at all from an external server into my EaselJS code.

The images load perfectly when loading them from the same server but when I try to load them externally I get the following error ONLY in IE9. IE10/Firefox/Chrome all work fine. The CORS config for my S3 bucket is set up correctly. The images are all PNG files.

Does anyone know an effective way to fix this? I've been hitting my head against the wall all morning on this issue.

Is this a limitation of IE9?

**Comment by lannymcnie** [comment]
Do you have a sample? We can check this out.

**Comment by johncskelton** [comment]
Certainly. I have uploaded a simple test here -

http://sawmaxtest.com/sawmax/elearning/ele

arningimages/test/test.html.

Clicking on the images on that page in IE9 reproduces the error but does not occur in IE11/Chrome/Firefox etc.

You should be able to view the source code from that link but let me know if you can't see it.

Thanks,

John

**Comment by lannymcnie** [comment]
It looks like there are some limitations using XDomain requests with IE9 and below. There may be workarounds available, I am doing some research.

One note: the way you have defined the crossOrigin directly on your Bitmap instance is not necessary (and does nothing). The crossOrigin flag must be set directly on an image _before_ it is loaded (which PreloadJS does for you when you pass in the crossDomain argument).

**Comment by johncskelton** [comment]
This is possibly related to this issue in PreloadJS - http://stackoverflow.com/questions/33818340/preloadjs-working-version-for-ie9-and-ie11

**Comment by gskinner** [comment]
This is a PreloadJS issue. EaselJS loading is intentionally bare bones.
