### ISSUE TITLE
Propagate clicks on layered shapes

### ISSUE THREAD

**Issue by matteosimone** [CreateJS/EaselJS#687]
Hi,

I am not sure if this is possible and I have not been able to find anything in the documentation or on the web. I have multiple shapes that are overlaid on top of each other and I would like to trigger all of the click events when the top one is clicked.

As a simple example, I made this http://codepen.io/anon/pen/jbQaoq based on the bubbling demo page. When you click on the intersection between the red and blue circle, I want to fire both click handlers. The default behavior (which makes sense) is to fire the handler of the top element.

Is this possible?

**Comment by lannymcnie** [comment]
There is no way to handle this automatically, but you could use the `stage.getObjectsUnderPoint` API, and iterate the objects that are under the mouse position (which is what the click does).

**Comment by matteosimone** [comment]
Thanks for the quick reply @lannymcnie. 

In the docs, it says that getObjectsUnderPoint accounts for hitArea. However, in my example, it looks like I can only find the edges of the circles. I made a edited example to explain: http://codepen.io/anon/pen/QjJzoM

The green dots are where getObjectsUnderPoint found an object. I would expect a solid line through the circles as they have hit areas. When I draw the hit areas instead of the circles, I get what I want from the first example: http://codepen.io/anon/pen/zvMyXM.

**Comment by gskinner** [comment]
If you switch to the latest version of EaselJS (v0.8.1) this will work as you expect. I believe we added support for hitArea in getObjectsUnderPoint in v0.8.0.

**Comment by matteosimone** [comment]
Thanks. You might consider updating the script tags in most of the html files in https://github.com/CreateJS/EaselJS/tree/master/tutorials.

**Comment by lannymcnie** [comment]
Will do, thanks!
