### ISSUE TITLE
[Flash CC 2015] Bug during export images in different folders with the same name

### ISSUE THREAD

**Issue by flashist** [CreateJS/EaselJS#688]
An image worth a thousand words:
![And two images became the one](http://c2n.me/3qbPOwC.gif)

I guess it's a Flash CC bug.

**Comment by gskinner** [comment]
Interesting. Flash Pro should rename to 02_1.png or something similar. It does this for symbol and instance names, but it seems like that may not be getting applied for media items. I'll let Adobe know.

I'm sure you already know, but the workaround is just renaming one of the two images.
