### ISSUE TITLE
Add methods for modifying Graphics instructions

### ISSUE THREAD

**Issue by lannymcnie** [CreateJS/EaselJS#692]
It would be handy to have public APIs on Graphics to modify the Graphics instructions queue.

For example, when you clone a Shape, the instructions queue can be shared or cloned (using the recursive argument), however even when cloned, it will still share references to existing commands. This means if you save a command on a shape, and clone it, modifying the saved command affects both shapes:

``` js
var shape = new createjs.Shape();
var rectCommand = shape.graphics.beginFill("red").drawRect(0,0,100,100).command;

var shape2 = shape.clone(true);

rectCommand.w = 200; // Modify the width of the shape
```

I would expect this to just modify the first, but since the clone does not deep-copy the instructions, the command is shared between shapes.

Ideally, the recursive flag actually clones the instructions, but if not, an API could provide easy access to modify the instructions:

``` js
var rect2 = rectCommand.clone(); // Would be nice

var rect2 = new createjs.Graphics.Rect(0,0,200,200);
shape2.graphics.replace(rectCommand, rect2);

// OR

var index = shape2.graphics.indexOf(rectCommand);
shape2.graphics.splice(index, 1, [rect2]);
```

Totally open to implementation. Just some ideas.

**Comment by lannymcnie** [comment]
Similar to #654

**Comment by weltonrodrigo** [comment]
I stumbled upon the same requisite.
It's easy to append commands to the queue, but no public way to remove them.

A remove(command) would be awesome. Something in the fashion:

    shape.graphics.append(fillCmd);
    shape.graphics.append(strokeCmd);
    shape.graphics.append(rectCmd);
    shape.graphics.append(circleCmd);
    
    // later on, based on user interaction, one must remove the rectangle.
    shape.graphics.remove(rectCmd);    // life is easier now.

**Comment by lannymcnie** [comment]
How would that work if you added the same command multiple times?

**Comment by weltonrodrigo** [comment]
Now I see your point. A splice operation would be very nice.

**Comment by lannymcnie** [comment]
You can access the _instructions array (but it isn't recommended, since it could have unexpected results)

**Comment by Jezzamonn** [comment]
A quick work-around for this is to loop through the instructions and clone each one, like such:

```js
var shape = new createjs.Shape();
// ... drawing commands ...

var shapeClone = shape.clone(true);
// clone all the instructions
for (var i = 0; i < shapeClone.graphics.instructions.length; i ++) {
	var old = shapeClone.graphics.instructions[i];
	var newInstruction = new oldInstruction.constructor();
	Object.assign(newInstruction, oldInstruction);
	shapeClone.graphics.instructions[i] = newInstruction;
}
```

This could potentially be added to the graphics clone method. Not sure about browser compatibility though, might need some polyfill.

**Comment by gskinner** [comment]
There are two issues with adding arbitrary access to the command list:

1. There is a bunch of logic around when to inject / reset fills and stroke properties. This logic would break with arbitrary access.

2. We have plans to support bounds for Shape. This involves calculating the points in a Graphic object that comprise the convex hull. This is somewhat expensive to do. By only appending to the command list, we can retain the significan point list and only calculate against newly added points on-demand. This will also break if you edit existing commands, but that API is currently very constrained, and makes documenting how to address this simpler.

With that said, deep cloning is a separate ask, and something that I could see us adding. It's mostly a balance of library file size versus functionality. If deep cloning is something people think will provide significant benefit, then someone should open a separate issue for it (referencing this one), and we can evaluate it there.

Closing this, but feel free to comment further if you have questions or feedback.
