### ISSUE TITLE
The framerate is very slow on Safari 9.0.1 !!!

### ISSUE THREAD

**Issue by jkiss** [CreateJS/EaselJS#703]
when i test my example code, it's ok on chrome & firefox, but FPS is very slow when on Safari 9.0.1, below is code :
```javascript
    var stage = new createjs.Stage('demoCanvas');

    var t1 = new createjs.Text('Nokey', '20px Arial', '#ff7700');
    t1.x = 100;
    t1.y = 100;
    t1.textBaseline = 'alphabetic';
    t1.shadow = new createjs.Shadow('#000', 0, 0, 5);

    stage.addChild(t1);

    createjs.Ticker.addEventListener('tick', handleTick);
    // console.log(createjs.Ticker.framerate);
    function handleTick(event){
          if(t1.y > 330){
               t1.y = -20;
           }else{
                t1.y += 1;
           }

           stage.update();
     }
```

It's so weird!!!!!!!!!

**Comment by sebastianderossi** [comment]
Hmmm... seems fine to me. Have a look http://jsfiddle.net/sebastian_derossi/55z39ksq/1/
Tested on Safari 9.0.1 MacBookPro

**Comment by lannymcnie** [comment]
Note that shadow is quite expensive, as it runs on the CPU. I would recommend not using it if you can avoid it. You could put the text in a container, and cache it, which would reduce the CPU cost because the shadow is just drawn one time.

**Comment by jkiss** [comment]
My laptop is Macbook-12-inch. Could you test it on same device again?

**Comment by gskinner** [comment]
Tested on my Macbook Air 11", which should be less powerful than a MB12", and it runs fine. You're definitely running into some kind of glitch on your device if you're seeing performance problems. As Lanny mentioned, shadows are expensive, but you shouldn't see any slow down with the small use of shadows in this example.

**Comment by jkiss** [comment]
Sorry, guys, it's my fault. I haven't  shutdown my MB for a long time, and chrome opened a lot of tabs. It's ok after i restart...but only safari has this problem.
