### ISSUE TITLE
createjs.com home page display a blank page when using Ghostery addon

### ISSUE THREAD

**Issue by vinyll** [CreateJS/EaselJS#704]
CreateJS.com is ridiculously over dependant of typekit.net.

If typekit is down or blocked (like with the Ghostery addon/extension) the site displays a blank page.

Here is the log in the console (on chromium):

```
GET http://use.typekit.net/cek3iwo.js net::ERR_BLOCKED_BY_CLIENT
(index):2 Uncaught ReferenceError: Typekit is not defined
```

Adn the blank page (well, it's blank)
![screen shot 2015-12-09 at 2 28 09 am](https://cloud.githubusercontent.com/assets/145172/11673840/1c3c2b80-9e1c-11e5-9a1d-3b2ded68c603.png)

**Comment by lannymcnie** [comment]
Thanks, we are definitely looking at replacements :)

**Comment by lannymcnie** [comment]
I think this was solved ages ago when this bug surfaced. Checking before we close it.

**Comment by lannymcnie** [comment]
Yep it was solved. Thanks again for the report :)
