### ISSUE TITLE
eventlistener

### ISSUE THREAD

**Issue by aihaibo** [CreateJS/EaselJS#706]
if i used removeAllChildren method, the Eventlistener on the all children would be remove ?

**Comment by lannymcnie** [comment]
No, removing the children will just remove them from the display list.

**Comment by aihaibo** [comment]
Thank you, and how to delete an sprite completely (delete the eventlistener at the same time)?

**Comment by lannymcnie** [comment]
If you want to remove the event listener, use the EventDispatcher API:
```js
// Using EventDispatcher
displayObject.addEventListener("click", handleClick);
displayObject.removeEventListener("click", handleClick);

// Using the shorthand `on` method
var listener = displayObject.on("click", handleClick);
displayObject.off("click", listener);

// Remove all listeners
displayObject.removeAllEventListeners();
```

**Comment by aihaibo** [comment]
get it, and you said the removeAllChildren method is removing the children just from the display list. 
if i don't need a container later,  how can i completely delete it ?

**Comment by lannymcnie** [comment]
If there are no references to it, it will be garbage collected. When it is on stage, the stage has a reference to it. Once you remove it from the display list, and remove any listeners that it has, it should be free for GC.

**Comment by aihaibo** [comment]
I understand, thank you very much.
