### ISSUE TITLE
beginBitmapFill

### ISSUE THREAD

**Issue by aihaibo** [CreateJS/EaselJS#709]
If I want to use low poly triangle to combination a shape, but the shape will have some gap between the triangles, How can I avoid this problem?

``` javascript
for(i = 0; i < len; i++){
    shape.graphics.bf(img).mt(x1, y1).mt(x2, y2).mt(x3, y3).cp();
    container.addChild(shape);
}
```

![Image of demo](http://219.140.160.68:8011/temp_img.jpg)

**Comment by lannymcnie** [comment]
This is likely due to canvas antialiasing, and not likely something that can be fixed in EaselJS. The best solution is probably over-sizing the triangles, and overlapping them slightly. Sorry we can't do better...

Closing this for now.
