### ISSUE TITLE
Provide NPM package

### ISSUE THREAD

**Issue by legomind** [CreateJS/EaselJS#713]
It would make it very convenient for those of us using webpack or browserify

**Comment by vieron** [comment]
+1

**Comment by wittnl** [comment]
+1

**Comment by Diligentia-Uitgeverij** [comment]
This issue can be easily be avoided using [browserify-shim](https://www.npmjs.com/package/browserify-shim).

**Comment by wittnl** [comment]
Not as easy as `npm install easeljs` would be. Package management and build systems are related but distinct problems.

**Comment by legomind** [comment]
browserify-shim wont help webpack users.

**Comment by Diligentia-Uitgeverij** [comment]
I know it's not as easy, and that browserify-shim won't help webpack users. But it is a valid point for browserify users that are looking for a way to install, as long as there is no NPM-package.    
My comment was not made to talk down at anyone, just to help people find a way to pass the issue without having to wait on the team to add a package.

As for webpack users, webpack seems to have options to [import bower modules](https://webpack.github.io/docs/usage-with-bower.html), or to [shim packages](https://webpack.github.io/docs/shimming-modules.html) that are not correctly formatted.

I haven't used webpack myself, so I can't really help there, but seeing as there are options, I would imagine that this isn't the highest priority on the teams mind.

**Comment by jmeas** [comment]
Are the maintainers interested in providing an npm package? If so, I'm willing to help get things set up for publishing this on npm; I can make a PR for the package.json and/or provide guidance on npm best practices. Lmk if any of this could help get this issue closed out!

**Comment by iamkether** [comment]
This doesn't solve the fundamental problem of module importing in Webpack. However, I figured out a nice way to bypass this until a solution is presented by just "importing" the classes from the window global object. I put up a Gist which demonstrates this and also shows how to use it with ES6 syntax/ classes: https://gist.github.com/iamkether/752e381e03ddcb78f637

**Comment by gskinner** [comment]
Hi All - just wanted to pop in to let you know that this is one of our priority items for the next release. We have a plan in mind that we will run past you here in a bit, but we are very open to thoughts on specific implementation details.

**Comment by Robinfr** [comment]
Any update on this?

**Comment by fatlinesofcode** [comment]
unofficial package here, https://github.com/mattbalmer/createjs-collection

**Comment by Robinfr** [comment]
We have our own in-house package for creates that's not the point. I would like to have an official one.

**Comment by toverux** [comment]
For Webpack users, here is a "verbose", but fully-functional configuration:

Install EaselJS via Bower: `bower install --save EaselJS`

Install these Webpack loaders: `npm install --save-dev imports-loader exports-loader`

In your webpack.config.js, merge your config with:

```js
module.exports = {
    module: {
        loaders: [
            // That will tell Webpack that EaselJS refers to `window` with `this` and exports `window.createjs`.
            { test: /bower_components\/EaselJS\/.*\.js$/, loader: 'imports?this=>window!exports?window.createjs' }
        ]
    },

    plugins: [
        // This will tell Webpack how to find the main file of bower modules
        new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('.bower.json', ['main'])
        )
    ],

    resolve: {
        // Add bower_components as a modules root
        modulesDirectories: ['node_modules', 'bower_components']
    }
}
```

Now, if you use ES2015, you could do in your app:

```js
import { Stage } from 'EaselJS';

const stage = new Stage(canvas);
// enjoy!
```

**Comment by Entaro** [comment]
Hi,
toverux solution works fine.

**Comment by shennan** [comment]
Any movement on this? It's been 5 months...

Isn't it (for the moment) just a case of adding a simple `package.json`?

**Comment by lannymcnie** [comment]
Still on the horizon, but nothing expected immediately. Cheers.

**Comment by shennan** [comment]
@Diligentia-Uitgeverij was wondering if you could help me r.e using the browserify shim you mentioned earlier. I'm having trouble using it. Tried a number of things, but generally my `package.json` has this:

```
"browser": {
    "easel": "./src/vendor/easeljs-0.8.2.combined.js"
},
"browserify-shim": {
    "easel": "easel"
},
```

The resulting bundle does contain the EaselJS code, but I'm unable to `require` it in my JS files using `require('easel')`.

Running the browserify diagnostic reveals this:

```
{ file: 'example/src/script.js',
  info: 
   { package_json: 'example/package.json',
     packageDir: 'example',
     shim: undefined,
     exposeGlobals: {},
     browser: { easel: './src/vendor/easeljs-0.8.2.combined.js' },
     'browserify-shim': { easel: 'easel' },
  messages: 
   [ 'Found "easel" in browser field referencing "./src/vendor/easeljs-0.8.2.combined.js" and resolved it to "example/src/vendor/easeljs-0.8.2.combined.js"',
     { resolved: { 'example/src/vendor/easeljs-0.8.2.combined.js': { exports: 'easel', depends: undefined } } } ] }

{ file: 'example/src/vendor/easeljs-0.8.2.combined.js',
  info: 
   { package_json: 'example/package.json',
     packageDir: 'example',
     resolvedPreviously: true,
     shim: { exports: 'easel', depends: undefined },
     exposeGlobals: {},
     browser: { easel: './src/vendor/easeljs-0.8.2.combined.js' },
     'browserify-shim': { easel: 'easel' },
  messages: [] }
```

Perhaps I've misunderstood what the shim does, but it was my understanding that I could feed it a source file that hasn't been setup for CommonJS and then require it in my scripts?

**Comment by unematiii** [comment]
@shennan From my experience setting up `createjs-easeljs` with `npm` & `browserify`, your shim needs an `exports` argument:

```
  "browser": {
    "createjs": "./node_modules/createjs-easeljs/lib/easeljs-0.8.2.min.js",
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "createjs": {
      "exports": "createjs"
    }
  },
```

**Comment by StephanBijzitter** [comment]
Sigh...

**Comment by lannymcnie** [comment]
We have started an ES6 branch which will enable a lot of these things (RequireJS, CommonJS, npm, etc), which we hope to start posting publicly fairly soon, with an official release in Q1/Q2 of 2017

**Comment by achillesrasquinha** [comment]
Ah, waiting!

**Comment by blerchin** [comment]
Great to hear ES6 is coming soon!

In the meantime, I found a clean(er) way to import via webpack:
`npm i -DE createjs-easeljs`
add to `webpack.config.js`:
```
loaders: [
      ...
      {
        test: require.resolve('createjs-easeljs'),
        loader: 'imports?this=>window!exports?window.createjs'
      }
]
```

**Comment by RoosterKelly** [comment]
@lannymcnie I looked for an ES6 branch but could not find one, has it been merged already?

**Comment by lannymcnie** [comment]
@RoosterKelly Sorry, the ES6 branch is internal for now. Probably will get pushed to github in the new year.

**Comment by Draluy** [comment]
I'm also interested in a version directly usable with webpack.

**Comment by wittnl** [comment]
I've messed about with a lot of different ways in trying to make the CreateJS suite work in any module format and my analysis is that the latest stable (2015.11.26) can only ever be a global module. I've tried [`imports-loader`](https://github.com/webpack-contrib/imports-loader) which may work so long as your output target is truly [`"web"`](https://webpack.github.io/docs/configuration.html#target). This ended up not working for me in two different ways though: 

1) If you also need to use PreloadJS, you'll find that the embedded JSON3 library [will think it's in an AMD ecosystem](https://github.com/CreateJS/Combined/blob/master/builds/createjs-2015.11.26.combined.js#L13541) and therefore be undefined.
2) Because we're testing with Mocha & jsdom (a node environment) meaning the `this` CreateJS is expecting to be `window` is in fact `global`. I went way too far down a rabbit hole trying to make jsdom think it was a real browser and it just wasn't worth it.

### That said, here is how I've configured webpack to handle the global library

`$ npm install script-loader --save`
`$ npm install github:CreateJS/combined --save`

```
// entry.js

// Sucks but aliasing is not available here
import 'script-loader!CreateJS/builds/createjs-2015.11.26.combined.js';
```

Then any modules further down your dependency tree will have access to `createjs` as a global

```
console.log(createjs);
...
const { EaselJS, SoundJS, PreloadJS } = createjs;
...
```

**Comment by jabbowaki** [comment]
+1

**Comment by vogloblinsky** [comment]
+1

**Comment by abouthiroppy** [comment]
+1

**Comment by StefanRein** [comment]
+1

**Comment by limichange** [comment]
+1

**Comment by limichange** [comment]
Try it.
https://github.com/yuki-torii/yuki-createjs

**Comment by Draluy** [comment]
@limichange Just tried it and works like a charm. Thanks a lot !

**Comment by eskab** [comment]
You can try my solution for this: https://github.com/eskab/createjs-boilerplate. I'm using bower packages of library

**Comment by OUGHT** [comment]
+1. The lack of official npm package is the only thing that drives me out from this amazing engine.

**Comment by mpj** [comment]
+1 this, very weird that no npm package is provided.

**Comment by CaptainN** [comment]
It looks like there are two forks on this thread that implement the necessary package.json - can we just use one of those?

**Comment by CaptainN** [comment]
Actually I see that it would be even better to have proper support for ES6 imports - for example, it's not obvious how we would import the WebGL based StageGL (or even the older SpriteStage) in the current system (if I use bower, which I have done).

It'd be nicer to do something like:

`import {StageGL} from 'easeljs/StageGL'`

or whatever it would take to enable tree shaking. It would also be nice to avoid adding everything to a global object. That seems like a bit more work than just adding package.json.

Is there a planning document to get this done somewhere?

**Comment by RoosterKelly** [comment]
> We have started an ES6 branch which will enable a lot of these things (RequireJS, CommonJS, npm, etc), which we hope to start posting publicly fairly soon, with an official release in Q1/Q2 of 2017

@lannymcnie Well it is 10 days until the end of Q2, any update on the ES6 branch of CreateJS?

**Comment by yedaodao** [comment]
HI , you can try it https://www.npmjs.com/package/createjs-cmd

**Comment by yeluoqiuzhi** [comment]
+1

**Comment by zhe-he** [comment]
+1

**Comment by jivedesign** [comment]
+1

**Comment by gazpachu** [comment]
+1

**Comment by lannymcnie** [comment]
We have pushed npm support for the latest tagged version.

**Comment by wittnl** [comment]
@lannymcnie thanks for the update! I'm finding issues lining up the `main` entry point configured in package.json and the the actual result of `npm i easeljs` which is `./lib/easeljs.js`, but also noticed [`npmFilemap`](https://github.com/CreateJS/EaselJS/blob/master/package.json#L14) which looks new. Is there a minimum version of Node/NPM I need to be using? NPM 5.4.2 / Node 7.10.0 if so.

**Comment by lannymcnie** [comment]
For the current EaselJS build, there isn't support for importing directly -- just downloading - much like bower. We are working on full support for the next version, but are open to any workarounds anyone has used in the interim.

**Comment by patrickmesana** [comment]
it's a pain in the ass not being able to use easeljs the way you use 99% of other js libs out there...

**Comment by lannymcnie** [comment]
@patrickmesana We hear you. The next version of EaselJS (which will be *much* sooner than the last release cycle) will be ES6, and have full compatibility for NPM, RequireJS, CommonJS, etc. Sorry for the inconvenience in the mean time.

**Comment by jolaleye** [comment]
Progress report on NPM support? Just found the Create JS suite and I'm hoping to be able to use it like other js libraries soon. It seems like a great set of tools from what I've seen.

**Comment by lannymcnie** [comment]
There is a public branch of EaselJS 2.0, though its not published on npm just yet. We can look into a good approach to release it on NPM.

**Comment by lannymcnie** [comment]
My mistake: Looks like we already have an NPM package for 2.0
https://www.npmjs.com/package/@createjs/easeljs

Cheers,

**Comment by lannymcnie** [comment]
Thanks, we will publish an update shortly.

**Comment by josemadriz** [comment]
> HI , you can try it https://www.npmjs.com/package/createjs-cmd

Yedaodao, You nonchalantly saved my nuxt project setup, my hero!
