### ISSUE TITLE
Setting text of Text to number 0 nulls the getBounds()

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#718]
Perhaps we should not be assigning a number to the text property of a Text object... but the numbers show up and we usually get an expected result for getBounds() - except with the number 0

var t = new createjs.Text("hi");
stage.addChild(t);
t.text = 1; // or any other number but 0
console.log(t.getBounds()); // fine
t.text = 0;
console.log(t.getBounds()); // null
t.text = String(0);
console.log(t.getBounds()); // fine

**Comment by ph2-cst** [comment]
try to use latest version, There is no problem because I tried it

**Comment by wdamien** [comment]
@danzen, @ph2-cst is correct this is fixed in the latest version, see #550 for more information.
