### ISSUE TITLE
stage.updateViewport is not a function

### ISSUE THREAD

**Issue by jonaslund** [CreateJS/EaselJS#721]
When trying to update the viewport size by using the 
stage.updateViewport(800, 600); as defined in the api docs it generates this error
```stage.updateViewport is not a function```

**Comment by sebastianderossi** [comment]
Just to double check you are using **SpriteStage** and not "Stage" class.

**Comment by jonaslund** [comment]
I'm using this 
```var stage = new createjs.Stage("canvas"); ```

**Comment by sebastianderossi** [comment]
The `updateViewport` is a method of `SpriteStage` class.
