### ISSUE TITLE
Stroke width resets to 1

### ISSUE THREAD

**Issue by lannymcnie** [CreateJS/EaselJS#730]
This is from a bug mentioned on Google Groups:

A bug was introduced **after** 0.8.0 which makes Graphics ignore the strokestyle under some circumstances. I ported the drawing demo from EaselJS and was able to reproduce it:
1. create graphics up front
2. on mousedown, set the stroke style to a number larger than 1, and a color, and call moveTo+lineTo
3. on mousemove, do lineTos to draw

The behaviour changes if the approach changes:
- Under these circumstances, it will only draw single-pixel line, until you do a click without dragging, which it will inexplicably begin working.
- If the lineTo in the mousedown is removed, it will eventually fix if you click a whole bunch. I was unable to determine what changed.
- If the stroke and color are set initially, it will always draw a 1px line, no matter what.

I have attached a simple repro case.
[GraphicsBug.html.zip](https://github.com/CreateJS/EaselJS/files/126779/GraphicsBug.html.zip)

**Comment by ph2-cst** [comment]
I probably found the problem.
[Graphics._updateInstructions ](https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/display/Graphics.js#L1574)

because, this._commitIndex == 0, so instructions will be clear.
And then, strokeStyle isn't re-applied because it  hasn't changed.
```javascript
if (this._strokeStyle !== this._oldStrokeStyle) {
    this._oldStrokeStyle = this._strokeStyle;
    instr.push(this._strokeStyle);
}
```

**Comment by mattcolman** [comment]
Yep this is the guilty commit https://github.com/CreateJS/EaselJS/commit/8e9e31a7ca71880316e85b1d3e229323db34f183

**Comment by lannymcnie** [comment]
Thanks! We will take a look shortly, and get a fix up.

**Comment by Mr-ziqiang** [comment]
run this code ,the same bug.

`<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Graphics Bug</title>
</head>
<body style="background-color:#cccccc">
<canvas width="800" height="400" id="canvas" style="background-color:#fff"></canvas>

<script src="https://code.createjs.com/easeljs-0.8.2.min.js"></script>

<script>
    var canvas, stage, drawingCanvas;
    stage = new createjs.Stage("canvas");
    drawingCanvas = stage.addChild(new createjs.Shape());
    var g=drawingCanvas.graphics;

    g.setStrokeStyle(20, 'round', 'round').beginStroke("red");
    setInterval(function() {g.lineTo(Math.random() * 800, Math.random() * 400); stage.update() }, 1000);
    
</script>
</body>
</html>`

**Comment by Mr-ziqiang** [comment]
When I use the timer, it appeared the same bug.

`var canvas, stage, drawingCanvas;
    stage = new createjs.Stage("canvas");
    drawingCanvas = stage.addChild(new createjs.Shape());
    var g=drawingCanvas.graphics;

    g.setStrokeStyle(20, 'round', 'round').beginStroke("red");
    setInterval(function() {g.lineTo(Math.random() * 800, Math.random() * 400); stage.update() }, 1000);`

![11111](https://cloud.githubusercontent.com/assets/16486126/13178818/eb25e2ec-d75b-11e5-8601-34e239c9c2b1.jpg)


[bug.zip](https://github.com/CreateJS/EaselJS/files/138137/bug.zip)

**Comment by quentint** [comment]
Same issue here, any updates on this?

**Comment by jtylerroth** [comment]
Any update on this? Its causing very undesired behavior in my app. :(

**Comment by lannymcnie** [comment]
High on the priority list. Sorry for any inconvenience.

**Comment by seismicsix** [comment]
Hi,

Is there an update on this - has this been fixed yet - as I'm experiencing the same issue.

thanks

**Comment by gskinner** [comment]
I just pushed an update that should resolve this issue by only saving off `_oldStrokeStyle` on a commit. Please test and let me know if this resolves your issues, or introduces any new ones.

Closing for now, but please reopen as appropriate.

Thanks!

**Comment by danzen** [comment]
Thanks Grant - I was just having this problem and doing some research and got here.  I want to test but I don't really know how to use the "next" version or whatever without going and getting the other modules individually, etc.  I use a single min file from the CDN.  So... perhaps I will start a new issue and ask about this procedure - I have asked before but don't recall getting an answer.
