### ISSUE TITLE
Preload sprite frames

### ISSUE THREAD

**Issue by a3gis** [CreateJS/EaselJS#738]
Hello,

I am implementing an animation with a large number of frames, which cannot all be loaded for the animation to start. Basically, I would like to start the animation once X frames have been loaded, then if the last frame is reached before the next frames are available, display a "loading" indicator. 

I have managed to hack my way around this by using multiple sprites on the stage, and chain them (by listening to animationend, bring the next sprite forward, play, etc.). When a new chunk of frame has been loaded I add a new sprite, and so on.

I was wondering if it would be possible to do this on one sprite. I need to either be able to dynamically add frames/animations to a running sprite, or create a new one and hot-swap the running one while remaining at the same point in the animation.

Any advice would be welcome.

Thanks!

**Comment by lannymcnie** [comment]
Not likely to be something supported by EaselJS directly.
