### ISSUE TITLE
Using custom fonts in EaselJS using BitmapText

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#739]
BitmapText seems like a good way to go for in-game texts that pop up, but I'd like to avoid using the standard Arial, Times New Roman or whatever. I have some great license-free TTF fonts that I like to use in my games. Is there an easy way to convert those fonts into spritesheets for BitmapTexts?

Thanks
-Adam

**Comment by lannymcnie** [comment]
Not really. A custom tool would need to be made to convert the text to a SpriteSheet definition. Definitely could be useful, but not something EaselJS will likely support. Closing this for now.

**Comment by krazbobeans** [comment]
Well it's almost 1 year later here. Just to let you know I already created that tool about a week after I left this question. If someone wants to integrate it into EaselJS let me know. It works great so far for me.

**Comment by lannymcnie** [comment]
Feel free to share it :)
