### ISSUE TITLE
setBounds - when null is passed, bounds are set to an empty rectangle instead of null

### ISSUE THREAD

**Issue by ruslan-simonenko** [CreateJS/EaselJS#740]
When a new `DisplayObject` is created in EaselJS its bounds are set to `null`. The documentation of `setBounds` says: 

> Pass null to remove the manual bounds.

But it seems that once bounds are set manually it is impossible to revert them to the initial state, because when `null` is passed bounds are set to an empty rectangle instead of expected `null`:

```
var container = new createjs.Container(); 

var beforeBoundsSet = container.getBounds(); // null
container.setBounds(null);
var afterBoundsReset = container.getBounds(); // {x:0, y:0, width:0, height: 0}
```

Currently this makes it impossible to force `Container`'s bounds recalculation, once its bounds were changed manually (Not considering direct change of its `_bounds` property). 

[jsfiddle](https://jsfiddle.net/r99L55bo/1/)

**Comment by gskinner** [comment]
I fixed this a while back, but neglected to close this.
