### ISSUE TITLE
Differantiating between drag/drop and click

### ISSUE THREAD

**Issue by rsmd** [CreateJS/EaselJS#742]
I have a problem with mouse interactions. A shape that listens to pressmove, pressup and click always additionally fires a click event when beeing dragged and dropped or a drop event when beeing clicked.

```
s.on("mousedown", stopEventPropagation);
s.on("mouseup", stopEventPropagation);  
s.on("pressmove", handleDrag);  
s.on("pressup", handleDrop);  
s.on("click", handleClick);

function stopEventPropagation(e) {
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
}

function handleDrag(e) {
    stopEventPropagation(e);
    // move shape around
}

function handleDrop(e) {
    stopEventPropagation(e);
    // snap shape to nearest valid position
}

function handleClick(e) {
    e.stopPropagation(e);
    // rotate shape
}
```

Even though I stop propagation in all of those handlers click or drop events are still beeing fired as mentioned above. Can someone give me a pointer?

Thanks!

**Comment by lannymcnie** [comment]
You will receive a "click" event if you press and release the mouse on the same target. 

Cancelling or stopping the other events will not prevent the click event from occurring. Note that there is no "mouseup" event (use click or pressup). The event methods you are calling will not have an effect on *other* mouse events. ie, calling `stopPropagation()` on a "mousedown" event will only stop that event from bubbling to the parent display object. 

If you want to make an object no longer receive a click event once it has moved, you will have to build it yourself. I recommend setting a boolean flag on the object (`true` on mousedown), and then changing when the mouse moves (set to `false` on pressmove). You can then check that property on click, and stop it there if you want.

Hope that helps.

**Comment by rsmd** [comment]
Thank you for your fast and detailed answer. I really appreciate it.

**Comment by lannymcnie** [comment]
Happy to help!
