### ISSUE TITLE
Using custom font and Text caching will reset the font

### ISSUE THREAD

**Issue by pcoltau** [CreateJS/EaselJS#744]
I am using a custom font in my project, and I declare it in my style.css file using the "@font-face" keyword:

    @font-face {
        font-family: TerminalVector;
        src: url(font/TerminalVector.ttf);
    }

I create my Text in a function:

    function outTextXY(container, color, x, y, text) {
        var text = new createjs.Text(text, "12px TerminalVector", color);
        text.x = x;
        text.y = y;
        text.textBaseline = "hanging";
        text.scaleY = 0.80;
        var bounds = text.getBounds();
        text.cache(bounds.x, bounds.y, bounds.width, bounds.height);
        container.addChild(text);
    }

However, when I use caching on the Text as above, the font "TerminalVector" is not applied - the font will "reset" to some default font. If I remove the caching, the font is applied as expected. If I only apply caching to the parent container, the font is also "reset".

Is this a bug? And if so, is there a workaround for now? If it is not a bug, then what am I doing wrong?

**Comment by MannyC** [comment]
I would guess that the font file hasn't been loaded by the time the function is run, so it uses a font that it does have available.  The browser won't attempt to load the font files specified in CSS until they're actually used, and it won't pause the JavaScript while it does so.  You can do a search for workarounds, a common one is attaching the font to a small div to trigger the loading earlier.

**Comment by lannymcnie** [comment]
You could check out the FontLoader branch in PreloadJS, which has support for loading fonts a number of ways. https://github.com/CreateJS/PreloadJS/tree/FontLoader
