### ISSUE TITLE
DOMElement z-index

### ISSUE THREAD

**Issue by bernardbaker** [CreateJS/EaselJS#747]
When using a DOMElement for example at the following URL: https://www.google.com/doubleclick/studio/dynamic/tearsheet/#3db842bc-df03-40f2-9608-1182fec1f1a8

How is it possible to layer another canvas on top of the DOMElement?

So that in this working example the text will animate behind the content of the canvas layered on top of it.

For example:
1. Layer one contains a canvas with animations (z-index = 1)
2. Layer two contains DOMElements with text (z-index = 2)
3. Layer three contains a canvas with branding (z-index = 3).

In this case the text (DOMElement is always displayed on top of all content.

How can I layer the different pieces of content.

**Comment by lannymcnie** [comment]
You would need multiple canvases. DOM elements exist as siblings of the entire canvas, so can not be layered within content on the same canvas. You need to set up multiple stages (one per canvas). If you have mouse interaction on both, you can use the `nextStage` property to help propagate mouse events.
