### ISSUE TITLE
Incorrect documentation for Rectangle.pad

### ISSUE THREAD

**Issue by ruslan-simonenko** [CreateJS/EaselJS#751]
Currently `Rectangle` [documentation][1] says that `pad` method accepts next parameters: `(top, left, right, bottom)`, while [in fact][2] it accepts `p.pad = function(top, left, bottom, right)` - pay attention to the `bottom` and `right` positions. 

[1]: http://www.createjs.com/docs/easeljs/classes/Rectangle.html#method_pad
[2]: http://www.createjs.com/docs/easeljs/files/easeljs_geom_Rectangle.js.html#l151

**Comment by lannymcnie** [comment]
Great catch! I have made the fix and pushed it to GitHub.
