### ISSUE TITLE
tickEnabled is huge performance hog, what does it do?

### ISSUE THREAD

**Issue by griii2** [CreateJS/EaselJS#754]
What exactly is tickEnabled used for? I have couple thousand DOs in my canvas, mostly shapes, containers and texts. After playing with Chrome performance profiler I switched tickEnabled off for the whole stage and the performance of the scene increased by at least 60%. I do not use any Sprites, Movie Clips nor DOMElements and to my surprise everything else works as usual (visibility, animations etc). 

Shouldn't it be set to false by default same as MouseOver detection is?

**Comment by lannymcnie** [comment]
Container might be the offender. Containers must propagate ticks to all their children. If you want to prevent this, you can turn off `tickChildren` on containers, rather than using `tickEnabled` on all your shapes and text.

**Comment by griii2** [comment]
Shouldn't it be set to false by default same as MouseOver detection is?

**Comment by lannymcnie** [comment]
This would prevent MovieClips and SpriteSheets from advancing automatically. I think the behaviour is working as-designed. The tick overhead should be nominal.
