### ISSUE TITLE
setLineDash() error in IE10

### ISSUE THREAD

**Issue by FabioParigi** [CreateJS/EaselJS#757]
HI I have a big problem with IE10 in one of my application, in particular in consolle I receive this error
![cattura](https://cloud.githubusercontent.com/assets/5470284/14566335/7b367f0a-032f-11e6-9bad-6976a92cebcf.PNG)

For test it I found and try this jsfiddler example, in Crome work in IE10 same error
http://jsfiddle.net/z9pyfmxb/1/

can you help me?

thanks a lot
Fabio

**Comment by lannymcnie** [comment]
IE10 doesn't support line dash, so this might need to be considered in IE10. We will do some testing.

**Comment by lannymcnie** [comment]
IE10 does not support the `setLineDash` method, and the demo you posted has no check before calling it. If you want to use this code, you will have to do a check first. Note that there is no way to polyfill this in IE10 (and other older browsers) without a lot of work.

Here is a quick fix to that fiddle:

```js
(createjs.Graphics.SetLineDash = function(segments) {
  this.segments = segments;
}).prototype.exec = function(ctx) {
  if (ctx.setLineDash) {
    ctx.setLineDash(this.segments);
  }
};

(createjs.Graphics.SetDashOffset = function(offset) {
  this.offset = offset;
}).prototype.exec = function(ctx) {
  if (ctx.setLineDashOffset) {
	  ctx.lineDashOffset = this.offset;
  }
};
```

EaselJS 0.8.2 has lineDash support already, using `setStrokeDash([pattern], offset)` Here is an updated fiddle:
https://code.createjs.com/createjs-2015.11.26.combined.js

Again, this will not work in IE10, but doesn't throw any errors.
