### ISSUE TITLE
mouseenter event not working with stage objects

### ISSUE THREAD

**Issue by pathprabu** [CreateJS/EaselJS#761]
mouse enter event works with stage perfectly but  not  with the object  attached  to stage..
my code is ..

sprite.addEventListener("mouseenter", function() {  sprite.gotoAndPlay("run");   });

**Comment by lannymcnie** [comment]
The "mouseenter" event is just a Stage event, which indicates when the user first brings their mouse into the HTML canvas.
http://www.createjs.com/docs/easeljs/classes/Stage.html#event_mouseenter

For display objects, use either the "rollover" or "mouseover" events. 
http://www.createjs.com/docs/easeljs/classes/DisplayObject.html#event_rollover
