### ISSUE TITLE
Why does transformPoint take x,y params instead of a point?

### ISSUE THREAD

**Issue by jschatz1** [CreateJS/EaselJS#762]
I am using `matrix.transformPoint`. I noticed that the [AS3 matrix class](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix.html#transformPoint()) takes a `Point` as the param, and your class takes `x`,`y`. Any reason for this? I thought you were trying to follow the AS3 classes as close as possible.

**Comment by lannymcnie** [comment]
EaselJS loosely followed Flash/AS3 patterns to begin with, however over time it has become its own library, and there is no mandate to keep it consistent. 

The point parameter in transform point provides a way to reuse point objects, rather than creating new ones constantly.

**Comment by jschatz1** [comment]
@lannymcnie Thanks for the explanation. A sound design decision.
