### ISSUE TITLE
Matrix2D rotate tx, ty was removed. On purpose?

### ISSUE THREAD

**Issue by jschatz1** [CreateJS/EaselJS#765]
According to this commit https://github.com/CreateJS/EaselJS/commit/3ed3b894d5e53c07869c4a7f0ca405f3ee583f15#diff-390a4d9b135bba80029aef8b5eb7ca4dR347 

You removed the `tx` and `ty` variables of the matrix2D. I believe it was an error because you need those for `rotate` to work properly.

**Comment by MannyC** [comment]
They aren't gone from Matrix2D.  It looks like rotate changed from an appended rotation to a prepended rotation

**Comment by jschatz1** [comment]
@MannyC Again thanks! That answers my question.
