### ISSUE TITLE
Matrix2d translate not accurate

### ISSUE THREAD

**Issue by jschatz1** [CreateJS/EaselJS#766]
Aside from the fact that your `Matrix2D` method does not currently work in `master` because it is missing `tx` and `ty`. If you put `tx` and `ty` back in using the code before it was removed it works great. However I noticed that `Matrix2D.translate` is not accurate. At least not with AS3.

Take the following JS code

```
var m = new createjs.Matrix2D();
m.identity();
m.translate(150,65);
m.rotate(45) // in degrees
m.translate(319, 79.07611844574882);
console.log(m.tx,m.ty)
```  

And the equivalent AS3 code: 

```
package {
    import flash.text.TextField;
    import flash.geom.Matrix;
    import flash.display.Sprite;
    public class FlashTest extends Sprite {
        public function FlashTest() {
            var m:Matrix = new Matrix();
            m.identity();
            m.translate(150,65);
            m.rotate(0.785398) // in radians
            m.translate(319, 79.07611844574882);
            var t:TextField = new TextField();
            t.text = m.tx + " " + m.ty;
            t.width = 2000;
            addChild(t)
        }
    }
}
```

Both are logging the `tx` and `ty` of the matrix after a translation a rotate and a translation again. 

Flash gives: 

`tx=379.4178764008566, ty=231.5402764008565`

EaselJS gives:

`tx=319.651803615609, ty=346.48232278140824`

These are not the same. But if you trace the first translate you get the same answer. Trace the rotate you get the same answer. Trace the second translate you get a different answer.  So it has something to do with calling translate a second time for some reason. Unless the AS3 libs are wrong. Or I am using it incorrectly.

**Comment by MannyC** [comment]
This is somewhat similar to the other issue, as it has to do with appending vs prepending.  

`var m = new createjs.Matrix2D();
m.identity();
m.translate(150,65);
m.prependTransform(0,0,1,1,45) // in degrees
m.prependTransform(319, 79.07611844574882,1,1);
console.log(m.tx,m.ty)`

gives

`379.10407640085657 231.1040764008565`

**Comment by jschatz1** [comment]
@MannyC Thank you. That answers my question.
