### ISSUE TITLE
CreateJS with TypeScript?

### ISSUE THREAD

**Issue by gmattie** [CreateJS/EaselJS#767]
Are there plans to implement TypeScript with CreateJS like Angular 2 has done?

**Comment by FabioParigi** [comment]
No news?

**Comment by lannymcnie** [comment]
Yes!

Sorry for the delayed response. When this was posted, the answer was "maybe someday", and then the question got lost in the pile.

At the very least we will support TypeScript by maintaining and updating the DefinitelyTyped definitions, which to date we have not been involved with before, and are somewhat out of date. 

We are also supporting ES6 in a future release (not the immediate next release, but sometime after). We have already begun an internal branch, and will share it publicly in the new year.  We are still evaluating if we want to actually code the source in TypeScript.

Cheers.

**Comment by adamhughes86** [comment]
Is there any update on this? I'm having difficulty getting EaselJS into an Angular2 project as a module

**Comment by Taewa** [comment]
Same here

**Comment by lannymcnie** [comment]
We have internal builds of EaselJS and TweenJS that are almost ready for public preview. We are wrapping up some EaselJS/StageGL/Filter enhancements in the current version first. The new version has a lot of different requirements, as well as a completely new build and documentation process, and sets the standard for other libraries, so we are trying to wrap that up before a release.
