### ISSUE TITLE
shadow disappears when rotation is applied to displayobject

### ISSUE THREAD

**Issue by siims** [CreateJS/EaselJS#768]
After updating chrome from version 48 to version 51 (also tested on 52) we are having an issue with shadow. Namely, it disappears when rotation is applied and reappears when DisplayObject is rotated to its original rotation. I checked DisplayObject in rotated state and it had shadow defined, but for some reason shadow is not visible.

Firefox behaves correctly, I haven't tested it on other browsers.

See example: https://jsfiddle.net/siims/khv7tdzm/

All help and hints are appreciated in solving this issue.

**Comment by lannymcnie** [comment]
Good catch. Will have a look.

**Comment by fonograph** [comment]
I believe this is a bug with Chrome: http://stackoverflow.com/questions/36726694/html-canvas-shadowblur-not-working-after-rotating

**Comment by lannymcnie** [comment]
Looks like this is solved? Since it isn't an EaselJS bug (Chrome issue) I am closing it.
