### ISSUE TITLE
How is the non-minified source code compressed?

### ISSUE THREAD

**Issue by griii2** [CreateJS/EaselJS#775]
First of all let me say you did an amazing job, IMHO CreateJS is the best HTML5 Canvas drawing library out there.

How is the combined but non-minified source code (for instance https://github.com/CreateJS/EaselJS/blob/master/lib/easeljs-0.8.2.combined.js) compressed? 

(I would like to build a copy of combined but uncompressed and code so that I can dive deeper and learn how CreateJS works.)

**Comment by sebastianderossi** [comment]
Have you looked at CreateJS [CDN page](http://code.createjs.com/)?
You'll find a combined, non-minified version of CreateJS libs [here](https://code.createjs.com/createjs-2015.11.26.combined.js)

**Comment by MannyC** [comment]
Are you asking how is the combined file created?  If so, check the build folder

**Comment by griii2** [comment]
Awesome, thanks. By the way, any plans to rewrite createJS into TypeScript?

**Comment by gskinner** [comment]
Our current plan is to rewrite to ES2016 and possibly have official TS declaration files. We are currently evaluating performance of both raw ES6 and transpired output. We don't want to take a major hit in the rewrite.
