### ISSUE TITLE
EventDispatcher useCapture issue

### ISSUE THREAD

**Issue by KIWI-JP** [CreateJS/EaselJS#777]
When the target EventDispatcher has useCapture set to true, the handler function does not get called. For example, on the code below `cb2` should get called when clicking on `child`, but it doesn't.

```
parent.addEventListener("click", cb1, true);
child.addEventListener("click", cb2, true);
```

In the code, when adding an event listener to a EventDispatcher object using the `useCapture` parameter set to true, the listener gets added to `this._captureListeners`. This is the correct/expected behavior.

```
p.addEventListener = function(type, listener, useCapture) {
    var listeners;
    if (useCapture) {
        listeners = this._captureListeners = this._captureListeners||{};
    } else {
        listeners = this._listeners = this._listeners||{};
    }
    var arr = listeners[type];
    if (arr) { this.removeEventListener(type, listener, useCapture); }
    arr = listeners[type]; // remove may have deleted the array
    if (!arr) { listeners[type] = [listener];  }
    else { arr.push(listener); }
    return listener;
}
```

Later, when calling "_dispatchEvent" from "dispatchEvent" with the target, the code passes `eventPhase` 2 (target phase). This is the correct/expected behavior.

```
p.dispatchEvent = function(eventObj, bubbles, cancelable) {
    ...
    var top=this, list=[top];
    while (top.parent) { list.push(top = top.parent); }
    var i, l=list.length;

    // capture & atTarget
    for (i=l-1; i>=0 && !eventObj.propagationStopped; i--) {
        list[i]._dispatchEvent(eventObj, 1+(i==0));
    }
    ...
}
```

However, "_dispatchEvent" only processes `this._captureListeners` if the `eventPhase` is 1 (capture phase). So when the `eventPhase` is 2 (target phase), it does not select `this._captureListeners`, which is where the target EventDispatcher was added. This is **not** the correct/expected behavior.

```
p._dispatchEvent = function(eventObj, eventPhase) {
    var l, listeners = (eventPhase==1) ? this._captureListeners : this._listeners;
    ...
}
```

If eventPhase is 2 (target phase), "_dispatchEvent" should set listeners as the union of `this._captureListeners` and `this._listeners`.

**Comment by gskinner** [comment]
I just pushed a fix for this. I know it's been a while, but feel free to test and provide feedback.
