### ISSUE TITLE
Is it possible to add a BlurFilter to a line?

### ISSUE THREAD

**Issue by itsmoops** [CreateJS/EaselJS#782]
I'm attempting to add a blur effect to a single line. I've been following the BlurFilter demo in the docs (except that they are using a circle instead of a line). My shape disappears completely unless I remove the shape.cache call. Is this possible with a line or is blur limited to specific shapes?

`function drawShape() {
  var shape = new createjs.Shape();
  shape.graphics.setStrokeStyle(10, "round")
  .beginStroke(colorPalette.shape[0])
  .beginFill(colorPalette.shape[0])
  .moveTo(200,400)
  .lineTo(1500,400);
  shape.cursor = "pointer";

  var blurFilter = new createjs.BlurFilter(50, 50, 1);
  shape.filters = [blurFilter];
  var bounds = blurFilter.getBounds();
  shape.cache(-50+bounds.x, -50+bounds.y, 100+bounds.width, 100+bounds.height); // Code works if I remove this line

  updateStage(shape); // Utility function that calls addChild and update on stage
}`

**Comment by lannymcnie** [comment]
Answered this here: http://stackoverflow.com/questions/38173637/easeljs-is-it-possible-to-add-a-blurfilter-to-a-line/38188295#38188295
