### ISSUE TITLE
beginBitmapFill not working correctly with no-repeat

### ISSUE THREAD

**Issue by Davide95** [CreateJS/EaselJS#786]
Sorry for my bad English but I'm not native.
I've a web app written with EaselJS. I've a canvas in witch I've to move an image. When I use beginBitmapFill with repeat all works smootly, but if I use no-repeat it happens a small glitch.

The code:
```javascript
var matrix = new createjs.Matrix2D();
matrix.tx = (background.x % (PIECE_SIZE+1));
matrix.ty = (background.y % (PIECE_SIZE+1));

background.shape.graphics.clear();
background.shape.graphics.beginStroke('white')
   .beginFill('white')
   .beginBitmapFill(lastBackgroundImg, 'no-repeat', matrix)
   .drawPolyStar(PIECE_SIZE/2, PIECE_SIZE/2, PIECE_SIZE/2 - FRAME_BORDER_SIZE, 8, 0, 0)
   .endStroke();
stage.update();
```

An image that shows the problem.
![bug](https://cloud.githubusercontent.com/assets/10170507/17209350/e6e7bcda-54bc-11e6-8afe-d07e0c906eac.png)

**Comment by lannymcnie** [comment]
Unfortunately, this is an issue with the browser/Canvas, and not something we can solve in EaselJS.

Here is a sample with raw canvas APIs.
http://jsfiddle.net/4vp21mr7/1/

**Comment by Davide95** [comment]
First of all, thank you:)
Is there a workaraound to fix this issue?
