### ISSUE TITLE
EaselJSRenderers needs update?

### ISSUE THREAD

**Issue by gregmax17** [CreateJS/EaselJS#787]
I was looking at this: https://github.com/CreateJS/EaselJSRenderers and noticed that it doesn't work with the current build of EaselJS. 

Can this be updated? 

PS - I'm curious if there will be any performance boost with 'Renderer2DMtx'
PSS - Why use "next" as a version? "next" from what year? Please just keep versions a number ;)

**Comment by lannymcnie** [comment]
The Renderers are out of date, and will not be updated, as we are deprecating SpriteStage/SpriteContainer in favour of the new (and way better) StageGL approach, which is currently available in the [StageGL-beta branch](https://github.com/CreateJS/EaselJS/tree/StageGL-beta) in GitHub.

As for the naming, the NEXT name refers to "what is currently in GitHub" between official releases (ie, the next release). This provides a minified version with the latest features until they become official and are put on the CreateJS CDN. 

I am closing this for now.
