### ISSUE TITLE
Question about "examples/SpriteSheetBuilderMC/gunnertron_g.js" codes, help!

### ISSUE THREAD

**Issue by jkiss** [CreateJS/EaselJS#791]
Hi guys:

when i see example of SpriteSheetBuilderMC, i notice that code below:

```javascript
(lib.gunarm = function() {
	this.initialize();
	...
}).prototype = p = new cjs.Container();
```

I really want to know ***this.initialize();*** inherit from where? what it is function? **How it works?**

Thx!!!

**Comment by MannyC** [comment]
It's set in Container that the above code is using as a prototype ( set here: https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/display/Container.js#L127 ).  

However, it looks like that example hasn't been updated after the they updated the inheritance mechanism a couple of versions ago.  You should instead follow the guidelines here: http://www.createjs.com/tutorials/Inheritance/

**Comment by jkiss** [comment]
Yeah, I really need some **new** examples for me as a newcomer! Thx again!
