### ISSUE TITLE
After double click on bitmap/canvas pressup event not working 

### ISSUE THREAD

**Issue by mamallana** [CreateJS/EaselJS#799]
Hi,

After double clicking on the bitmap/canvas, if we try to move the bitmap (pressmove) and drop the bitmap image(pressup) its not working, please someone assist on remove the double click event to solve this issue.

**Comment by lannymcnie** [comment]
Can you clarify what is happening, and maybe post some code? I can not reproduce this.
Here is a quick spike: http://jsfiddle.net/lannymcnie/ne4hp1c8/

**Comment by mamallana** [comment]
@lannymcnie  Thanks for the response, 

I have a frame(shape) and inside there are some circles(bitmap), so while clicking the bitmap(select) i will update the bitmap image to another one, which will have the hover effect, then i will move(pressmove) and drop (pressup) out of the frame. if do the single click to select then i can able to move and drop out of the frame. But in case if i do double click to select the bitmap image then i can't move and drop(pressup) out of the frame, please find the attached screenshot for the same.

Sample code: 

object.on('click',function(){
   var icon = new createjs.Bitmap('images/circle_hover.png');
   object.image = icon.image;
   object.on("pressmove", function (evt) {
     frame.removeChild(this);
     stage.addChild(this);
   }
   object.on("pressup", function (evt) {
   
   }   
})
 
![bitmap](https://cloud.githubusercontent.com/assets/13505185/18700516/506cc750-7ff5-11e6-9a92-1fb27335b527.png)

**Comment by mamallana** [comment]
Double click issue go resolved by adding the below code,

var canvas = document.getElementById('canvas');
canvas.onselectstart = function () { return false; }

**Comment by lannymcnie** [comment]
This should be taken care of by the `Stage.preventSelection` property.
http://createjs.com/docs/easeljs/classes/Stage.html#property_preventSelection

**Comment by mamallana** [comment]
I will this... thank you @lannymcnie
