### ISSUE TITLE
Auto-refresh Bounds after setBounds()

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#800]
Once we setBounds() it would be nice to have a way at a later time to stop using the set bounds and go back to automatic bounds calculation.  Maybe a clearSetBounds() which then sees if the bounds can be calculated and if so calculates, and if not then sets the bounds to null and proceeds as if they have never been set.  Cheers!

**Comment by MannyC** [comment]
You can pass `null` to the `setBounds` method.   See the docs for the first parameter.

**Comment by danzen** [comment]
Thanks for the quick response - that makes sense.

**Comment by danzen** [comment]
Hmmm... just trying this out and I can't seem to get it to work.  I am getting 0 width after setting bounds to null.  It does not seem to matter if I move the c.addChild(r) around - and a delay did not help either.  If I do not set the bounds of c at all then the width does calculate correctly to 100.

```
var r = new createjs.Shape();
r.graphics.f("black").dr(0,0,100,100);
r.setBounds(0,0,100,100);

var c = new createjs.Container();
stage.addChild(c);
c.setBounds(0,0,10,10);
c.setBounds(null);
c.addChild(r);
// setTimeout(function() {
console.log(c.getBounds().width); // 0 - but should be 100
//}, 1000); // still 0
```

**Comment by gskinner** [comment]
Looks like we are missing a return statement in setBounds(). Easy fix - it will be in the next release.

````
if (x == null) { this._bounds = x; return; }
````

**Comment by danzen** [comment]
Not sure - it seems this one did not get in the new versions 1.0?  I am getting a width of 0 for a container with setBounds(null);  Even if there is something in the container with the bounds set.  I tried re-adding the object with bounds to the container but still get 0 for the container bounds.

**Comment by gskinner** [comment]
Hmm. The fix I mentioned above is definitely in place. Any chance you could toss a quick codepen or jsfiddle together and I'll take a look?

**Comment by danzen** [comment]
Ah - my fault - thought I was in a new file but was remaking some gesture work to act around pinch points when I tested this - and indeed, the CreateJS was an old one.  So sorry - yes it is working and glad it is working ;-)

**Comment by danzen** [comment]
Hey folks, Adobe Animate is using https://code.createjs.com/createjs-2015.11.26.min.js and this bug is still in that version.  So just founds a solution to reset the bounds based on Grant's internal fix.  If you set myObject._bounds = null; it does what myObject.setBounds(); should do and does do in newer versions of CreateJS.  Whew.
