### ISSUE TITLE
Doc for MovieClip might need updating?

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#801]
On the blog you mention that the MovieClip is included in Easel: 

> one important update: The EaselJS minified file(s) now include the MovieClip class

But then in the MovieClip docs it still says:

> Due to the complexities inherent in correctly setting up a MovieClip, it is largely intended for tool output and is not included in the main EaselJS library.

**Comment by lannymcnie** [comment]
Fixed description in the class file. Thanks!
