### ISSUE TITLE
Docs - SpriteSheet missing "Zoe" perhaps?

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#803]
http://www.createjs.com/docs/easeljs/classes/SpriteSheet.html
down in the "Generating SpriteSheet Images" area you have:
SWF animations in Flash can be exported to SpriteSheets using 
And then nothing...

**Comment by lannymcnie** [comment]
Good catch, there is an empty A tag :) It should be "Zoë" http://createjs.com/zoe

**Comment by lannymcnie** [comment]
Pushed a fix to the SpriteSheet class. New docs zip and site update will be done at a later date.
