### ISSUE TITLE
Text in recent Firefox Browsers not adjusting alpha

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#808]
This worked as of Firefox 47 but on my 49 and nightly 51 it is not showing the alpha change.
Not sure about Firefox 48.  And only tried on my one PC Win 10 for 49 and 51.  Works on other browsers (Chrome, Edge)  It is late and I am a little brain dead - but... worth a verification.  I noticed when I could not seem to animate text - and then when I was animating a container with text - everything but the text fades in and out.  The text just stays at alpha = 1.
```
var text = new createjs.Text("ouch");
text.scaleX = text.scaleY = 5;
stage.addChild(text);
text.alpha = .2;
stage.update();
```

**Comment by danzen** [comment]
Just restarted my machine to make sure and still broken.  This works: var text = new createjs.Text("Hello World", "70px Arial", "rgba(0,0,0,.1)");  but when I set the font to "black" and then use text.alpha = .1; and update the stage, the text is still alpha 1.  When I look back on a few projects I have done with alpha'd text, they are not showing the alpha.  For instance, all the ZIM Bits eg. http://zimjs.com/code/bits/view/drag.html - the buttons at the bottom are faded out but the text is not faded.

**Comment by lannymcnie** [comment]
Wow, that is nuts. Looks like Mozilla broke the API, and the bug is not in EaselJS. 

Here is a fiddle with plain context APIs: http://jsfiddle.net/fupaqw26/1/

**Comment by lannymcnie** [comment]
https://www.fxsitecompat.com/en-CA/docs/2016/specific-canvas-text-effects-are-not-rendered-properly/

**Comment by danzen** [comment]
whew!
