### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by ndevr** [CreateJS/EaselJS#809]

**Comment by lannymcnie** [comment]
Absolutely. A new WebGL (beta) implementation was published to the StageGL-beta branch a few weeks ago which offers massive improvements to performance. We are also internally working on an ES6 port, a refactor of TweenJS, and evaluating the roadmap for the other libraries. 

Unfortunately our internal production often keeps our team busy, but we have lots of plans to continue development over the next few months, and hope we can get a new release out in that time.

Cheers.

**Comment by SenthilKumaranC** [comment]
Project still active?

**Comment by SenthilKumaranC** [comment]
Shall we use Flash IDE to generate HTML5 Canvas UI using this library?

**Comment by danzen** [comment]
Hi @SenthilKumaranC - you can use Flash to create a Canvas UI - or you can use the library directly - that is what we did at https://zimjs.com - you might want to click the UI/UX banner to see examples of what can be made - you are welcome to use these to save some time.  If you are using Adobe Animate - then also check the ZIM SHIM which lets you bring the components into Animate as you code with CreateJS there.  Cheers - let us know if you have any questions - there is an unofficial Facebook group at https://www.facebook.com/groups/createjs and we talk about CreateJS and ZIM at https://zimjs.com/slack - you may find other communities too... these are the ones I am involved in.
