### ISSUE TITLE
Overriden draw() throws exception when adding children to extended Container

### ISSUE THREAD

**Issue by ppisecky** [CreateJS/EaselJS#810]
I am having trouble with extending the Container class functionality and overriding the draw method.
I wrote two classes:
1. Entity - inherits from Container
2. Tank - inherits from Entity

```
/**
 * Entity
 * @type {Container}
 */
function Entity(x,y){
    this.Container_constructor();
    this.x = Math.round(x);
    this.y = Math.round(y);
    this.rotation = 0;
}
createjs.extend(Entity, createjs.Container);
createjs.promote(Entity, "Container");

/**
 * Tank
 * @type {Entity}
 */
Tank.prototype = new Entity();
Tank.prototype.constructor = Tank;
Tank.prototype._super_ = Entity.prototype;
function Tank(x,y){
    this._super_.constructor.apply(this, arguments);
    this.bodyWidth = 40;
    this.bodyHeight = 65;
    this.regX = Math.round(this.bodyWidth/2);
    this.regY = Math.round(this.bodyHeight/2);
    this.tankBody = new createjs.Shape();
    this.tankBody.graphics.beginFill('#ecf0f1').drawRect(0,0,this.bodyWidth,this.bodyHeight);
    this.addChild(this.tankBody);
}
```

Ok that works. But if you follow the [docs ](http://www.createjs.com/tutorials/Inheritance/)and do something like this between the _extend_ and _promote_ calls:
`Entity.prototype.draw = function(){
    this.Container_draw();
}`

Then adding children and trying to update the stage will throw:
**Cannot read property save of undefined.**

Maybe I did something wrong but I am not quite sure what. Fortunately - I don't need this functionality atm so I'm just letting you guys know.

**Comment by lannymcnie** [comment]
The `draw` method of Container takes 2 parameters, one of which is the canvas context. When the context is modified, the `save` and `restore` methods are invoked. Your example does not handle or pass those parameters properly, resulting in the error you described.

Here is the draw method signature:

```js
p.draw = function(ctx, ignoreCache) {}
```

Your method should read:

```js
Entity.prototype.draw = function(ctx, ignoreCache){ this.Container_draw(ctx, ignoreCache); }
```

Cheers.

**Comment by ppisecky** [comment]
Thanks for the fast response. The `draw` method implementation I provided was from the [inheritance tutorial](http://www.createjs.com/tutorials/Inheritance/). I knew something was wrong with it but since I had no use for an overriden version I didn't look for the cause. I just wanted to let you guys know that maybe you should consider changing the tutorial as it might confuse others as well.

**Comment by lannymcnie** [comment]
I pushed up a change to GitHub. We will update the site at a later date. Thanks!

**Comment by ppisecky** [comment]
No problem. Cheers.
