### ISSUE TITLE
Documentation - compositionOperation further reading link broken

### ISSUE THREAD

**Issue by pdkn** [CreateJS/EaselJS#811]
Hi guys,

Ickle thing - Noticed the link for more info about compositionOperation is now broken
http://createjs.com/docs/easeljs/classes/DisplayObject.html#property_compositeOperation
links to: https://html.spec.whatwg.org/multipage/the-canvas-element.html#compositing

over and out ;)

**Comment by lannymcnie** [comment]
Thanks for the report. I updated the links, and added another to the composite operation and blending draft (https://drafts.fxtf.org/compositing/).

A fix for this has been pushed to GitHub, and the site will be updated at a later date.
Cheers,
