### ISSUE TITLE
SpriteContainer alpha is not applied to its children

### ISSUE THREAD

**Issue by ferrym4n** [CreateJS/EaselJS#812]
Setting the alpha value for SpriteContainer does not update its appearance. Setting 0 will make it invisible any positive value is same as setting 1.

Example: http://jsfiddle.net/sd0fa1qa/
Left sprite has container with alpha=1, right sprite has container with alpha=0.1 and yet apperance is the same. Setting alpha value for the actual sprite works as expected.

**Comment by ferrym4n** [comment]
Found the bug. SpriteContainer alpha is completely ignored in _drawWebGLKids and only child alpha is used. Since BitmapText is also in essence a sprite container in disguise this applies to it as well.

Here is my fix to webgl-0.8.2 for others stumbling to this same problem. I'm too busy at the moment to test this further and make a pull request.

@@ -975,7 +975,8 @@ this.createjs = this.createjs||{};
                        vertices = this._vertices,
                        numVertexPropertiesPerBox = SpriteStage.NUM_VERTEX_PROPERTIES_PER_BOX,
                        maxIndexSize = SpriteStage.MAX_INDEX_SIZE,
-                       maxBoxIndex = this._maxBoxesPerDraw - 1;
+                       maxBoxIndex = this._maxBoxesPerDraw - 1,
+                       alphaFactor = 1;

@@ -1030,6 +1031,13 @@ this.createjs = this.createjs||{};
                                this._drawTexture = texture;
                        }

+                       if (kid.parent != null &&
+                           (kid.parent._spritestage_compatibility === 1 || kid.parent._spritestage_compatibility === 3)) {
+                           alphaFactor = kid.parent.alpha;
+                       } else {
+                               alphaFactor = 1;
+                       }
+

@@ -1063,7 +1071,7 @@ this.createjs = this.createjs||{};
                                vertices[offset + 8]  = vertices[offset + 13] = vEnd;

                                // Alphas:
-                               vertices[offset + 4] = vertices[offset + 9] = vertices[offset + 14] = vertices[offset + 19] = kid.alpha;
+                               vertices[offset + 4] = vertices[offset + 9] = vertices[offset + 14] = vertices[offset + 19] = (kid.alpha * alphaFactor);

@@ -1080,8 +1088,12 @@ this.createjs = this.createjs||{};

                        // Draw children:
                        if (kid.children) {
+                               kid.alpha *= alphaFactor;
+
                                this._drawWebGLKids(kid.children, ctx, mtx);
                                maxBoxIndex = this._maxBoxesPerDraw - 1;
+
+                               kid.alpha /= alphaFactor;

**Comment by lannymcnie** [comment]
This likely won't be fixed, as SpriteContainer is going is deprecated in the next version of EaselJS, and we are focusing our efforts on the new WebGL implementation "StageGL", which you can find in the [StageGL-beta branch](https://github.com/CreateJS/EaselJS/tree/StageGL-beta) on GitHub.

If you test and post a PR before we release, we would be happy to accept it.

**Comment by lannymcnie** [comment]
Closing this, since SpriteContainer is officially removed.
