### ISSUE TITLE
Drag and drop not work on mobile

### ISSUE THREAD

**Issue by mathben** [CreateJS/EaselJS#815]
I try the tutorial drag.html

https://github.com/CreateJS/EaselJS/blob/4787f0a08c92e347b79f583fd76f1630b6ec6de0/tutorials/Mouse%20Interaction/drag.html

It works very well on desktop, but no result on mobile.
I test with chrome and safari.

**Comment by lannymcnie** [comment]
In order to do drag/drop on mobile, you must enable touch.

```js
createjs.Touch.enable(stage);
```

The demo doesn't currently do that, so we can make that change.

**Comment by mwylegly** [comment]
I'm getting an issue where instances are not matching the touch location. A dragable movieclip for example will be offset and move a strange relationship to the X/Y touch position (like the position is being multiplied by something).

**Comment by lannymcnie** [comment]
@mwylegly This is caused by a scaled container or stage. Check out this thread:
http://stackoverflow.com/questions/40809123/animate-cc-html5-easeljs-stage-x-stage-y-mouse-position-not-consistent-between-c/40819693#40819693

**Comment by lannymcnie** [comment]
I pushed up an updated tutorial to GitHub. The site will get updated in the near future.
