### ISSUE TITLE
the website createjs.com does not work when Adobe TypeKit is blocked

### ISSUE THREAD

**Issue by spelunk** [CreateJS/EaselJS#818]
I hope this is the right place to post issues with the website

http://createjs.com/ just fails when you try to load it under ghostery.  The code uses the check:

```JS
			Typekit && Typekit.load();
```

This will always throw an error if Typekit is not defined, preventing the page from loading.  The correct check is:

```JS
			(typeof Typekit !== 'undefined') && Typekit.load();
```

**Comment by lannymcnie** [comment]
Thanks, we will update it!

**Comment by lannymcnie** [comment]
Implemented. Cheers!
