### ISSUE TITLE
Examples that no longer work in Firefox 7

### ISSUE THREAD

**Issue by sir20171** [CreateJS/EaselJS#82]
I just upgraded to Firefox 7 and discovered that the following examples no longer work:

bitmapSequences.html
dragAndDrop.html
extractFrame.html
spriteSheetFlip.html

**Comment by frops** [comment]
Uncaught An error has occurred. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.

**Comment by lannymcnie** [comment]
@frops The error says you are loading content cross-domain (or using file:// which has the same issue). You need to add a crossOrigin flag to your images, and make sure the server has a allow-access header when serving images, or put your images on the same domain.

**Comment by frops** [comment]
@lannymcnie But images have header Access-Control-Allow-Origin:*. And JS have same header. What is wrong?

**Comment by lannymcnie** [comment]
Having the server give you the header is the first step, but you also need to tell your images to be crossOrigin:

```js
var image = document.createElement("img");
image.crossOrigin = "Anonymous";
image.src = "http://server.com/image.jpg";

var bmp = new createjs.Bitmap(image);
```
