### ISSUE TITLE
StageGL: Exception with missing _batchID attribute

### ISSUE THREAD

**Issue by ggschelling** [CreateJS/EaselJS#821]
Line 2241 in StageGL is throwing an exception "Uncaught TypeError: Cannot read property '_batchID' of undefined"
![bildschirmfoto 2016-11-17 um 15 41 15](https://cloud.githubusercontent.com/assets/11750733/20393971/341e7fba-acde-11e6-94d7-f9958a09b2f5.png)

`if(texture._batchID !== this._batchID) {`

**Comment by DavidHGillen** [comment]
These kind of errors occur when trying to use a single image on multiple StageGL instances. The logic governing this behaviour has been updated so this would not be the same error any more, it will be clearer. If this is an issue for anyone, try updating to the latest libs and making sure you clone the DOM image element if you intend to use it on multiple StageGL instances.
