### ISSUE TITLE
Graphics.command returning undefined

### ISSUE THREAD

**Issue by KhubaibQaiser** [CreateJS/EaselJS#822]
I want to change the stroke color of a line (on click press) drawn as:

```
var currentLine = new createjs.Shape();
currentLine.graphics.moveTo(startX, startY).setStrokeStyle(4).beginStroke(tempLineColor).lineTo(target.x, target.y).endStroke();
```
I tried the "command" property of the graphics (currentLine.graphics.command) as mentioned here: http://createjs.com/docs/easeljs/classes/Graphics.html

But it didnt work because it returns "undefined". Any help would be appreciated.

**Comment by lannymcnie** [comment]
Answered here:
http://stackoverflow.com/questions/40779310/change-stroke-color-of-shape-easeljs/40791266#40791266

Main issue was old build of CreateJS, but there was also a problem with instructions order.

**Comment by KhubaibQaiser** [comment]
Thank you lanny for answering my question here and on the stackoverflow as well :)
