### ISSUE TITLE
addedtostage event

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#833]
I had always thought that the _added_ event triggered when the object was added to the stage but now I realize that this just triggers when added to a parent.  Is there a way short of polling the stage property to find when an object is added to the stage - if not, would it make sense to have an _addedtostage_ event?  Thanks,

Dan

**Comment by danzen** [comment]
Hmmm I guess we could ask to see if there is a stage property once added - maybe that's enough.  Ya, I guess...  I'll leave this here in case you think its a good idea anyway.  I like to run the added just once so cancel the event with the 4th parameter of on().  Now, I can't do that, I have to cancel it with the event object's remove() method if the stage property is there - otherwise leave the added event active.

**Comment by lannymcnie** [comment]
See #493
