### ISSUE TITLE
Cached display object lags severely on rotation

### ISSUE THREAD

**Issue by krazbobeans** [CreateJS/EaselJS#836]
Hello-

I am using a tiled background made up of a grid of Bitmap objects. When I put all the tiles into one Container and then cache it to improve performance, everything runs great at first. Until the level rotates (that's one of the main mechanics of this game) then suddenly it lags like crazy. The tile container doesn't have anything other than Bitmap objects. Wondering what the issue might be? I can provide code or a link to the game if need be.

Thank you!
-Adam L

**Comment by gskinner** [comment]
A JSFiddle / CodePen repro with info on what browser(s) you're seeing this in would be very helpful.

**Comment by krazbobeans** [comment]
I would love to do that for you, but I'm not sure how difficult that would be with this app. It has dozens of JS files and objects that need each other to run. Can that be done with Fiddle or CodePen? At a glance it looked like it was for single JS/HTML files.

What might be easier is uploading what I have to my site and sending a link? I usually debug with the Chrome Developer window. Would that work ok?

Thanks

**Comment by gskinner** [comment]
It would be much easier for us to debug if you could create a very simple example of the problem. It may also help you to isolate the issue. If we have to read through dozens of JS files to understand what's going on, it's going to be very low on the priority list due to the time cost.

Thanks!

**Comment by krazbobeans** [comment]
Yea of course. I wouldn't want you to thumb through all of it yourself I was planning to just tell you the specific 2 or 3 areas to look at where its relevant. But the whole project would be there so you could see what's happening. 

Sorry to be a pain. I'll go ahead and try to get a good example JS for you.

Btw, I just tried something which stopped the lag. I put the scaling down to 0.05 from 0.85. Interesting.

**Comment by krazbobeans** [comment]
Putting the scaling to 0.05 made it look way too pixelated, but putting down to 0.5 I didn't notice any difference and there is no lag now. I'll go ahead and close this. :)

**Comment by gskinner** [comment]
Ok. Sounds like you might just be hitting a limitation on hardware support. If an image (in this case a cache) gets too large, some browsers may switch from GPU to software rendering.
