### ISSUE TITLE
easeljs drag and drop sluglish on ipad

### ISSUE THREAD

**Issue by jenniferschofi** [CreateJS/EaselJS#837]
I am having an issue with drag and drop.  I built drag and drop and it works however it is very slow and not smooth.  the mouse can move quicker then the card dose. and it is on the ipad also but it is smooth on the iphone help i looked everywhere I  have tried catching 
 the cards changing the tick rate, playing with the stage.enablemouseover nothing is working

[brain_workouts_moble.zip](https://github.com/CreateJS/EaselJS/files/725382/brain_workouts_moble.zip)

**Comment by danzen** [comment]
Just peeking - you might want to see what the framerate you are setting is on the iPad - which model iPad is it? I found setting the framerate too high actually lessened performance (although I don't think it mattered with dragging) so now use 30 on mobile - too low might not be good either.  The drag code looked good, I think.  You maybe could have put the code on a container and used e.target to target the card - but I don't think that will matter.  console.log() in the mousedown to make sure you only are calling this once. Perhaps simplify - just try a shape and your drag code (without anything else) and see if that is moving smoothly and then go from there.  Or perhaps the folks here will have an answer - I have not had drag delay issues on any iPads - maybe ask on StackOverflow if you have not already.  You probably know all that stuff - so off I go... have a good night!

**Comment by MannyC** [comment]
I ran this and it seemed fluid for me on my PC.  If you're using a Ticker (and you are) then try taking the update call out of the pressmove event handler.  Also, as a side note, most webserver file systems are case sensitive so Portrait.png != portrait.png

**Comment by jenniferschofi** [comment]
It dose work great on the desktop and we were supersized when it had trouble on mobile If someone could please check out this web link on android or and ipad that would be great.   http://www.mathplayground.com/br/brain_workout_01_addition_Canvas.html That would be great If you move your figure slow it is fine but when you move your figure fast there is a lag.  and since it is a kids game we need to take care of this.  I have converted 9 flash actionscript games into html5 and this is the only thing keeping me from moving forward.  We want to convert as many as we can before flash goes away

**Comment by jenniferschofi** [comment]
Thanks for your suggestions I was able to figured it out i needed to cache images that did not change.  This was slowing down run time and the ipad was not processing quick enough
