### ISSUE TITLE
Alpha of SpriteContainer ignored?

### ISSUE THREAD

**Issue by cotejp** [CreateJS/EaselJS#839]
I am fading a `SpriteContainer`'s `alpha` property with TweenJS. By listening to the change event, I can see that the value of `alpha` changes over time. However, the sprites inside the container are not affected by the change at all. This is roughly what I'm doing:

```javascript
hero.alpha = 1;

createjs
  .Tween
  .get(hero)
  .to({alpha: 1}, 1000)
  .addEventListener("change", () => console.log(hero.alpha))
```
If I perform the tween directly on any of the container's children, the fading happens as it should. I don't think this is the expected behaviour but maybe I'm missing something?!

**Comment by lannymcnie** [comment]
I think this might be a bug in the old SpriteContainer. We deprecated its usage, and recommend trying out the new StageGL. It is ready, it just needs docs and demo polish, which we have been trying to get to recently. You can get it from the [StageGL-beta branch](https://github.com/CreateJS/EaselJS/tree/StageGL-beta). It is both more performant, and also way easier to use (just swap your stage).

Cheers,

**Comment by cotejp** [comment]
@lannymcnie Ok, thanks for the input. I'm in the middle of a project with my students and it's probably not the best time to switch (especially if the documentation is not ready yet)... unless the JSDoc that I saw inside the StageGL object is published somewhere?

By the way, it might be a good idea to update the `SpriteStage` and `SpriteContainer` documentation to say that they are now deprecated ;-)

Thanks.

P.S. `StageGL` is a much better name than `SpriteStage` (imo).

**Comment by cotejp** [comment]
Does `StageGL` also require the use of a single sprite sheet?

**Comment by lannymcnie** [comment]
No, StageGL is a rewrite to remove those limitations. You can literally swap out the regular stage for a StageGL, and any supported content will work. This version has a much more efficient pipeline, and is able to use as many textures as are supported by the GPU.

Not supported: Vectors and text (unless cached)

It is advisable to still work things into spritesheets where possible (eg, a lot of small caches are not helpful to the GPU).

**Comment by cotejp** [comment]
@lannymcnie Excellent! Can't wait to try it out with my students. It should be easier this way. I'll wait for an official and documented release though. Thanks for the excellent work. Cheers!

**Comment by lannymcnie** [comment]
Closing this since SpriteContainer is officially removed.
