### ISSUE TITLE
EaselJS app with Require, getBounds() returns null.

### ISSUE THREAD

**Issue by kirkins** [CreateJS/EaselJS#843]
I have some text created like this:

    dialogText = new createjs.Text(text, 'bold ' + (28 * scale) + 'px Calibri', '#FFFFFF');

Then later on I use` dialogText.getBounds()` which returns `null`.

I try console logging `dialogText `and I can see that it is set and there is a `value _bounds` which reads null.

When I use the same javascript without requirejs it seems to work fine. 

Any tips of what might be causing my issue?

**Comment by lannymcnie** [comment]
Posted some comments here: http://stackoverflow.com/questions/42068565/easeljs-getbounds-when-are-dimensions-set/42072537#42072537

I recommend providing a demo. I haven't seen this issue, and can't reproduce without more info, or a test case.

Cheers.

**Comment by kirkins** [comment]
I'm trying to debug further with the information you provided.

The two implementations are located here:

without requirejs (working): https://dev-cms.virtualhighschool.com/30/interactives/universal/interactives/d2l/searchEngine/index.html

With require (not-working): https://dev-cms.virtualhighschool.com/30/interactives/universal/index.html?id=preview/7038395&type=searchengine

**Comment by lannymcnie** [comment]
The provided site with require does not load for me (missing json asset error in console)

**Comment by kirkins** [comment]
@lannymcnie sorry about that can you try this one? https://dev-cms.virtualhighschool.com/30/interactives/universal/index.html?id=preview/3431480&type=mealMaker

**Comment by lannymcnie** [comment]
Better, but still missing JS and CSS (createjsCog.js). No content visible.

**Comment by kirkins** [comment]
Wow today is not my day I accidentally sent you the wrong interactive the second time here is the one with the described error: https://dev-cms.virtualhighschool.com/30/interactives/universal/index.html?id=preview/7515540&type=searchengine

**Comment by lannymcnie** [comment]
Sorry. Still not working.
Missing https://dev-cms.virtualhighschool.com/30/interactives/universal/json/preview/7515540.json

**Comment by kirkins** [comment]
Sorry I ended up going on vacation and co-workers removed a bunch of stuff from our dev server. 

I edited my message to an [instance where the bug is occurring](https://dev-cms.virtualhighschool.com/30/interactives/universal/index.html?id=preview/6998916&type=searchEngine)

**Comment by MannyC** [comment]
Your `dialogText` has no text in it, so it's returning null for `getBounds()`

**Comment by kirkins** [comment]
@MannyC  wow thanks so much!
