### ISSUE TITLE
MovieClip.children doesn't update after gotoAndStop(1)

### ISSUE THREAD

**Issue by oshevans** [CreateJS/EaselJS#848]
CreateJS (2015.11.26) via Animate CC (16.0.0.112)

Project structure :

```
root
 - myContainer
     - frame 0 -> btn_0
     - frame 1 -> btn_1
```
First frame of root contains following code :

```
var self = this;
createjs.Ticker.addEventListener("tick", initScreen);

function initScreen() {
    createjs.Ticker.removeEventListener("tick", initScreen);
    self.myContainer.gotoAndStop(1);
}

this.myContainer.addEventListener("click", function(e) {
    console.log("Button 0 : "+self.myContainer.btn_0);
    console.log("Button 1 : "+self.myContainer.btn_1);
});
```
The result is :

```
[Log] Button 0 : [MovieClip]
[Log] Button 1 : undefined
```
And when iterating through self.myContainer.children, only btn_0 exists.

So self.myContainer.children is not being updated when playing through the frames.

**Comment by saar62097** [comment]
I believe this is because both buttons use the same symbol.
In AnimateCC, choose btn_1 and change its "instance of", by swapping-duplicating to a new symbol.

This logged for me:
Button 0 : [MovieClip (name=null)]
Button 1 : [MovieClip (name=null)]

**Comment by sebastianderossi** [comment]
Hi @oshevans 
I am actually seeing: 
```
console.log("Button 0 : "+self.myContainer.btn_0);
console.log("Button 1 : "+self.myContainer.btn_1);
```
```
Button 0 : [MovieClip (name=null)] 
Button 1 : [MovieClip (name=null)]
```
However,  if I remove the string value `Button 0:`
Results in this:

```
lib.MyButton {_listeners: {…}, _captureListeners: null, alpha: 1, cacheCanvas: null, cacheID: 0, …}
```
Looking at your provided code sample, I was wondering why are you adding a `tick event` handler? Why not just call `self.myContainer.gotoAndStop(1);` from the beginning? There is no need for a `tick` event. Also you know you don't have to code from within AnimateCC, you could do that in the generated HTML. 

For instance, you can reference your container clip `myContainer` from the `exportedRoot`
```
var myContainer = exportedRoot.myContainer;
myContainer.on("click", function (event) { ... })
```

**Comment by oshevans** [comment]
Thanks @sebastianderossi.

This is from way back in March - not sure what software versions you are using, but guessing things have changed to fix the issue. 
(We used CreateJS (2015.11.26) via Animate CC (16.0.0.112) back then.)

Also, this is an isolated and self contained example to test and highlight the issue - it's not the production code used in the project (e.g. we use another code editor and take advantage of exportedRoot).

Cheers.

**Comment by sebastianderossi** [comment]
Hi @oshevans,

Sorry, about the delay sometimes issues get missed. We are doing our best to answer everyone's questions/concerns :)

Anyway I am testing against the CDN version which is the default when publishing from CC `https://code.createjs.com/createjs-2015.11.26.min.js` `2017.2 Release Build 16.2.0.24`

I did suspect that this may have been a simple example to illustrate your issue. :)

I am going to close this issue because it seems that this is no longer a problem for you.

Thanks!
