### ISSUE TITLE
getBounds ignores font-variant-ligatures: none;

### ISSUE THREAD

**Issue by oshevans** [CreateJS/EaselJS#849]
CreateJS (2015.11.26) via Animate CC (16.0.0.112)

When a string contains ligatures and the font-variant-ligatures property is set to none, the text displays correctly, but the getBounds seems to use the ligature to calculate it's width.

e.g. the word hoffi in Welsh (meaning 'to like') consist of h and o characters, and the ffi ligature (which is a squished version of the f,f and i characters).
So, when displayed with ligatures turned on, the text is shorter than when ligatures are turned off via the CSS property font-variant-ligatures.

Using getBounds to draw a rectangle around the ligatured text (squished ffi), results in the text fitting inside the rect.
Using the getBounds to draw a rectangle around the non-ligatured text, results in the text overlapping the rect (it is the same size as with ligatures).

**Comment by lannymcnie** [comment]
Relevant SO post: http://stackoverflow.com/questions/42684645/createjs-easeljs-getbounds-ignores-font-variant-ligatures-none

**Comment by lannymcnie** [comment]
Text getBounds almost entirely relies on the canvas's APIs and measurement, there isn't anything EaselJS can do.

If this problem can be shown to not exist in raw Canvas, feel free to reopen the issue.
