### ISSUE TITLE
Featuring on createjs.com

### ISSUE THREAD

**Issue by griii2** [CreateJS/EaselJS#852]
Hi guys

While I was going to shamelessly ask if you could feature our project in the carousel on createjs.com I have noticed that it does not work as intended, there seems to be too many dots and while Ion Drift is the last content, the rest is empty. See https://www.dropbox.com/s/lxuqj4jgdj3bh2r/Screen%20Shot%202017-03-23%20at%2015.55.52.png?dl=0

Our project is zoomable budget visualizator 

Example: https://uk.wikibudgets.org/w/united-kingdom-budget-2015
Drag & Drop Editor: https://www.wikibudgets.org/sankey/

Also I would like to thank you, you have answered my questions on several occasions and we could not have build our project without the precise documentation and familiar architecture of EaselJS.

Have a great day!

**Comment by lannymcnie** [comment]
Thanks for the report, we will check it out.

We would be happy to include it. We came across it last week on the FWA submissions, awesome work!

Cheers,

**Comment by griii2** [comment]
I am not sure if we were submitted to FWA, but thanks anyway. I have been following Grant Skinner since I learned programming 14 years ago, being featured on your website would be a great honour for me.

**Comment by lannymcnie** [comment]
We added your site this morning. Cheers!

For anyone else with cool projects you want to share, tweet us @createjs!

**Comment by griii2** [comment]
Awesome, thanks! I can see it on http://www.createjs.com/easeljs but not on http://www.createjs.com/. Also your OG tag image seems to be blank.
