### ISSUE TITLE
Shape From Bitmap not working on latest chrome update

### ISSUE THREAD

**Issue by chaitanya055** [CreateJS/EaselJS#856]
I am using easeljs version 0.8.2. The shape from bitmap fill is not working on chrome update version 57. 

This is the auto-generated code for bitmap fill, created by Adobe Animate
```
this.shape = new cjs.Shape();
this.shape.graphics.bf(cjs.SpriteSheetUtils.extractFrame(ss["game_atlas_"],27), null, new cjs.Matrix2D(1,0,0,1,-745.7,-61.5)).s().p("A1MJYIC4yuMAnhAAAIgKBkIguRKg");
```

The above shape is not visible on the canvas. The click events are being recognized properly. This issue is occurring only from chrome version 57. In browsers with chrome version < 56, it is working fine.

The beginRadialGradientFill is working fine. Below is the code for gradient fill.

```
this.shape = new cjs.Shape();
this.shape.graphics.rf(["#FF6969","#D22402"],[0,1],0.1,0,0,0.1,0,1.7).s().p("AgEAKIgLgKIALgJIAJAAIALAJIgLAKg");
```

Please suggest a fix for that issue.

**Comment by lannymcnie** [comment]
The bitmap fill requires an image. 
* Are you sure its loaded? 
* Did this work in earlier Chrome versions, or other browsers?
* Have you tried the NEXT version in GitHub? A number of fixes have been pushed.

Any chance you have a demo handy?

**Comment by chaitanya055** [comment]
@lannymcnie 

- The image is a part of a spritesheet, all the other images in that spritesheet are loaded, so the bitmap is loaded.
- It is not working in other browsers, but it is working in earlier Chrome versions. (installed older version and tried)
- I tried with NEXT version also, but still not displaying.

Here is the demo : http://ec2-35-164-41-102.us-west-2.compute.amazonaws.com/bitmapfilltest/

Here is the source code & fla : http://ec2-35-164-41-102.us-west-2.compute.amazonaws.com/bitmapfilltest/BitmapFillTest.zip

In the demo, a bitmap fill shape is visible for 3 frames and hidden for 3 frames, it is working in older chrome versions, but not in latest version and other browsers.

**Comment by lannymcnie** [comment]
It looks like this is an issue with the image not being ready yet. I added in an `onload` handler, and did the draw when that fired, and it worked fine.

```
        // Layer 2
	this.shape = new cjs.Shape();
	var img = cjs.SpriteSheetUtils.extractFrame(ss["BitmapFillTest_atlas_"],0);
	img.onload = function() {
		this.shape.graphics.bf(img, null, new cjs.Matrix2D(1, 0, 0, 1, -300, -200)).s().p("AsfI/IAAx9IY/AAIAAR9g");
	}.bind(this);
	this.shape.setTransform(383,213.5);
```

**Comment by chaitanya055** [comment]
@lannymcnie 

Thanks a lot lannymcnie. It solved the issue. Now, I am loading javascript file after spritesheet is loaded instead of changing the flash generated file.
