### ISSUE TITLE
0.8.2 examples AlphaMaskReveal.html setStroke "width" is not working

### ISSUE THREAD

**Issue by bmorwood** [CreateJS/EaselJS#858]
release 0.8.2 - example 'AlphaMaskReveal.html' "examples/AlphaMaskReveal.html" setStroke width is not working and showing a small line 1px.

I checked out tagged release 0.8.1 and the example works fine.

**Comment by lannymcnie** [comment]
This is a known issue with 0.8.2, and it is fixed in the NEXT build (last week, actually).

**Comment by bmorwood** [comment]
Thank you, I switched from master to GMC-0.8.2 and it is working.
