### ISSUE TITLE
when bitmap load the bitmap is zoomed

### ISSUE THREAD

**Issue by gkio** [CreateJS/EaselJS#859]
when i am loading an image its shows the same size like the canvas the both is 700 with but the image in canvas loaded is like zoomed 1000% 

```js
 stage = new createjs.Stage("scratch");
   var background = new createjs.Bitmap("IMAGE.png");
   var frame = new createjs.Bitmap("frame.png");
    stage.addChild(background);
    stage.addChild(frame);
    background.image.onload = function() {
    		stage.update();
	}
````

**Comment by lannymcnie** [comment]
Any chance you are setting the size or scaling the canvas with CSS / jQuery?

**Comment by gkio** [comment]
yes with css i give the width of canvas

**Comment by gkio** [comment]
@lannymcnie i deleted from css the width and height and added on element its works perfect thx
