### ISSUE TITLE
DisplayObject.mask doesn't work with StageGL

### ISSUE THREAD

**Issue by ricofegh** [CreateJS/EaselJS#860]
As soon as the .mask property expects to be set to a Shape object it obviously cannot be used with StageGL, and there is no other instrument for masking complex display objects.

**Comment by lannymcnie** [comment]
You should be able to use the AlphaMaskFilter, which can use a cached shape.

**Comment by ricofegh** [comment]
But it works for me only when I cache the target object as well. In case there is animation inside of the target object I have to update cache every single frame and it should be extremely slow. AlphaMaskFilter doesn't use stencil buffer yet, does it?

**Comment by lannymcnie** [comment]
Correct. We have better masking on the roadmap.

**Comment by ricofegh** [comment]
In my project I use masks a lot and now it looks not that pretty when I use StageGL. But same time it works much faster than before! That's why I'm really concerned about masks support. What is the current state of this feature now? Is there any chance that it will be added soon? Thank you.

**Comment by lannymcnie** [comment]
If your masks require vectors, then it may not get support in the near future. You can use mask filters such as AlphaMaskFilter though. Caching your vectors and using masks works quite well.

**Comment by ricofegh** [comment]
Actually I want to apply bitmap mask over movie clip with some animation inside. In case of using AlphaMaskFilter I'll need to cache movie clip every single frame.

**Comment by ricofegh** [comment]
I learned more about how caching works with param {useGL: "stage"} and found that as soon as it just handle webGL to render frame to frame buffer, it works quite fast. So, it's possible to update cache every frame without big performance lags. I tried this approach in my project and it works well.
