### ISSUE TITLE
Button states are not updated until mouse movement

### ISSUE THREAD

**Issue by chaitanya055** [CreateJS/EaselJS#862]
I am disabling a button on clicking it, by setting `button.mouseEnabled = false;`. When I re-enable it by setting `button.mouseEnabled = true;`, the hover state is not shown on the button, until there is a mouse pointer movement.

**Comment by lannymcnie** [comment]
This is typical because although you changed the enabled, property, the mouse position is only updated on move.

**Comment by lannymcnie** [comment]
Closing in favour of #861
