### ISSUE TITLE
StageGL antialiasing problem

### ISSUE THREAD

**Issue by cotejp** [CreateJS/EaselJS#863]
I tried to enable `antialias` on StageGL but it does not seem to work. This is what I used: `new createjs.StageGL("stage", {"antialias": true})`

When I inspect the stage, I see that the `_antialias` property is set to `true`. If I go back to using `SpriteStage`, antialiasing works as it should.

**Comment by lannymcnie** [comment]
Are your sprites a size that is factor-of-two?

**Comment by cotejp** [comment]
No, they're not. I did not realize they had to be. I'm using `Bitmap` and `Sprite` objects. Do they both have to be POT ?

**Comment by lannymcnie** [comment]
The source images must be, whether they are used in Sprites or Bitmaps. This is a WebGL 1.0 limitation -- and I am not sure why SpriteStage would not have that limitation.

**Comment by DavidHGillen** [comment]
Currently we're enforcing the pixelated (nearest neighbor) scaling when they don't meet the full requirements for proper smoothing, which include being POT in WebGL 1.0. But on an AntiAliased context you can upscale (but not downscale) with linear scaling on non POT textures, we'll see about making sure that linear is available with less hoops. If you're the type to digging in the source look at `StageGL.setTextureParams` and you'll notice its probably a quick turn around barring testing etc.

**Comment by cotejp** [comment]
I made sure all my textures where POT-compliant and now anti-aliasing works fine. What threw me off was that this wasn't a requirement with `SpriteStage`. Thanks for your help.
