### ISSUE TITLE
Button helper not destroying

### ISSUE THREAD

**Issue by chaitanya055** [CreateJS/EaselJS#865]
I have a few buttons on a game. When I destroy the game in buttons disabled state and start again, the mouse pointers are flickering. Looks like two button helpers are created for that button. How to completely remove button helpers when destroying the game?

**Comment by gskinner** [comment]
Please use StackOverflow for support questions. If you believe this is a bug, please provide an isolated test for it in jsfiddle or codepen.

However, to answer your immediate question: Unless you are retaining references elsewhere, ButtonHelper should be freed for garbage collection when its target is removed. The only references a ButtonHelper instance creates to itself is in the target's event listener queues.
