### ISSUE TITLE
Edges of children of a masked container bleed into each other

### ISSUE THREAD

**Issue by Lange** [CreateJS/EaselJS#871]
Apologies for the verbose title, but it's a somewhat complex scenario:

Given a container with a mask and multiple children, the edges of these children will bleed into each other causing unpleasant aliased edges.

In [this JS Bin](https://jsbin.com/dabuboqibe/edit?html,js,output), you can see that the edges of the black shape object are visible around the perimeter of the yellow shape, despite the yellow shape completely covering the black shape. This gif illustrates the problem clearly:

![2017-05-02_17-34-51](https://cloud.githubusercontent.com/assets/873012/25642160/b41d7390-2f5d-11e7-8d98-1a503968ddbe.gif)

**EDIT**: This happens in Chrome, Chrome Canary, Safari, and Edge, but _does not happen in Firefox_.

**Comment by Lange** [comment]
Ah, hm. I've just realized that this happens in vanilla canvases as well, without EaselJS: https://jsbin.com/kutovogawo/1/edit?html,js,output

Is there anything that can be done to combat this?

**Comment by Lange** [comment]
I couldn't find a bug on crbug.com for this, so I've opened one: https://bugs.chromium.org/p/chromium/issues/detail?id=717809&can=1&q=canvas%20clip%20bleed&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified#

**Comment by MannyC** [comment]
This appears to be related, but seems to imply that what's happening shouldn't actually be happening: http://neugierig.org/software/chromium/notes/2010/07/clipping.html

If you need a workaround you should be able to do something with `compositeOperation`: https://jsbin.com/fuhopaqeso/edit?html,js,output

**Comment by Lange** [comment]
@MannyC that works! I've implemented that in my project and it should be enough to get me across the finish line. Thank you!!

**Comment by Lange** [comment]
This issue has been [closed as `WontFix`](https://bugs.chromium.org/p/chromium/issues/detail?id=717809) by the Chrome team, so I suppose there's nothing more to be done.
