### ISSUE TITLE
Rich text editing in canvas

### ISSUE THREAD

**Issue by cksachdev** [CreateJS/EaselJS#873]
Are there any rich text editing libraries which can be used with createjs/canvas? 

Something similar to hallo.js 
http://bergie.iki.fi/blog/hallo-editor/

or  
Froala 
https://www.froala.com/wysiwyg-editor/inline

**Comment by lannymcnie** [comment]
Answered on StackOverflow: http://stackoverflow.com/questions/43981175/rich-text-editing-on-html5-canvas/43983233#43983233

TLDR: Wrap DOM content in DOMElement. Canvas's text capabilities are too limited to do much.
