### ISSUE TITLE
StageGL works considerably slower in a scene with cached movieclips

### ISSUE THREAD

**Issue by Nestorferrando** [CreateJS/EaselJS#878]
Hi! I tried the new StageGL and it work slower over chrome in both PC and android devices.

The scene I used for testing consists of a set of 800 cached movieclips, each one contains a blue rectangle:

        **### for (var i = 0; i < 800; i++) {
                var someSymbol = new lib.Symbol1();
                someSymbol.gotoAndStop(0);
                someSymbol.x = (Math.random() * 650) - 300;
                someSymbol.y = (Math.random() * 650) - 300;
                someSymbol.cache(0, 0, 200, 100);
                _this.stage.addChild(someSymbol);
            }**

the render time with the traditional Stage: about 5 ms

![image](https://cloud.githubusercontent.com/assets/4629402/26628412/4acb3e24-45fe-11e7-9162-bd131479ffec.png)

render time with stageGL: about 30 ms

![image](https://cloud.githubusercontent.com/assets/4629402/26628469/8fac35de-45fe-11e7-9026-2842e6287f9c.png)

This results are obtained with a core i7 laptop running last version of chrome, but I obtained similar results on a Samsung Galaxy S4.

**Comment by lannymcnie** [comment]
A ton of separate textures is not ideal for WebGL, as a GPU can only work with a smaller set at a time (8 ,16, etc -- depends on the video card), so it has to constantly re-upload textures, in your case between 50 and 100 times per tick. 

If you want to get a performance increase with StageGL, you have to optimize your approach. One way is to use [SpriteSheetBuilder](http://www.createjs.com/docs/easeljs/classes/SpriteSheetBuilder.html) to put a group your caches into less textures. There is a [SpriteSheetBuilder demo](https://github.com/CreateJS/EaselJS/tree/master/examples/SpriteSheetBuilderMC) in GitHub, and you can swap out the `Stage` for a `StageGL` instance to see it in action.

The behaviour you describe is definitely expected when you have a lot of separate small textures.
