### ISSUE TITLE
Hosting EaselJS on CDNJS

### ISSUE THREAD

**Issue by dakshshah96** [CreateJS/EaselJS#879]
Hey @gskinner,

I'd like to host your library, EaselJS on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

However, when I took a look at the `lib` folder in your repository to find files to be fetched for CDNJS, I noticed that you use the version numbers in your file names, like so `easeljs-0.8.2.min.js`.

CDNJS convention is to not include version numbers in file names and that's the convention followed by most public CDNs.

If it's not too much trouble, would it be possible to remove the version numbers from your file names to clear things up? You could always rely on GitHub/npm release tags for managing releases.

Thanks, and sorry for the trouble!

https://github.com/cdnjs/cdnjs/pull/11363

**Comment by sufuf3** [comment]
@lannymcnie Could you help us this issue?

**Comment by lannymcnie** [comment]
We are considering this for future releases.

**Comment by sufuf3** [comment]
@lannymcnie Thank you.

**Comment by lannymcnie** [comment]
We have simplified the naming in the latest version (1.0.0), and it should be good to go for cdnjs!

**Comment by sufuf3** [comment]
Many thanks.

**Comment by lannymcnie** [comment]
Quick update, CDNJS has all the latest libs, except the combined lib. We are working with them to get it live, however because we made some GitHub changes, it is showing as a new lib without much usage, so it might be a while before they accept it :)
