### ISSUE TITLE
stop() not working as expected

### ISSUE THREAD

**Issue by mat-witts** [CreateJS/EaselJS#881]
this.stop() persistently failed to stop cjs.MovieClip() timeline after working as expected for months.
replacing this.stop() with this.gotoAndStop() resumed expected behavior.

**Comment by sebastianderossi** [comment]
Hi @mat-witts 
Can you give more specifics on this? 
It would be helpful for us to know what version of the libs are you using? 
Did anything change with your project?

Thanks!

**Comment by mat-witts** [comment]
createjs-2015.11.26.min.js, nothing changed with the project... it just stopped working after months of production use, this resumed expected behavior:
`	// timeline functions:`
`        this.frame_0 = function() {`
`        this.stop();`
`        this.gotoAndStop(parseInt(sessionStorage.gametype));`
`	}`

**Comment by sebastianderossi** [comment]
Hi @mat-witts 

Seems strange to me that `this.stop();` wouldn't stop the movieClip in its tracks. Can you give me more information about the construction of your clip? By the looks of your code, can I assume that    `parseInt(sessionStorage.gametype)` is 0?

Actually, if you can provide a sample of this issue that would help us.

Thanks!

**Comment by mat-witts** [comment]
Sorry, previous code was from an unrelated animation, will dig around the codebase for you and post here if I can find the diff. in versions.

**Comment by mat-witts** [comment]
Using CDN: easeljs-0.7.1.min.js tweenjs-0.5.1.min.js movieclip-0.7.1.min.js the following code works as expected:
`// timeline functions:`
`this.frame_0 = function() {`
`this.stop();`
`this.tens_mc.stop();`
`this.hundreds_mc.stop();`
Using createjs-2015.11.26.min.js the animation loops with any use of stop(). This works:
`// timeline functions:`
`this.frame_0 = function() {`
`this.gotoAndStop(0);`
`this.tens_mc.gotoAndStop(0);`
`this.hundreds_mc.gotoAndStop(0);`

**Comment by sebastianderossi** [comment]
Hi @mat-witts,

Interesting, I can confirm that it is not working on `createjs-2015.11.26.min.js`. However, I can also confirm that it **does** work on the latest version of `createjs1.0`

Give it a shot :)
[CreateJS v1.0](https://github.com/CreateJS/Combined/releases)

Thanks!

**Comment by mat-witts** [comment]
Just to confirm, `createjs.min.js` produces expected behavior with use of stop(). Just FYI, in the `Combined-1.0.1` version, `build` contains subfolder `1.0.0` which maybe gives the impression the latest version is a downgrade... possibly?

**Comment by sebastianderossi** [comment]
Hi @mat-witts,

Correct, how it was working before: 
```
// timeline functions:
this.frame_0 = function() {
this.stop();
this.tens_mc.stop();
this.hundreds_mc.stop();
```
 is how it's working now in v 1.0. 

Cool, I will make a note of `1.0.0` subfolder.

I am going to close this issue now but feel free to re-open if needed.

Thanks!
