### ISSUE TITLE
WebGL blend alpha with gray color

### ISSUE THREAD

**Issue by LazeKer** [CreateJS/EaselJS#883]
I'm looking for the new WebGL refactoring (`NEXT` release) but an issue stopped me in the process. When I try to add a `Sprite` in a webgl stage with transparency, the image's alpha seems to be blend/processed with some gray glitches.

You can try it through this examples :
- webgl : https://codepen.io/anon/pen/jwmbJg
- canvas : https://codepen.io/anon/pen/WOjrOb

I tried to change the clearing color `stage.setClearColor("rgba(255,255,255,0.0)");`. Did I missed something?!

**Comment by DavidHGillen** [comment]
@grant 
> I can notice a slightly darker colour around the edges of the transparency. This is part of different image standards treating transparency slightly differently. The best fix for you is to turn on the premultiply flag when creating your StageGL instance. On my screen that gets rid of the the black touches in the transparent areas. `{transparent:true, premultiply:true}` but as a reminder, you really don't want to use "transparent:true" unless you can't avoid it because it has massive performance impacts. Hope that helps.
