### ISSUE TITLE
WebGL animation framerate parameter not working

### ISSUE THREAD

**Issue by neurall** [CreateJS/EaselJS#888]
all our animations were limited to 15 fps yet they all run 60 ignoring parameter it sems

**Comment by lannymcnie** [comment]
How are you setting framerate? What is your timingMode?

If you are using RAF, it is not limited by a framerate. Try RAF_SYNCHED, which uses RAF but simulates another framerate. You also have to ensure you pass the TIcker event through to the stage.

```js
createjs.Ticker.timingMode = createjs.Ticker.RAF_SYNCHED;
createjs.Ticker.framerate = 15;
createjs.Ticker.on("tick", function(e) {
    stage.update(e); // Pass event to the update
});
```

**Comment by neurall** [comment]
Hi lanny.  Thx a lot. Unfortunately bug was on my side sorry for that ;(.

I was hooking Sprite.tick and I forgot to pass event param to original tick. My bad.

Anyway
We are hooking Sprite.tick to collect bounds rectangles just once for fast rectangle based hit testing that is so needed for gui in createjs.
I plan to add this and fast rectangle-based hit testing as a pull requests when ready to give back to this wonderful community.
