### ISSUE TITLE
artifacts on certain apple devices when using premultiply = true

### ISSUE THREAD

**Issue by Nestorferrando** [CreateJS/EaselJS#892]
Hi! In order to get the best image quality on my StageGL I activate the 'antialias' flag for images smoothening and 'premultiply' flag to avoid weird colors arround edges.

This works fine on windows/android, but on certain iPhones/Macbook, some weird artifacts appear in areas with alpha set to 0 (they are shown as black):

![image](https://user-images.githubusercontent.com/4629402/27959623-807bd1b8-6328-11e7-8597-b3f64dd6b154.png)

I also tried playing with 'transparent' and 'preserveBuffer' flags. With no changes.

I'm not sure if this is actually a bug of certain apple devices. As it seemed to work nice on other apple devices.

Devices with problems: 

iPhone 6s
iOS 10.3.2  (latest)
AppleWebkit: 603.2.4

MacBook:
Safari 9.1.1
MacOS 10.11.15 (Capitán)
Webkit 601.6.17

Devices that worked OK
Mac Mini
Safari 10.1
MacOS 10.12.4

**Comment by DavidHGillen** [comment]
I've seen this before and I added a flag to the main shader to account for it, odd that it's showing up for you. Should be an easy fix once I track down what's causing it to occur.

I'll look into this and see if there's something I can do. Do you have a minimum replication scenario I could play about with? Are you doing anything like caching, specifying an opaque clear color, applying filters?

**Comment by Nestorferrando** [comment]
Hi!
find attached a minimum project that replicate the errror. It is basically a text with a transparent background that shows the frames per second.

The code is in "production\sample\sample.js". It looks a bit weird because it is transpiled from another language, but is small enough to understand (about 30 lines of code :-) )

The background is shown black on an IPhone6S

I just tried also on an IPhone6 (not S) and also looks fine. It seems that something device specific. Weird

[SampleThatFails.zip](https://github.com/CreateJS/EaselJS/files/1142277/SampleThatFails.zip)

**Comment by DavidHGillen** [comment]
Latest NEXT build should have this fixed. Turns out GLSL division by 0 is an undefined behavior and some browser/hardware combos handle it differently. I added a check to bypass that problem. Should be good to go.

**Comment by lannymcnie** [comment]
Closing for now. Feel free to reopen if problem persists. Thanks for the report!!
