### ISSUE TITLE
Bleeding with multiple calls to rect() on the same shape

### ISSUE THREAD

**Issue by tristan-shelton** [CreateJS/EaselJS#895]
I'm new to EasleJS and I'm not sure if I'm using it incorrectly, but the Graphics.rect() function has unexpected behavior for me. When I try to draw a tile map using a bunch of rects I get some kind of "bleeding" at the edges that doesn't seem to happen with other methods.

I've created a fiddle demonstrating the problem here: https://jsfiddle.net/sgpjoxa6/2/

This is the essential code that exhibits the issue:

```javascript
function drawGrid(shape) {
  for (var r = 0; r < 9; r++) {
    var color = 'hsl(' + Math.floor(Math.random()*360) + ', 50%, 50%)';
    var x = r % 3 * 32;
    var y = Math.floor(r / 3) * 32;

    shape.graphics.beginFill(color).rect(x, y, x + 32, y + 32);
  }
}
```

Note that using drawCircle() or a series of lineTo()s terminated with a closePath() don't have the same behavior.

**Comment by XESDog** [comment]
`rect(x,y,width,height);`
change you code to:
`shape.graphics.beginFill(color).rect(x, y, 32/*width*/, 32/*height*/);`

**Comment by tristan-shelton** [comment]
Oh, it's a width and height not a coordinate. How embarrassing. Thank you!
