### ISSUE TITLE
Easeljs 1.0.0 on the Createjs.com CDN? Or using another one?

### ISSUE THREAD

**Issue by q2apro** [CreateJS/EaselJS#905]
Just wanted to point out that at http://code.createjs.com/ there is still v. 0.8.2.

https://code.createjs.com/easeljs-0.8.2.min.js

Would be great to get the v. 1.0.0 file at: 

https://code.createjs.com/easeljs-1.0.0.min.js

Or should we use another CDN? (Still the others don't have the latest version.)

**Comment by lannymcnie** [comment]
We are currently waiting on Adobe to push the latest (they manage our CDN). FYI, the new URL will be https://code.createjs.com/1.0.0/createjs.js

Cheers,

**Comment by lannymcnie** [comment]
The Adobe CDN was finally updated! The site has been updated too to reflect it. Cheers!

**Comment by danzen** [comment]
That's great news!  Looking forward to 1.1 - or whatever it becomes with the recent TweenJS updates that Grant made.  I mean, great news!  Just wondering how quickly updates can be made going forward ;-)

**Comment by lannymcnie** [comment]
Tween updates will definitely be in a dot-update, before they are ported to the ES6 version, which we hope will be 2.0.
