### ISSUE TITLE
Can't update a radial gradient fill color in RAF

### ISSUE THREAD

**Issue by heaversm** [CreateJS/EaselJS#909]
I am constructing a radial gradient filled circle in easelJS for a javascript canvas animation:

```
    const blur1 = new createjs.Shape();
    const endColor = this.hexToRGBA(data.settings.startColor,0);
    blur1.circleCmd = blur1.graphics.beginRadialGradientFill([data.settings.startColor,endColor], [.25, .9], 0, 0, 0, 0, 0, 50).command;
    blur1.graphics.drawCircle(0,0,50);
```

I am using the command function so that I can later update that fill.

In a request animation frame, I'd like to be able to say `update the fill of this circle to the current color` - a color value I'm tweening. So I have:

```
    thisBlur1.circleCmd.style.props.colors[0] = curColor;
    thisBlur1.circleCmd.style.props.colors[1] = this.hexToRGBA(curColor,0);
```

I see that it sets the properties of the circle properly, but it doesn't update the color on the screen, so I'm guessing that the style.props.colors array is read-only? Or maybe I need to just completely redraw the circle each frame? I'd like to avoid that, as there are a number of other properties which can change at any frame for this circle.

How do I update the gradient fill of a circle in easelJS?

**Comment by lannymcnie** [comment]
I answered your question here: https://stackoverflow.com/questions/46567399/how-to-update-a-radial-gradient-fill-color-in-easeljs/46568335#46568335
