### ISSUE TITLE
Shape with custom scale property not working

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#914]
http://zimjs.com/code/shape.html

In the new version CreateJS 1.0 if we add a scale property to a shape, it will not work properly - for instance, it does not position.  The only thing I can see is that maybe it is obscuring the canvas scale() method.  It works in the other versions of CreateJS including the NEXT version.  Any thoughts?

> window.addEventListener("DOMContentLoaded", function() {
> 	var stage = new createjs.Stage("canvasElementId");
> 	var shape = new createjs.Shape();
> 	shape.scale = "test"; // this line causes positioning to fail in new CreateJS
> 	shape.graphics.f("red").dc(0,0,90);
> 	stage.addChild(shape);
> 	shape.x = 200;
> 	shape.y = 200;
> 	stage.update();
> });

**Comment by MannyC** [comment]
[`scale`](https://www.createjs.com/docs/easeljs/classes/Shape.html#property_scale) needs to be a number

**Comment by lannymcnie** [comment]
Scale is a new setter for `scaleX`/`scaleY`. Setting a non-number is not prevented, so it will probably break any calculations.
