### ISSUE TITLE
Documentation typo SpriteSheet (Cross Origin Issues)

### ISSUE THREAD

**Issue by sebastianderossi** [CreateJS/EaselJS#922]
https://www.createjs.com/docs/easeljs/classes/SpriteSheet.html

    var image = new Image();
    img.crossOrigin="Anonymous";
    img.src = "http://server-with-CORS-support.com/path/to/image.jpg";

image !=  img

**Comment by lannymcnie** [comment]
Thanks. Fixed and pushed.
