### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by szymkab** [CreateJS/EaselJS#924]
Hello everyone

Do any of you know how to run tests, I've followed instruction, but when I'm entering page it looks like that:

![zrzut ekranu z 2017-11-13 22-48-55](https://user-images.githubusercontent.com/13819284/32751126-fd11458a-c8c4-11e7-99b4-715ce3180eb6.png)

Is it correct? It seems not

**Comment by MannyC** [comment]
You should be following https://github.com/CreateJS/EaselJS/blob/master/tests/README.md with the commands being entered while in the `tests` folder (not the `build` folder).

I just tried it and got an error relating to `es5-shim` and `grunt-contrib-jasmine`.  Manually npm installing the `es5-shim` package into `grunt-contrib-jasmine`'s `node_modules` folder resolved the error.
