### ISSUE TITLE
Typo: setValue should be setValues

### ISSUE THREAD

**Issue by JonnyCodes** [CreateJS/EaselJS#927]
Hi,
I've been working on an issue where I can't get the width of cached text.
After looking through the recent commits, I noticed that it was fixed ([in this commit](https://github.com/CreateJS/EaselJS/commit/54e8c3e0016539ba00e5d8ea62eaed35abf31c12)) and merged into master.

But it looks like there has been a typo:
`BitmapCache.js:420`
    `return this._boundRect.setValue` should be `return this._boundRect.setValues`.

**Comment by sebastianderossi** [comment]
@JonnyCodes We'll have a closer look at this. Thanks!

**Comment by sebastianderossi** [comment]
Hi @JonnyCodes 
Nice one! I can confirm that it was indeed a typo that slipped by use. `BitmapCache.js` has been updated and pushed to **Master**.

Thanks!
