### ISSUE TITLE
Adding shapes slowing the FPS

### ISSUE THREAD

**Issue by joseph-olivemultimedia** [CreateJS/EaselJS#934]
see the code below.
I am adding 37 shapes and is this the right way to add its mousedown and mouseover event handlers. With this 37 shapes the performance are not slower, but it increases with additional 100 shapes. Please help me. 

for(var i = 1;i<37;i++)
		{
			BetValue_Array.push(betValue)
			//betValue+=1
			Independent_Bet_Container = new createjs.Container();
			
			Independent_Bet_Container.x = Current_Bet_X
			Independent_Bet_Container.y = Current_Bet_Y
			
			Independent_Bet_Shape = new createjs.Shape()
			Independent_Bet_Shape.graphics.beginFill("#FFFFFF").drawRect(0,0,Independent_Bet_Width,Independent_Bet_Height);
			Independent_Bet_Shape.alpha=0.8
			Independent_Bet_Shape.cache(0,0,Independent_Bet_Width,Independent_Bet_Height)
			Independent_Bet_Text = 	new createjs.Text([i],"BOLD "+"26px Britannic", "#000000");
			Independent_Bet_Text.regX = Independent_Bet_Text.getBounds().width/2
			Independent_Bet_Text.regY = Independent_Bet_Text.getBounds().height/2
			Independent_Bet_Text.x = (Independent_Bet_Width/2) + adjustX 
			Independent_Bet_Text.y = (Independent_Bet_Height/2) +Independent_Bet_Text.getBounds().height + adjustY
			Independent_Bet_Text.textAlign = "center";
			Independent_Bet_Text.textBaseline="alphabetic"
			Independent_Bet_Container.name = "Bet_Container"+i
			Independent_Bets_Array.push(Independent_Bet_Container)
			Current_Bet_Y -= Independent_Bet_Height + 1
			if(i == 9)
			{
				adjustX = 14
			}
			Independent_Bet_Container.addChild(Independent_Bet_Shape)	
			s_oStage.addChild(Independent_Bet_Container)
			if(i%3 == 0) //Splitting them in column for every 3 bets from bottom to top.
			{				
				Current_Bet_X = Current_Bet_X+Independent_Bet_Width+0.1
				Current_Bet_Y = Start_Bet_Y						
				for(var j = 0;j<3;j++)
				{
					Independent_Column_Bets_Array[columnCount][j] = j + (last_J + 1) 
				}		
				columnCount +=1 	
				last_J = j * columnCount			
			}
		}
		
		for(var i = 1;i<37;i++)
		{
			Selection_Bet_Container = new createjs.Container();
			Selection_Bet_Container.x = 5//-700
			Selection_Bet_Container.y = 5//-210
			
			Selection_Bets_Array.push(Selection_Bet_Container)
			Independent_Bets_Array[i].addChild(Selection_Bet_Container)
			Selection_Bet_Container.cache(0,0,Independent_Bet_Width,Independent_Bet_Height)
			Independent_Chips_Array.push(Selection_Bet_Container)
		}
		for(var i = 1;i<37;i++)
		{
			Independent_Bets_Array[i].on("mousedown", Independent_TableBetFun);
			Independent_Bets_Array[i].cursor='pointer'

		}
    }
	function Independent_TableBetFun(event)//-----------------------------This function used to animate the Independent selected Bet area.
	{
		Current_Bet_ID = Independent_Bets_Array.indexOf(event.currentTarget)
		console.log("Current_Bet_ID = "+Current_Bet_ID)
		if((BetValue_Array[Current_Bet_ID] + chipselval)<= maxbetVal)//--------------------------chipselval means it give the Bet value from the array
		{		
			BetValue_Array[Current_Bet_ID]+=chipselval
			var tempBetval = BetValue_Array[Current_Bet_ID]
			Independent_Chips_Array[Current_Bet_ID].uncache();
			Independent_Chips_Array[Current_Bet_ID].removeAllChildren()
			Independent_Chips_Array[Current_Bet_ID].cache(0,0,55,70)
			Independent_Bets_Array[Current_Bet_ID].alpha=0.1
			//console.log("Independent_Chips_Array[Current_Bet_ID]= "+Independent_Chips_Array[Current_Bet_ID].numChildren )
			//console.log(event.currentTarget.name+" selected ="+Independent_Bets_Array[Current_Bet_ID])
			for(var i=chipOption.length - 1;i>=0;i--)
			{
				quotient = Math.floor(tempBetval/chipOption[i])
				remainvalue = tempBetval%chipOption[i]
				remainvalue = remainvalue.toFixed(2)
				tempBetval = remainvalue
				Single_betArray[i] = quotient
			}
			var distance1 = 0
			for(var j = Single_betArray.length-1;j>=0;j--)
			{
				for(var j1 = Single_betArray[j];j1>0;j1--)
				{
					var distance = Math.round(Math.random() * 10)                     //chip position  Bet
					var index1 = chipOption.indexOf(chipOption[j])
					oSprite = ChipAyyay[index1];
					betImg = new createjs.Bitmap(oSprite)
					Independent_Chips_Array[Current_Bet_ID].addChild(betImg)
					//console.log("Independent_Chips_Array[Current_Bet_ID]= "+Independent_Chips_Array[Current_Bet_ID].numChildren)
					if(distance1 == 0)
					{
						distance1 = 1
						betImg.x=distance
						betImg.y=distance
					}
					else
					{
						distance1 = 0
						betImg.x=distance
						betImg.y=distance
					}
					betImg.scaleX = 0.5
					betImg.scaleY = 0.5
					betImg.y += 20
					betImg.x += 4
					Independent_Chips_Array[Current_Bet_ID].updateCache("source-over")
				}
				
			}
		}
		createjs.Sound.play("Sound1");
	}

**Comment by joseph-olivemultimedia** [comment]
I mean the line "Independent_Bets_Array[i].on("mousedown", Independent_TableBetFun);" is this right? Because Inside the Independent_Bets_Array, we have a container and inside each container we have this shape, Independent_Bet_Shape = new createjs.Shape()

Does adding more shapes will make the FPS slow, please confirm.

**Comment by lannymcnie** [comment]
Answered here: https://stackoverflow.com/questions/48267123/does-adding-more-shapes-will-slow-the-fps-in-createjs/48269481#48269481

**Comment by joseph-olivemultimedia** [comment]
Lanny thank you for the response, but is the way i wrote this line "Independent_Bet_Shape = new createjs.Shape() " inside the for loop is right or wrong.

**Comment by lannymcnie** [comment]
@joseph-olivemultimedia it depends on what you are trying to do. You can continue to draw to the same shape each iteration, but it may be harder to determine the cache bounds.

**Comment by joseph-olivemultimedia** [comment]
Ok thanks,  I found that we use stage.enablemouseover(20) which is the main reason as we have mouse over & mouse out for all most 150 bitmaps( shapes r converted to bitmaps), is there any way to have better performance with mouse over & mouse out functionality,  also I tried stage.enablemouseover(1), Does this the solution or do u know any other solution.

**Comment by lannymcnie** [comment]
Do you need mouse interaction on everything? It can be pretty expensive. Turning it off on items that don't need interaction is a good way to speed that up.

**Comment by joseph-olivemultimedia** [comment]
Yes I need it on everything, maybe if I click on it I can make stage.enablemouseover(0). After that i can  again set it to 1 or 10 or 20, right.  Any idea
