### ISSUE TITLE
CreateJS no longer recognizes hit areas in Chrome 64.0.3282.119 

### ISSUE THREAD

**Issue by mjonkman** [CreateJS/EaselJS#937]
With the release of Chrome 64.0.3282.119 we are finding that CreateJS no longer recognizes hitAreas that are MovieClips, *if* those MovieClips are cached. Simple shapes or MovieClips that are not cached continue to work fine as the hitArea. All other browsers including Chrome 63.x.x.x work fine with MovieClips that are cached. 

We utilize MovieClips extensively for hitAreas (DisplayObject.hitArea). In our code base, we process the JS output from Animate CC into TypeScript classes and automatically cache most MovieClip instances on creation. This sudden change in behavior has had a huge negative impact on our product. Our solution has been to uncache these hitArea clips and make sure they are removed from the stage though this too has other ramifications. Often we used a "background" clip within the symbol to be the hitArea. Thus we have had to sometimes add a duplicate clip to take care of that function.  

This behavior occurs on Windows 10 as well as Chrome OS. Has not been tested on Mac.

**Comment by PixelTom** [comment]
Can confirm this happens to us as well on Mac with cached bitmaps. We've had to uncache them to get it to work.

@mjonkman if you test this in Canary (v66) the issue seems to have resolved itself.

**Comment by lannymcnie** [comment]
Does this problem affect cached HitAreas that aren't MovieClips? Do you have a simple reproduction case?

**Comment by lannymcnie** [comment]
Can you provide an isolated sample to show the issue? I made a quick spike, and it seems to work as expected.
https://jsfiddle.net/lannymcnie/fydkx9pp/3/

**Comment by mjonkman** [comment]
I've tasked a member of my team to create a simpler test case for you as our product is fairly large and complex.  My team is still running full out to get things running stably again across browsers and meet a revised late deadline so our response might not be immediate but should be within 24-36 hr.

**Comment by mjonkman** [comment]
The following fiddle shows the issue

https://jsfiddle.net/mjonkman/hrx680ns/

To provide a bit of background, we develop in TypeScript so we modify the js output from AnimateCC and convert each symbol into a TypeScript class - with us setting the bounds and caching the item (note we cache at 2x). The output at the top of this file represents output from the TypeScript compiler back into JavaScript. I don't believe this is the source of any of the issues but just thought I'd explain what you are seeing.

In the example above the hitArea will respond correctly around the Glasses and an area below it on IE, Edge, Chrome 63 etc. However, you will notice that the hitArea doesn't respond in Chrome 64. Just below the creation of the hitArea clip, is a commented out section that uncaches the ha clip. Uncomment the uncache and the hitArea immediately responds in Chrome 64. I have not tested this with the Canary release for Chrome 66.

Normally there is a text label associated with the icon and thus the hit area is bigger then just the glasses icon.

**Comment by MannyC** [comment]
Works without uncommenting for me, Chrome for Linux version 64.0.3282.140 

Just a note on canary: I'm pretty sure there's no guarantee that something in canary ever lands in stable.

**Comment by PixelTom** [comment]
Testing the demo from @mjonkman I can replicate the problem.

Chrome, Mac, Version 64.0.3282.140 (Official Build) (64-bit)

macOS Sierra: 10.12.6

**Comment by lannymcnie** [comment]
Looks like this is related to the cache size. Changing it back to 1 causes it to start working. Around 1.5, it stops working. We can take a deeper look to see if there is something we can do.

**Comment by Cpt0r** [comment]
@lannymcnie the issue occurs when adding a click handler to the object that was cached - in your example the click handler is added to the **un**cached bitmap.

To replicate the issue:
- add `bmp.cache()`
- del `bmp.hitArea = mc`

Forcing the `hitArea` works but this is a workaround at best - one we (@PixelTom and I) are currently forced to use in some cases.  In fact even `bmp.hitArea = bmp` doesn't work.

Specifically we're using it in our custom TextStroke class which uses it's own internal canvas - where I believe the issue occurs ie. Chrome is ignoring pixels that come from a source not tied to the 'active' canvas, which is how the caching mechanism works, too.

**Comment by Cpt0r** [comment]
...damn you github and your lack of auto update when new content arrives...

**Comment by lannymcnie** [comment]
We did a bunch of testing, and came to some unfortunate conclusions. It looks like this is a browser bug, and there is nothing we can do about it, and you'll just have to wait until the next version of Chrome.

I created a custom build of CreateJS that visualizes the hitTest a little better using this [modified demo](https://jsfiddle.net/lannymcnie/hrx680ns/5/). Using this demo, it is clear that the content getting drawn to the "hit test" canvas is not behaving appropriately. Specifically it will constantly "lock" to the top right, and ignore the objects transformation.

We were hopeful there was just a place we were getting a bad canvas size back, and could handle it, but that is not the case.

Digging deeper in your demo, the error happens when the cache scale exceeds approximately 1.46. When it is any larger, the number of pixels in the canvas exceeds 2^16, and the error presents. You can change the cache size, and then adjust the scale factor, and this is true every time. 

> For example, we set the cache size to `0,0,200, 50, 2.56`, resulting in a canvas size of 512x128, or 65,536 pixels (2^16) and it works! Set the width to 201, and the problem re-appears. 

So the issue is perhaps some kind of internal integer overflow. The fact that this doesn't happen in Chrome Canary should mean the problem disappears shortly. Unfortunately there isn't anything we can do at this time. Sorry!

**Comment by PixelTom** [comment]
Thanks for your time @lannymcnie 

We've disabled caching on most clickable/draggables and forced hitAreas where we can and that's fixed it for now. Will keep an eye out when v66 drops whether we can revert the change.

**Comment by mjonkman** [comment]
Likewise, we've been working around it and making sure that items that don't need to be cached are no longer being cached. We probably went overboard on caching in the first place. I appreciate the CreateJS team looking into it. Are you planning on keeping this on your radar?

**Comment by mjonkman** [comment]
I just wanted to let folks know that Chrome updated again to Version 64.0.3282.140 and the hitArea issue has gone away. It officially the roll out started on Feb 1. I just updated it by going to -> Help -> About Chrome. It seems to be rolling out across devices and platforms. The HitArea issue appears to have gone away. @MannyC mentioned it above, but I totally missed the version number difference and attributed it to being Linux instead of Windows (my mistake). I will have another of my team members checking on the render out of place issue #938 and will update that bug accordingly.

**Comment by mjonkman** [comment]
Crap after rebooting the computer it seems to be broken again. So much for jumping to conclusions. I had rolled back to a 63 build to test something yesterday and apparently the update must have still used the 63 build after the update. Sorry.
