### ISSUE TITLE
TypeError: Argument 2 of WebGLRenderingContext.bindTexture

### ISSUE THREAD

**Issue by joakimkm** [CreateJS/EaselJS#947]
In Version 1.1.0 (April 05, 2018) "TypeError: Argument 2 of WebGLRenderingContext.bindTexture does not implement interface WebGLTexture" is throwed when doing this:

1. Drawing rect with cache and adding to stage
2. Calling updateViewport();

Here is codepen with issue: 
https://codepen.io/joakimk/pen/GxPbLj?editors=0011

Error is not given in version 1.0.0 and earlier

**Comment by DavidHGillen** [comment]
https://github.com/DavidHGillen/EaselJS/blob/master/src/easeljs/display/StageGL.js#L1599

Here's the fix. We'll get that integrated pronto.

**Comment by lannymcnie** [comment]
This has been pushed to GitHub, and new libs generated.
Cheers!
