### ISSUE TITLE
Font size in IE Edge has a bug

### ISSUE THREAD

**Issue by shaderbytes** [CreateJS/EaselJS#951]
Here is a js fiddle to test : 

https://jsfiddle.net/4vw78zrk/

I am having issues in my big project , it works fine on chrome , firefox ,and even IE 11 , but not on Edge. I replicated the bare bones of the code needed to show the error in the fiddle.

What is happening is the font is rendered at some small size in the canvas, way smaller than it should. There are no errors logged to the console. I cant find anything about this on google. Please help.

**Comment by shaderbytes** [comment]
Just did some more testing , the scale appears to always be a 10th of the font-family text size you set. For example if you set the size 50px , then setting the scaleX and scaleY to 5 will fix the size , not that you want to do that just pointing out a pattern i noticed.

Sadly with more texting trying the trick above it then dawned on me it is not using the correct font face either. Again this is only a problem on Edge (Microsoft Edge 41.16299.371.0) and this problem does not occur in Chrome , Firefox or IE 11

**Comment by shaderbytes** [comment]
Here is a fiddle using vanilla canvas code :

**Comment by gskinner** [comment]
Sorry for the delay. I appreciate the repo cases. I'm hoping to fire up my VM and look at these in Edge later today or tomorrow. It seems like an odd issue, since we just pass the font string into canvas directly, with no modification. Text is a pretty simple class.

**Comment by shaderbytes** [comment]
Thanks Grant chat soon then

**Comment by shaderbytes** [comment]
![image](https://user-images.githubusercontent.com/2153214/39972741-a88cd0da-5715-11e8-93c1-9f16ad3234db.png)

**Comment by danzen** [comment]
It looks fine in my Edge - what about the overall font scaling of the browser.  If that accidentally got made smaller it would look like this - so perhaps try a CTRL + to increase font size?

**Comment by shaderbytes** [comment]
that is a rather silly answer since i sent a screenshot of my two monitors , one with chrome and one with edge.. if the zoom of the browser was not 100% then all the copy in the html and js sections of the jsfiddle website would be affected as well. It is easy to see they are not and that the font size is the same for those sections of the website on both chrome and edge.

Secondly the vanilla canvas fiddle i sent afterwards does not have this problem. I hope you did click that and respond please click the first fiddle link i sent : 

https://jsfiddle.net/4vw78zrk/

if possible attach a screenshot showing it working as it should in edge.

**Comment by shaderbytes** [comment]
i ffixed it .. was a typo Urrgg..
So for font I had an extra parameter for font-weight , i had a numeric size and i had "normal" which tyhen pushed the other parameters out by one index. So anyway thanks for looking it should be : 

var font =  "normal normal normal"+("50")+"px / normal "+("Arial");
