### ISSUE TITLE
Method DisplayObject.getCacheDataURL() breaks

### ISSUE THREAD

**Issue by DavidCasillasRivero** [CreateJS/EaselJS#956]
Version used: 1.0.0:
 
Calling `DisplayObject.getCacheDataURL()` method breaks with console error `this.bitmapCache.getDataURL() method undefined`.

Debugging gives this piece of breaking code in `easeljs.js: 6700`, in `DisplayObject` class definition: 

```
	p.getCacheDataURL = function() {
		return this.bitmapCache?this.bitmapCache.getDataURL():null;
        };
```

Changing the code by this one works for me:
```
	p.getCacheDataURL = function() {
		return this.bitmapCache?this.bitmapCache.getCacheDataURL():null;
        };
```

`BitmapCache` class does not implement any  `getDataURL()` method only `getCacheDataURL()`

**Comment by lannymcnie** [comment]
Thanks, good catch!

We can fix it on our end. Feel free to submit a pull request for stuff like this.

**Comment by MrJop** [comment]
You absolute legend! Just saved my day :)

**Comment by danbraun** [comment]
Hi. This error still appears for me using the CDN for the full "createjs" combined library via 'https://code.createjs.com/1.0.0/createjs.min.js' 

"getDataURL" still being used as shown here from https://raw.githubusercontent.com/CreateJS/CreateJS/master/dist/createjs.js
`/**
	 * Returns a data URL for the cache, or null if this display object is not cached.
	 * Only generated if the cache has changed, otherwise returns last result.
	 * @method getCacheDataURL
	 * @return {String} The image data url for the cache.
	 **/
	p.getCacheDataURL = function() {
		return this.bitmapCache?this.bitmapCache.getDataURL():null;
	};`

**Comment by lannymcnie** [comment]
@danbraun The fix is in EaselJS NEXT build that you can find in the libs/ folder in GitHub. It has not yet been published to the CDN. We are planning a dot-release in the next month or so.

Cheers,
