### ISSUE TITLE
2.0 Beta Stage Issue

### ISSUE THREAD

**Issue by yeager-j** [CreateJS/EaselJS#957]
### Issue Details
* Version used (Ex; 1.0): v2.0 Beta

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors): 

My code:

```typescript
import { Bitmap, Container, Stage, Ticker, Touch } from '@createjs/easeljs';
import { Component, Prop, Vue } from 'vue-property-decorator';
import { Created } from '../../../../modules/lifecycle';

@Component
export default class StupidImage extends Vue implements Created {
	@Prop() public image: string;
	@Prop() public initialProps: any;

	public stage: any = null;
	public offset: any = null;
	public update: boolean = true;

	public created() {
		this.stage = new Stage('stupidImage');

		Touch.enable(this.stage);

		this.stage.enableMouseOver(10);
		this.stage.mouseMoveOutside = true;

		const image = new Image();
		image.src = this.image;
		image.onload = this.handleImageLoad;
	}

        // ...
}
```

Error:

```
[Vue warn]: Error in created hook: "TypeError: _createjs_easeljs__WEBPACK_IMPORTED_MODULE_0__.Stage is not a constructor"

found in

---> <StupidImage> at src/components/editor/typography/stupid-image/stupid-image.vue
       <VCard>
         <Typography> at src/components/editor/typography/typography.vue
           <VTabItem>
             <VTabsItems>
               <VTabs>
                 <VNavigationDrawer>
                   <VApp>
                     <Editor> at src/components/editor/editor.vue
                       <VApp>
                         <MainApp> at src/App.vue
                           <Root>
```

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

Chrome Version 66.0.3359.139 (Official Build) (64-bit)

* Do you know of any workarounds?

Nope

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

**Comment by CodeScriptum** [comment]
A temporary workaround for this issue is to import `@createjs/easeljs/dist/easeljs.module.js` instead. since you are using webpack you can add an alias for that in webpack config.
```
resolve: {
    extensions: ['.js', '.json'],
    alias: {
      '@createjs/easeljs': '@createjs/easeljs/dist/easeljs.module'
    }
  },
```
then you can use `import {...} from '@createjs/easeljs'` as you would normaly do

**Comment by tehvgg** [comment]
`browser` field was dropped from the package so bundlers stop using the global module, this issue is resolved.
