### ISSUE TITLE
Stage can't not disable mouse events after initialization

### ISSUE THREAD

**Issue by Mactaivsh** [CreateJS/EaselJS#959]
I enable the mouse events during the stage initialization

and I want to disable or enable this behavior conditionally

according to the official docs

> Enables or disables (**by passing a frequency of 0**) mouse over (mouseover and mouseout) and roll over events (rollover and rollout) for this stage's display list. 

 but it seems not working

check the this [fiddle](https://jsfiddle.net/x2b5kezw/3/)

### Details
* Version: 1.0 
* OS & Browser version: Mac os 10.13.4, Chrome 66.0.3359.139

**Comment by MannyC** [comment]
That enables or disables mouse over/roll over events, not clicks.  Those events have to actively poll to see if they should trigger, which is why they are disabled by default.

**Comment by Mactaivsh** [comment]
Thanks,  I just found that I was mislead by my carelessness. 😯
