### ISSUE TITLE
CORS issue with 7 images but not with 6 images

### ISSUE THREAD

**Issue by alkisg** [CreateJS/EaselJS#961]
Hi, I've created a clone of a gcompris game, and while it works fine in firefox, I'm getting the following error in google chrome:
> An error has occurred. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.

I've read a lot about CORS and tried various things, to no avail. I did get the following very weird test case though:
* Works: https://ermis.dschool.edu.gr/preschool/mosaic/index2.html
* Fails: https://ermis.dschool.edu.gr/preschool/mosaic/index3.html

The difference between them is only one number!!! If I try to draw 6 images in the bottom line, it works, but if I try to draw 7 images, it fails! The rest 20+ images that I draw in the top boxes work fine in both cases.

Is there some limit in easeljs that I could increase to work around the issue?

Note that all my images are .svg, which I've read have additional issues with CORS, yet also note that they work fine in the "6 tiles" test case, so it doesn't sound like an issue in .svg.

**Comment by lannymcnie** [comment]
EaselJS simply draws content to the canvas that you provide, so it is very unlikely that the library is doing anything specific. Similarly, the fact that it works until it hits a specific resource, makes me think its an issue with the actual image.

Have you tried changing the order of the clips to see if its a specific image that is causing the error? Digging in, it appears "pencils.svg" is the image throwing the errors, so maybe swap its position to the first spot, or remove it from the list entirely, to see if its a resource problem.

It looks like `pencils.svg` has a bunch of references to external resources, which is the main difference I can find.

```
<cc:Work><dc:format>image/svg+xml</dc:format><dc:type
--
  | rdf:resource="http://purl.org/dc/dcmitype/StillImage" /><cc:license
  | rdf:resource="http://creativecommons.org/licenses/publicdomain/" /><dc:publisher><cc:Agent
  | rdf:about="http://openclipart.org/"><dc:title>Openclipart</dc:title></cc:Agent></dc:publisher><dc:title>pencil</dc:title><dc:date>2012-06-06T22:34:07</dc:date><dc:description>A pencil clipart</dc:description><dc:source>http://openclipart.org/detail/170449/pencil-by-freevectorfinder-170449</dc:source><dc:creator><cc:Agent><dc:title>freevectorfinder</dc:title></cc:Agent></dc:creator><dc:subject><rdf:Bag><rdf:li>art</rdf:li><rdf:li>artistic</rdf:li><rdf:li>blue</rdf:li><rdf:li>clip art</rdf:li><rdf:li>clipart</rdf:li><rdf:li>collection</rdf:li><rdf:li>color</rdf:li><rdf:li>colorful</rdf:li><rdf:li>creative</rdf:li><rdf:li>design</rdf:li><rdf:li>draw</rdf:li><rdf:li>education</rdf:li><rdf:li>equipment</rdf:li><rdf:li>eraser</rdf:li><rdf:li>green</rdf:li><rdf:li>illustration</rdf:li><rdf:li>inscription</rdf:li><rdf:li>job</rdf:li><rdf:li>notice</rdf:li><rdf:li>object</rdf:li><rdf:li>office</rdf:li><rdf:li>pencil</rdf:li><rdf:li>scalable</rdf:li><rdf:li>school</rdf:li><rdf:li>set</rdf:li></rdf:Bag></dc:subject></cc:Work>
```

This is just a guess. It might not be this particular block of SVG, but from what I have read, SVG can taint the canvas if it has internal references in it. If this specific image is the issue, then you can look into re-exporting it.

**Comment by alkisg** [comment]
Hi lannymcnie!

I removed the following tag from pencils.svg, and everything worked fine afterwards:
```
<foreignObject y="0" x="0" requiredExtensions="http://ns.adobe.com/AdobeIllustrator/10.0/" 
width="1" height="1" id="foreignObject6" />
```

What threw me off was that in the working version, "index2.html", I was already drawing pencils.svg in the top left box without it causing any issues! I still can't explain why it was working in the top left box and not in the bottom box, but I'm very glad that I can use canvasjs with svg!

Thank you very much for your help, I'm closing the issue.
