### ISSUE TITLE
drawArrays: no buffer is bound to enabled attribute

### ISSUE THREAD

**Issue by davidcalimero** [CreateJS/EaselJS#963]
Hello!

I'm having an issue when trying to use a custom shader with Createjs.

When running the attached code it gives the following warning:

WebGL: INVALID_OPERATION: drawArrays: no buffer is bound to enabled attribute

after executing gl.drawArrays(gl.TRIANGLES, 0, 6). However, this does not happen when I comment the following lines:

var stage = new createjs.StageGL("demoCanvas");   
stage.update();

I don't see anything wrong with my code.

[index.html.zip](https://github.com/CreateJS/EaselJS/files/2039551/index.html.zip)

**Comment by davidcalimero** [comment]
Ok, it seems I found the problem. I had to add this before setting up the shader program to draw:

for(var i = 0; i<8; i++)
 gl.disableVertexAttribArray(i);

Createjs is not disabling every attribute it enables

Is this intended?

**Comment by DavidHGillen** [comment]
Glad you fixed your issue.

Currently StageGL is pretty tuned to drawing exactly the way it's intended to draw. I totally get that this stops your ability to do some cool things for yourself like per object tinting or mesh rendering but they weren't phase 1 goals.

I have it on my roadmap to add a proper API for doing what you want, a custom shader to render all the DisplayObjects, but it's not going to be quick. I wont commit to a timeline right now sorry, but feel free to share the results of any experiments you do. It might speed up my process if I know some gotchas.

In the meantime I recommend anyone who has very custom drawing demands to consider making a new Filter. Filters are expected and designed to have swapable shaders, while they are expected to process a single element covering the scene the shaderParamSetup call on them is the window and reference you need to do all sorts of customization, so long as you set it back afterwards.
