### ISSUE TITLE
getObjectsUnderPoint and devicePixelRatio

### ISSUE THREAD

**Issue by DHTMLGoodies** [CreateJS/EaselJS#966]
First of all: A fantastic library for working with the canvas.

A place in our code, we have an event listener. In the callback we want to find objects under stageX, stageY
```
let objects = stage.getObjectsUnderPoint(evt.stageX, evt.stageY);
```

where evt is of type MouseEvent

This works very well on a device where window.devicePixelRatio is 1. However, on a mac with devicePixelRatio of 2, it does not work so well. For now, we're solving it by dividing evt.stageX and evt.stageY with window.devicePixelRatio

```
let r = window.devicePixelRatio;
let objects = stage.getObjectsUnderPoint(evt.stageX / r, evt.stageY / r);
```
Is this a bug in the library or the intended behaviour?

**Comment by lannymcnie** [comment]
Sounds like a bug, we can check it out.

**Comment by DHTMLGoodies** [comment]
I have created a sample based on the parts of our code which seems to be involved in this. 

When working through our code in order to set up an example for you, I noticed that the problem happens because we multiply canvas.width and canvas.height by window.devicePixelRatio, but do not do the same for canvas.style.width and canvas.style.height, i.e. this part:

```
            var width = 1000;
            var height = 1000;
            canvas.width = width * window.devicePixelRatio; 
            canvas.style.width = width + 'px';
            
            canvas.height = height * window.devicePixelRatio; 
            canvas.style.height = height + 'px';
            
            stage.scaleX = stage.scaleY = window.devicePixelRatio;
```
We do this to get the best possible resolution on hdpi devices (probably inspired by https://gist.github.com/vicro/5829162 and https://www.html5rocks.com/en/tutorials/canvas/hidpi/). 

Here's the full code sample
```
<html>

<head>
    <script type="text/javascript" src="https://code.createjs.com/1.0.0/easeljs.min.js"></script>

    <script type="text/javascript">

        function init() {

            var stage = new createjs.Stage("demoCanvas");
            var rect = new createjs.Shape();
            rect.graphics.beginFill("DeepSkyBlue").rect(0,0,500,500);
            rect.x = 100;
            rect.y = 100;
            stage.addChild(rect);
            
            


            var canvas = stage.canvas;
            var width = 1000;
            var height = 1000;

            // This is probably causing the problem since width and style.width is different
            canvas.width = width * window.devicePixelRatio; canvas.style.width = width + 'px';
            canvas.height = height * window.devicePixelRatio; canvas.style.height = height + 'px';
            stage.scaleX = stage.scaleY = window.devicePixelRatio;

            stage.update();


            stage.addEventListener("stagemousedown", function(evt){
                console.log(stage.getObjectsUnderPoint(evt.stageX, evt.stageY));
            });
        }

    </script>
</head>

<body onload="init();">
    <canvas id="demoCanvas" width="1000" height="1000"></canvas>
</body>

</html>
```

**Comment by lannymcnie** [comment]
I think the problem here is that you are changing the canvas to be high resolution, by over-sizing it, then counter-scaling it with CSS. Unfortunately when a canvas is scaled via CSS, it messes with the coordinate system.

It might be nice to handle this somehow internally with EaselJS, but currently there is no support.

**Comment by DHTMLGoodies** [comment]
Then we stick to the stageX / window.devicePixelRatio solution.

Thanks
