### ISSUE TITLE
Losing bounds after caching?

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#968]
If I add a shape or whatever with bounds to a Container and do not set the bounds of the container, I can successfully getBounds() and dimensions are reflected.  But if I cache the container afterwards, and then getBounds() it is giving me 0 for bound x, y, width and height.  If, before I cache,  I hard code a setBounds() to the values of getBounds() and then cache - the values of getBounds() after the cache work - the bounds are good.  (using CreateJS 1)

```
var container = new createjs.Container();
stage.addChild(container);
var box = new createjs.Shape();
box.graphics.drawRect(0,0,100,100);
box.setBounds(0,0,100,100);
container.addChild(box);
console.log(container.getBounds()); // 0,0,100,100 (good)
// container.setBounds(0,0,100,100); // uncommenting fixes bad below
container.cache(0,0,100,100);
console.log(container.getBounds()); // 0,0,0,0 (bad)
```

**Comment by lannymcnie** [comment]
Good catch, could be an issue witch calculating cache bounds. We will take a look!

**Comment by lannymcnie** [comment]
It looks like this was resolved already, and is available in the NEXT version of EaselJS. Sorry for the inconvenience!

Here is a fiddle with your code, and the latest NEXT version: https://jsfiddle.net/d8go7x2w/
