### ISSUE TITLE
Texture load failure in several android smartphones in the latest version of easeljs-NEXT

### ISSUE THREAD

**Issue by Nestorferrando** [CreateJS/EaselJS#969]
Hi!

we recently noticed that with the latest NEXT build, the atlas texture load fails on certain android devices, showing the following message on the console: 
"Invalid image provided as source. Please ensure source is a correct DOM element. <img src=​"public/​chinchon_atlas_.png?1524563253728">​"

The same  app works perfectly on other devices and PCs.

Looking for a little bit, when _loadTextureImage executed, for some reason, the comparisons

> if (image instanceof Image && image.src)
> if (image instanceof HTMLCanvasElement)

 are evaluated as "false" on these devices.  Adding some console debugging, these outputs:

 	p._loadTextureImage = function (gl, image) {
		var srcPath, texture, msg;
		console.log(image)
		console.log(image instanceof Image)
		console.log(image instanceof HTMLCanvasElement)
                ...

show this result:
![image](https://user-images.githubusercontent.com/4629402/41983314-0970a4e0-7a2e-11e8-81cc-95d72a2c133e.png)

Weird behavior. Maybe is some bug on the browser of these devices?

We solved it by just commenting the _instanceof Image_ checking.

**Comment by Nestorferrando** [comment]
BTW, if you need detailed data about the devices  (android version, Chrome version), let me know.

**Comment by DavidHGillen** [comment]
Given the fact it works else where we'll have to figure out how important the type safety is before simply removing it. Have you submitted browser bugs? I'd love to get the list of devices and browsers with this issue if you can. Thanks for bringing this to our attention.

**Comment by Nestorferrando** [comment]
Hi! I worked a little bit more into the problem. This is a small survey of working and not working devices:

not working devices:

```
alcatel PIXI, Android 6.0, Chrome 55.0.2883.91
Samsung Galaxy S6, Android 7.0, Chrome 56.0.2924.87
LG G2 Mini, Android 5.0.3, Chrome 34.0.1847.118
```

working devices:

```
gretel A7, Android 6.0, Chrome 67.0.3396.87
huawei Y6 II, Android 6.0, Chrome 64.0.3282.137
wiko SUNNY, Android 6.0  ,Chrome 61.0.3163.98
```

It seems a problem with phones with web browsers that cannot be updated .

On these browsers, the texture is loaded as an instance of  _HTMLImageElement_ instead of _Image_.  

Modifying the type checking comparison to: 

```
if ((image instanceof Image || image instanceof HTMLImageElement) && image.src)   {
			srcPath = image.src;
```

makes it working again on these browsers and keeps type checking safety.

Cheers

**Comment by DavidHGillen** [comment]
Tested the change on a variety of devices with no ill effects. Worked it into the latest.
