### ISSUE TITLE
2.0.0-beta.2 fails to load because of "Uncaught ReferenceError: Ticker is not defined"

### ISSUE THREAD

**Issue by arcatdmz** [CreateJS/EaselJS#972]
### Issue Details
* Version used (Ex; 1.0): 2.0.0-beta.2

* Describe whats happening:

To reproduce the bug, type the following commands with `yarn` and `parcel` installed on your computer:

```
git clone https://github.com/arcatdmz/CreateJSExample.git
cd CreateJSExample
yarn install
yarn develop
```

This will launch the web server at `http://localhost:1234` and loading it on a web browser fails because of the `Uncaught ReferenceError` as noted in the issue title. I initially thought this is due to the build pipeline bug and opened an issue at https://github.com/CreateJS/build/issues/1.

Further investigation on my side revealed that this error is happening because `Ticker` is not imported from anywhere in the EaselJS 2.0 codebase.

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

Windows 10 Pro, Edge 42.17134.1.0 & Chrome 67.0.3396.99

* Do you know of any workarounds?

Adding the following line of code at the top of https://github.com/CreateJS/EaselJS/blob/2.0/src/main.js and re-building the library addressed the issue.

```
import Ticker from "@createjs/core/src/utils/Ticker";
```

* Provide any extra details that will help us fix your issue.

https://github.com/arcatdmz/CreateJSExample

**Comment by arcatdmz** [comment]
Another option to address the issue would be to edit lines around https://github.com/CreateJS/build/blob/master/gulpfile.babel.js#L146 and remove the code to export `Ticker` from the EaselJS library, but I believe this would cause different kinds of issues. (apps using EaselJS usually make use of `Ticker` and it would be inconvenient if it were not included in the `@createjs/easeljs` library.)

**Comment by Lange** [comment]
Yep, I'm also running into this. This is one of just a couple very small bugs preventing EaselJS 2.0 from being used in browsers today, would love to get it fixed!

**Comment by arcatdmz** [comment]
I confirmed that the latest `2.0.0-beta.4` addresses the issue.
Accordingly, I've updated the repo.

https://github.com/arcatdmz/CreateJSExample

Thanks for the hard work!
