### ISSUE TITLE
SpriteSheet get wrong frame

### ISSUE THREAD

**Issue by DrMinh** [CreateJS/EaselJS#974]
I use this image: [Image](https://imgur.com/rlGIsgs)

This is my code:
`			var maptt=new createjs.SpriteSheet({
				images: [mapload.getResult("e11")],
				frames: {width:80, height:60},
				animations: {
					stop:0,
					go:[0,1,true,0.1],
					hurt: 2,
				}
			});`
And this is "hurt" : [hurt](https://imgur.com/8f70nCV)
there are a very small red line of frame 0 on "hurt". Why It not cut correct frame? (i test on Chrome and Android)

**Comment by DavidHGillen** [comment]
What is probably occuring is that Anti-Aliasing effects are causing the top image to bleed over into the bottom when it's being smoothed for rendering. This is not something EaselJS can reliably control. As such the recommendation is to include a few pixels of dead space between your frames so if they do bleed then they don't bleed into another frame. Most spritesheet generation tools should have a control for this option with a name like "spacing", "buffer", or "isolation".

That should get your problem sorted.

If there's anything else don't hesitate to ask. Thanks.
