### ISSUE TITLE
hitTest (→mousedown) fails on webgl cached DisplayObject

### ISSUE THREAD

**Issue by adabru** [CreateJS/EaselJS#977]
Using examples/WebGL/Filters_GL-GL.html from master branch (commit c7b6035840d37bac5cfa205af844c041dd57f762) and adding the line `bmp.hitTest(0,0)` leads to following error (Ubuntu 16.04, Chrome 69.0.3497.42  beta 64-bit):

```
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at BitmapCache.p.draw (easeljs-NEXT.js:15625)
    at Bitmap.p.draw (easeljs-NEXT.js:6705)
    at Bitmap.p.draw (easeljs-NEXT.js:11883)
    at Bitmap.p.hitTest (easeljs-NEXT.js:7016)
    at Image.handleImageLoad (Filters_GL-GL.html:68)
```

The provided value metioned in the error message is of type `WebGLTexture` instead. `bmp.on('mousedown', ()=>{})`  plus clicking causes the same error for same reason. 

The general problem as I see it is that currently for the hitTest a 1x1-sized canvas is created, its '2d' context is acquired, the object is drawn on it and the pixel for the test is queried with `ctx.getImageData(0,0,1,1)`, as can be seen in the following code references:

https://github.com/CreateJS/EaselJS/blob/c7b6035840d37bac5cfa205af844c041dd57f762/src/easeljs/display/DisplayObject.js#L543-L548
https://github.com/CreateJS/EaselJS/blob/c7b6035840d37bac5cfa205af844c041dd57f762/src/easeljs/display/DisplayObject.js#L1083-L1088
https://github.com/CreateJS/EaselJS/blob/c7b6035840d37bac5cfa205af844c041dd57f762/src/easeljs/display/DisplayObject.js#L1322-L1325

 I guess the problem with webgl-cache is that it is stored on the gpu and not as easy accessible as a `getImageData`. I'm basing my guess solely on the following comment:

https://github.com/CreateJS/EaselJS/blob/c7b6035840d37bac5cfa205af844c041dd57f762/src/easeljs/filters/BitmapCache.js#L366-L370

I don't know a solution, imo a solution depends on hitTest's use cases. For my case, as a workaround, I'm planning to override the DisplayObject's `hitTest` with a custom function that either uses a context2d-duplicate to do the hitTest or simply checks for the object's bounds in this function.

**Comment by DavidHGillen** [comment]
Thanks for the detailed report, the fix was basically to avoid this error state as the WebGLTexture can't be used in the 2D context drawing which takes place for hit testing as it stands.

I do recommend writing your own hit testing if you don't need pixel perfect hit interactions though!
