### ISSUE TITLE
Movieclip not stopping on appropiate frame

### ISSUE THREAD

**Issue by Nestorferrando** [CreateJS/EaselJS#981]
if a this.stop() is added as a frame action, sometimes the movieclip does not stop in that frame but on the next one.

![image](https://user-images.githubusercontent.com/4629402/45211979-ff6bed80-b293-11e8-938e-6ee299db7d52.png)

This is because in the MovieClip code (line 519), several frames can be advanced without any checking (and their actions called) if the time step is big enough:

**while (frames--) { this._updateTimeline(this._rawPosition+1, false); }**
 
I solved it by just added a checking before processing each frame:

**while (frames-- && !this.paused) { this._updateTimeline(this._rawPosition+1, false); }**

**Comment by gskinner** [comment]
Good catch. Looking at the code, there's a comment immediately above that:
`// TODO: should we also check this.paused here instead?`

So it looks like I was thinking about this, but didn't come back to it.

I'm going to remove the check for `this.paused` above that, and inject the check in the `while` loop similar to your solution. This will also allow `this._t` to be updated correctly even while paused.

**Comment by gskinner** [comment]
Resolved with 70f9d9a9fd9858d8bd1711ddc120b2c5be1bcc37
