### ISSUE TITLE
Math in CreateJS

### ISSUE THREAD

**Issue by ry-randall** [CreateJS/EaselJS#983]
Hello,

Just wanted to share that we’ve recently open sourced a library which allows the displaying of Mathematical equations in the canvas (via LaTeX).

This library supports createjs as a renderer. Each character is rendered as one of createjs' display objects.

Feel free to check it out! https://github.com/CurriculumAssociates/canvas-latex

**Comment by danzen** [comment]
Looks exciting... can you please point me to a single script I can use.  I tried the node install and all I seemed to have gotten is 888 folders.  Maybe it had something to do with an update to node it prompted me to do after.  Anyway - not the best at this node stuff... if you could compile a minified file to use with CreateJS or point me to where one exists it would be greatly appreciated.  Your example calls canvas-latex.js but that is nowhere to be found.

**Comment by ry-randall** [comment]
@danzen Did you try running `npm start` after install?

**Comment by danzen** [comment]
Yes - it gave me a 4 or 5 errors sort of the same but kind of made it through.  At that point, what is supposed to happen?

**Comment by ry-randall** [comment]
@danzen I'm going to close this issue to reduce any noise. Feel free to open an issue on that repo with the relevant info (i.e. screenshots, description of problem, etc.). I'd be happy to help you out there.
